from .function import Function

from .call_protocol import CallProtocol
from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AcceptCall(Function[Ok]):
    """
    Accepts an incoming call

    :param call_id: Call identifier
    :param protocol: The call protocols supported by the application
    :return: :class:`Ok`
    """
    __slots__ = ("call_id", "protocol", "_extra", "_client_id", "_type")

    def __init__(self, call_id: int = 0, protocol: CallProtocol | None = None):
        self.call_id = call_id
        self.protocol = protocol
        self._type = "acceptCall"