from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AcceptedGiftTypes(ObjectBase):
    """
    Describes gift types that are accepted by a user

    :param unlimited_gifts: True, if unlimited regular gifts are accepted
    :param limited_gifts: True, if limited regular gifts are accepted
    :param upgraded_gifts: True, if upgraded gifts and regular gifts that can be upgraded for free are accepted
    :param premium_subscription: True, if Telegram Premium subscription is accepted
    """
    __slots__ = ("unlimited_gifts", "limited_gifts", "upgraded_gifts", "premium_subscription", "_extra", "_client_id", "_type")

    def __init__(self, unlimited_gifts: bool = False, limited_gifts: bool = False, upgraded_gifts: bool = False, premium_subscription: bool = False):
        self.unlimited_gifts = unlimited_gifts
        self.limited_gifts = limited_gifts
        self.upgraded_gifts = upgraded_gifts
        self.premium_subscription = premium_subscription
        self._type = "acceptedGiftTypes"