from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AccountInfo(ObjectBase):
    """
    Contains basic information about another user that started a chat with the current user

    :param registration_month: Month when the user was registered in Telegram; 0-12; may be 0 if unknown
    :param registration_year: Year when the user was registered in Telegram; 0-9999; may be 0 if unknown
    :param phone_number_country_code: A two-letter ISO 3166-1 alpha-2 country code based on the phone number of the user; may be empty if unknown
    :param last_name_change_date: Point in time (Unix timestamp) when the user changed name last time; 0 if unknown
    :param last_photo_change_date: Point in time (Unix timestamp) when the user changed photo last time; 0 if unknown
    """
    __slots__ = ("registration_month", "registration_year", "phone_number_country_code", "last_name_change_date", "last_photo_change_date", "_extra", "_client_id", "_type")

    def __init__(self, registration_month: int = 0, registration_year: int = 0, phone_number_country_code: str = "", last_name_change_date: int = 0, last_photo_change_date: int = 0):
        self.registration_month = registration_month
        self.registration_year = registration_year
        self.phone_number_country_code = phone_number_country_code
        self.last_name_change_date = last_name_change_date
        self.last_photo_change_date = last_photo_change_date
        self._type = "accountInfo"