from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AddCustomServerLanguagePack(Function):
    """
    Adds a custom server language pack to the list of installed language packs in current localization target. Can be called before authorization

    :param language_pack_id: Identifier of a language pack to be added
    :return: :class:`Ok`
    """
    __slots__ = ("language_pack_id", "_extra", "_client_id", "_type")

    def __init__(self, language_pack_id = None):
        self.language_pack_id = language_pack_id
        self._type = "addCustomServerLanguagePack"