from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AddChatMember(Function):
    """
    Adds a new member to a chat; requires can_invite_users member right. Members can't be added to private or secret chats. Returns information about members that weren't added

    :param chat_id: Chat identifier
    :param user_id: Identifier of the user
    :param forward_limit: The number of earlier messages from the chat to be forwarded to the new member; up to 100. Ignored for supergroups and channels, or if the added user is a bot
    :return: :class:`FailedToAddMembers`
    """
    __slots__ = ("chat_id", "user_id", "forward_limit", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, user_id = None, forward_limit = None):
        self.chat_id = chat_id
        self.user_id = user_id
        self.forward_limit = forward_limit
        self._type = "addChatMember"