from .function import Function

from .proxy import Proxy
from .proxy_type import ProxyType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AddProxy(Function[Proxy]):
    """
    Adds a proxy server for network requests. Can be called before authorization

    :param server: Proxy server domain or IP address
    :param port: Proxy server port
    :param enable: Pass true to immediately enable the proxy
    :param type: Proxy type
    :return: :class:`Proxy`
    """
    __slots__ = ("server", "port", "enable", "type", "_extra", "_client_id", "_type")

    def __init__(self, server: str = "", port: int = 0, enable: bool = False, type: ProxyType | None = None):
        self.server = server
        self.port = port
        self.enable = enable
        self.type = type
        self._type = "addProxy"