from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AffiliateInfo(ObjectBase):
    """
    Contains information about an affiliate that received commission from a Telegram Star transaction

    :param commission_per_mille: The number of Telegram Stars received by the affiliate for each 1000 Telegram Stars received by the program owner
    :param affiliate_chat_id: Identifier of the chat which received the commission
    :param star_amount: The amount of Telegram Stars that were received by the affiliate; can be negative for refunds
    """
    __slots__ = ("commission_per_mille", "affiliate_chat_id", "star_amount", "_extra", "_client_id", "_type")

    def __init__(self, commission_per_mille = None, affiliate_chat_id = None, star_amount = None):
        self.commission_per_mille = commission_per_mille
        self.affiliate_chat_id = affiliate_chat_id
        self.star_amount = star_amount
        self._type = "affiliateInfo"