from .affiliate_type import AffiliateType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AffiliateTypeChannel(AffiliateType):
    """
    The affiliate is a channel chat where the current user has can_post_messages administrator right

    :param chat_id: Identifier of the channel chat
    """
    __slots__ = ("chat_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0):
        self.chat_id = chat_id
        self._type = "affiliateTypeChannel"