from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AllowBotToSendMessages(Function[Ok]):
    """
    Allows the specified bot to send messages to the user

    :param bot_user_id: Identifier of the target bot
    :return: :class:`Ok`
    """
    __slots__ = ("bot_user_id", "_extra", "_client_id", "_type")

    def __init__(self, bot_user_id: int = 0):
        self.bot_user_id = bot_user_id
        self._type = "allowBotToSendMessages"