from .file import File
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AnimatedChatPhoto(ObjectBase):
    """
    Animated variant of a chat photo in MPEG4 format

    :param length: Animation width and height
    :param file: Information about the animation file
    :param main_frame_timestamp: Timestamp of the frame, used as a static chat photo
    """
    __slots__ = ("length", "file", "main_frame_timestamp", "_extra", "_client_id", "_type")

    def __init__(self, length: int = 0, file: File | None = None, main_frame_timestamp: float = 0):
        self.length = length
        self.file = file
        self.main_frame_timestamp = main_frame_timestamp
        self._type = "animatedChatPhoto"