from .function import Function

from .input_inline_query_result import InputInlineQueryResult
from .sent_web_app_message import SentWebAppMessage

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AnswerWebAppQuery(Function[SentWebAppMessage]):
    """
    Sets the result of interaction with a Web App and sends corresponding message on behalf of the user to the chat from which the query originated; for bots only

    :param web_app_query_id: Identifier of the Web App query
    :param result: The result of the query
    :return: :class:`SentWebAppMessage`
    """
    __slots__ = ("web_app_query_id", "result", "_extra", "_client_id", "_type")

    def __init__(self, web_app_query_id: str = "", result: InputInlineQueryResult | None = None):
        self.web_app_query_id = web_app_query_id
        self.result = result
        self._type = "answerWebAppQuery"