from .function import Function

from .ok import Ok
from .store_payment_purpose import StorePaymentPurpose
from .store_transaction import StoreTransaction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AssignStoreTransaction(Function[Ok]):
    """
    Informs server about an in-store purchase. For official applications only

    :param transaction: Information about the transaction
    :param purpose: Transaction purpose
    :return: :class:`Ok`
    """
    __slots__ = ("transaction", "purpose", "_extra", "_client_id", "_type")

    def __init__(self, transaction: StoreTransaction | None = None, purpose: StorePaymentPurpose | None = None):
        self.transaction = transaction
        self.purpose = purpose
        self._type = "assignStoreTransaction"