from .authentication_code_type import AuthenticationCodeType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AuthenticationCodeTypeFirebaseIos(AuthenticationCodeType):
    """
    A digit-only authentication code is delivered via Firebase Authentication to the official iOS application

    :param receipt: Receipt of successful application token validation to compare with receipt from push notification
    :param push_timeout: Time after the next authentication method is expected to be used if verification push notification isn't received, in seconds
    :param length: Length of the code
    """
    __slots__ = ("receipt", "push_timeout", "length", "_extra", "_client_id", "_type")

    def __init__(self, receipt = None, push_timeout = None, length = None):
        self.receipt = receipt
        self.push_timeout = push_timeout
        self.length = length
        self._type = "authenticationCodeTypeFirebaseIos"