from .authorization_state import AuthorizationState

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AuthorizationStateWaitEmailAddress(AuthorizationState):
    """
    TDLib needs the user's email address to authorize. Call setAuthenticationEmailAddress to provide the email address, or directly call checkAuthenticationEmailCode with Apple ID/Google ID token if allowed

    :param allow_apple_id: True, if authorization through Apple ID is allowed
    :param allow_google_id: True, if authorization through Google ID is allowed
    """
    __slots__ = ("allow_apple_id", "allow_google_id", "_extra", "_client_id", "_type")

    def __init__(self, allow_apple_id: bool = False, allow_google_id: bool = False):
        self.allow_apple_id = allow_apple_id
        self.allow_google_id = allow_google_id
        self._type = "authorizationStateWaitEmailAddress"