from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class AvailableReaction(ObjectBase):
    """
    Represents an available reaction

    :param type: Type of the reaction
    :param needs_premium: True, if Telegram Premium is needed to send the reaction
    """
    __slots__ = ("type", "needs_premium", "_extra", "_client_id", "_type")

    def __init__(self, type = None, needs_premium = None):
        self.type = type
        self.needs_premium = needs_premium
        self._type = "availableReaction"