from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class Backgrounds(ObjectBase):
    """
    Contains a list of backgrounds

    :param backgrounds: A list of backgrounds
    """
    __slots__ = ("backgrounds", "_extra", "_client_id", "_type")

    def __init__(self, backgrounds = None):
        self.backgrounds = backgrounds
        self._type = "backgrounds"