from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BackgroundFill(ObjectBase):
    """
    Describes a fill of a background

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "BackgroundFill"