from .function import Function

from .ok import Ok
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BanGroupCallParticipants(Function[Ok]):
    """
    Bans users from a group call not bound to a chat; requires groupCall.is_owned. Only the owner of the group call can invite the banned users back

    :param group_call_id: Group call identifier
    :param user_ids: Identifiers of group call participants to ban; identifiers of unknown users from the update updateGroupCallParticipants can be also passed to the method
    :return: :class:`Ok`
    """
    __slots__ = ("group_call_id", "user_ids", "_extra", "_client_id", "_type")

    def __init__(self, group_call_id: int = 0, user_ids: List[int] | None = None):
        self.group_call_id = group_call_id
        self.user_ids = user_ids
        self._type = "banGroupCallParticipants"