from .bot_commands import BotCommands
from .chat_invite_link import ChatInviteLink
from .chat_member import ChatMember
from .chat_photo import ChatPhoto
from .object_base import ObjectBase
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BasicGroupFullInfo(ObjectBase):
    """
    Contains full information about a basic group

    :param photo: Chat photo; may be null if empty or unknown. If non-null, then it is the same photo as in chat.photo
    :param description: Contains full information about a basic group
    :param creator_user_id: User identifier of the creator of the group; 0 if unknown
    :param members: Group members
    :param can_hide_members: True, if non-administrators and non-bots can be hidden in responses to getSupergroupMembers and searchChatMembers for non-administrators after upgrading the basic group to a supergroup
    :param can_toggle_aggressive_anti_spam: True, if aggressive anti-spam checks can be enabled or disabled in the supergroup after upgrading the basic group to a supergroup
    :param invite_link: Primary invite link for this group; may be null. For chat administrators with can_invite_users right only. Updated only after the basic group is opened
    :param bot_commands: List of commands of bots in the group
    """
    __slots__ = ("photo", "description", "creator_user_id", "members", "can_hide_members", "can_toggle_aggressive_anti_spam", "invite_link", "bot_commands", "_extra", "_client_id", "_type")

    def __init__(self, photo: ChatPhoto | None = None, description: str = "", creator_user_id: int = 0, members: List[ChatMember] | None = None, can_hide_members: bool = False, can_toggle_aggressive_anti_spam: bool = False, invite_link: ChatInviteLink | None = None, bot_commands: List[BotCommands] | None = None):
        self.photo = photo
        self.description = description
        self.creator_user_id = creator_user_id
        self.members = members
        self.can_hide_members = can_hide_members
        self.can_toggle_aggressive_anti_spam = can_toggle_aggressive_anti_spam
        self.invite_link = invite_link
        self.bot_commands = bot_commands
        self._type = "basicGroupFullInfo"