from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class Birthdate(ObjectBase):
    """
    Represents a birthdate of a user

    :param day: Day of the month; 1-31
    :param month: Month of the year; 1-12
    :param year: Birth year; 0 if unknown
    """
    __slots__ = ("day", "month", "year", "_extra", "_client_id", "_type")

    def __init__(self, day = None, month = None, year = None):
        self.day = day
        self.month = month
        self.year = year
        self._type = "birthdate"