from .block_list import BlockList

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BlockListStories(BlockList):
    """
    The block list that disallows viewing of stories of the current user

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "blockListStories"