from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BotMediaPreviews(ObjectBase):
    """
    Contains a list of media previews of a bot

    :param previews: List of media previews
    """
    __slots__ = ("previews", "_extra", "_client_id", "_type")

    def __init__(self, previews = None):
        self.previews = previews
        self._type = "botMediaPreviews"