from .business_away_message_schedule import BusinessAwayMessageSchedule

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BusinessAwayMessageScheduleOutsideOfOpeningHours(BusinessAwayMessageSchedule):
    """
    Send away messages outside of the business opening hours

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "businessAwayMessageScheduleOutsideOfOpeningHours"