from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BusinessInfo(ObjectBase):
    """
    Contains information about a Telegram Business account

    :param location: Location of the business; may be null if none
    :param opening_hours: Opening hours of the business; may be null if none. The hours are guaranteed to be valid and has already been split by week days
    :param local_opening_hours: Opening hours of the business in the local time; may be null if none. The hours are guaranteed to be valid and has already been split by week days. Local time zone identifier will be empty. An updateUserFullInfo update is not triggered when value of this field changes
    :param next_open_in: Time left before the business will open the next time, in seconds; 0 if unknown. An updateUserFullInfo update is not triggered when value of this field changes
    :param next_close_in: Time left before the business will close the next time, in seconds; 0 if unknown. An updateUserFullInfo update is not triggered when value of this field changes
    :param greeting_message_settings: The greeting message; may be null if none or the Business account is not of the current user
    :param away_message_settings: The away message; may be null if none or the Business account is not of the current user
    :param start_page: Information about start page of the account; may be null if none
    """
    __slots__ = ("location", "opening_hours", "local_opening_hours", "next_open_in", "next_close_in", "greeting_message_settings", "away_message_settings", "start_page", "_extra", "_client_id", "_type")

    def __init__(self, location = None, opening_hours = None, local_opening_hours = None, next_open_in = None, next_close_in = None, greeting_message_settings = None, away_message_settings = None, start_page = None):
        self.location = location
        self.opening_hours = opening_hours
        self.local_opening_hours = local_opening_hours
        self.next_open_in = next_open_in
        self.next_close_in = next_close_in
        self.greeting_message_settings = greeting_message_settings
        self.away_message_settings = away_message_settings
        self.start_page = start_page
        self._type = "businessInfo"