from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BusinessRecipients(ObjectBase):
    """
    Describes private chats chosen for automatic interaction with a business

    :param chat_ids: Identifiers of selected private chats
    :param excluded_chat_ids: Identifiers of private chats that are always excluded; for businessConnectedBot only
    :param select_existing_chats: True, if all existing private chats are selected
    :param select_new_chats: True, if all new private chats are selected
    :param select_contacts: True, if all private chats with contacts are selected
    :param select_non_contacts: True, if all private chats with non-contacts are selected
    :param exclude_selected: If true, then all private chats except the selected are chosen. Otherwise, only the selected chats are chosen
    """
    __slots__ = ("chat_ids", "excluded_chat_ids", "select_existing_chats", "select_new_chats", "select_contacts", "select_non_contacts", "exclude_selected", "_extra", "_client_id", "_type")

    def __init__(self, chat_ids = None, excluded_chat_ids = None, select_existing_chats = None, select_new_chats = None, select_contacts = None, select_non_contacts = None, exclude_selected = None):
        self.chat_ids = chat_ids
        self.excluded_chat_ids = excluded_chat_ids
        self.select_existing_chats = select_existing_chats
        self.select_new_chats = select_new_chats
        self.select_contacts = select_contacts
        self.select_non_contacts = select_non_contacts
        self.exclude_selected = exclude_selected
        self._type = "businessRecipients"