from .business_feature import BusinessFeature

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BusinessFeatureUpgradedStories(BusinessFeature):
    """
    Allowed to use many additional features for stories

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "businessFeatureUpgradedStories"