from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BusinessBotManageBar(ObjectBase):
    """
    Contains information about a business bot that manages the chat

    :param bot_user_id: User identifier of the bot
    :param manage_url: URL to be opened to manage the bot
    :param is_bot_paused: True, if the bot is paused. Use toggleBusinessConnectedBotChatIsPaused to change the value of the field
    :param can_bot_reply: True, if the bot can reply
    """
    __slots__ = ("bot_user_id", "manage_url", "is_bot_paused", "can_bot_reply", "_extra", "_client_id", "_type")

    def __init__(self, bot_user_id: int = 0, manage_url: str = "", is_bot_paused: bool = False, can_bot_reply: bool = False):
        self.bot_user_id = bot_user_id
        self.manage_url = manage_url
        self.is_bot_paused = is_bot_paused
        self.can_bot_reply = can_bot_reply
        self._type = "businessBotManageBar"