from .business_opening_hours_interval import BusinessOpeningHoursInterval
from .object_base import ObjectBase
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BusinessOpeningHours(ObjectBase):
    """
    Describes opening hours of a business

    :param time_zone_id: Unique time zone identifier
    :param opening_hours: Intervals of the time when the business is open
    """
    __slots__ = ("time_zone_id", "opening_hours", "_extra", "_client_id", "_type")

    def __init__(self, time_zone_id: str = "", opening_hours: List[BusinessOpeningHoursInterval] | None = None):
        self.time_zone_id = time_zone_id
        self.opening_hours = opening_hours
        self._type = "businessOpeningHours"