from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BusinessAwayMessageSchedule(ObjectBase):
    """
    Describes conditions for sending of away messages by a Telegram Business account

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "BusinessAwayMessageSchedule"