from .business_away_message_schedule import BusinessAwayMessageSchedule

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class BusinessAwayMessageScheduleAlways(BusinessAwayMessageSchedule):
    """
    Send away messages always

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "businessAwayMessageScheduleAlways"