from .call_server_type import CallServerType
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CallServer(ObjectBase):
    """
    Describes a server for relaying call data

    :param id: Server identifier
    :param ip_address: Server IPv4 address
    :param ipv6_address: Server IPv6 address
    :param port: Server port number
    :param type: Server type
    """
    __slots__ = ("id", "ip_address", "ipv6_address", "port", "type", "_extra", "_client_id", "_type")

    def __init__(self, id: int = 0, ip_address: str = "", ipv6_address: str = "", port: int = 0, type: CallServerType | None = None):
        self.id = id
        self.ip_address = ip_address
        self.ipv6_address = ipv6_address
        self.port = port
        self.type = type
        self._type = "callServer"