from .call_problem import CallProblem

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CallProblemDistortedSpeech(CallProblem):
    """
    The speech was distorted

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "callProblemDistortedSpeech"