from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CallId(ObjectBase):
    """
    Contains the call identifier

    :param id: Call identifier
    """
    __slots__ = ("id", "_extra", "_client_id", "_type")

    def __init__(self, id = None):
        self.id = id
        self._type = "callId"