from .call_server_type import CallServerType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CallServerTypeWebrtc(CallServerType):
    """
    A WebRTC server

    :param username: Username to be used for authentication
    :param password: Authentication password
    :param supports_turn: True, if the server supports TURN
    :param supports_stun: True, if the server supports STUN
    """
    __slots__ = ("username", "password", "supports_turn", "supports_stun", "_extra", "_client_id", "_type")

    def __init__(self, username = None, password = None, supports_turn = None, supports_stun = None):
        self.username = username
        self.password = password
        self.supports_turn = supports_turn
        self.supports_stun = supports_stun
        self._type = "callServerTypeWebrtc"