from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CanTransferOwnership(Function):
    """
    Checks whether the current session can be used to transfer a chat ownership to another user

    :return: :class:`CanTransferOwnershipResultOk | CanTransferOwnershipResultPasswordNeeded | CanTransferOwnershipResultPasswordTooFresh | CanTransferOwnershipResultSessionTooFresh`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "canTransferOwnership"