from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChangeStickerSet(Function[Ok]):
    """
    Installs/uninstalls or activates/archives a sticker set

    :param set_id: Identifier of the sticker set
    :param is_installed: The new value of is_installed
    :param is_archived: The new value of is_archived. A sticker set can't be installed and archived simultaneously
    :return: :class:`Ok`
    """
    __slots__ = ("set_id", "is_installed", "is_archived", "_extra", "_client_id", "_type")

    def __init__(self, set_id: int = 0, is_installed: bool = False, is_archived: bool = False):
        self.set_id = set_id
        self.is_installed = is_installed
        self.is_archived = is_archived
        self._type = "changeStickerSet"