from .chat_event_action import ChatEventAction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventSlowModeDelayChanged(ChatEventAction):
    """
    The slow_mode_delay setting of a supergroup was changed

    :param old_slow_mode_delay: Previous value of slow_mode_delay, in seconds
    :param new_slow_mode_delay: New value of slow_mode_delay, in seconds
    """
    __slots__ = ("old_slow_mode_delay", "new_slow_mode_delay", "_extra", "_client_id", "_type")

    def __init__(self, old_slow_mode_delay = None, new_slow_mode_delay = None):
        self.old_slow_mode_delay = old_slow_mode_delay
        self.new_slow_mode_delay = new_slow_mode_delay
        self._type = "chatEventSlowModeDelayChanged"