from .chat_event_action import ChatEventAction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventUsernameChanged(ChatEventAction):
    """
    The chat editable username was changed

    :param old_username: Previous chat username
    :param new_username: New chat username
    """
    __slots__ = ("old_username", "new_username", "_extra", "_client_id", "_type")

    def __init__(self, old_username: str = "", new_username: str = ""):
        self.old_username = old_username
        self.new_username = new_username
        self._type = "chatEventUsernameChanged"