from .chat_statistics import ChatStatistics

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatStatisticsChannel(ChatStatistics):
    """
    A detailed statistics about a channel chat

    :param period: A period to which the statistics applies
    :param member_count: Number of members in the chat
    :param mean_message_view_count: Mean number of times the recently sent messages were viewed
    :param mean_message_share_count: Mean number of times the recently sent messages were shared
    :param mean_message_reaction_count: Mean number of times reactions were added to the recently sent messages
    :param mean_story_view_count: Mean number of times the recently posted stories were viewed
    :param mean_story_share_count: Mean number of times the recently posted stories were shared
    :param mean_story_reaction_count: Mean number of times reactions were added to the recently posted stories
    :param enabled_notifications_percentage: A percentage of users with enabled notifications for the chat; 0-100
    :param member_count_graph: A graph containing number of members in the chat
    :param join_graph: A graph containing number of members joined and left the chat
    :param mute_graph: A graph containing number of members muted and unmuted the chat
    :param view_count_by_hour_graph: A graph containing number of message views in a given hour in the last two weeks
    :param view_count_by_source_graph: A graph containing number of message views per source
    :param join_by_source_graph: A graph containing number of new member joins per source
    :param language_graph: A graph containing number of users viewed chat messages per language
    :param message_interaction_graph: A graph containing number of chat message views and shares
    :param message_reaction_graph: A graph containing number of reactions on messages
    :param story_interaction_graph: A graph containing number of story views and shares
    :param story_reaction_graph: A graph containing number of reactions on stories
    :param instant_view_interaction_graph: A graph containing number of views of associated with the chat instant views
    :param recent_interactions: Detailed statistics about number of views and shares of recently sent messages and posted stories
    """
    __slots__ = ("period", "member_count", "mean_message_view_count", "mean_message_share_count", "mean_message_reaction_count", "mean_story_view_count", "mean_story_share_count", "mean_story_reaction_count", "enabled_notifications_percentage", "member_count_graph", "join_graph", "mute_graph", "view_count_by_hour_graph", "view_count_by_source_graph", "join_by_source_graph", "language_graph", "message_interaction_graph", "message_reaction_graph", "story_interaction_graph", "story_reaction_graph", "instant_view_interaction_graph", "recent_interactions", "_extra", "_client_id", "_type")

    def __init__(self, period = None, member_count = None, mean_message_view_count = None, mean_message_share_count = None, mean_message_reaction_count = None, mean_story_view_count = None, mean_story_share_count = None, mean_story_reaction_count = None, enabled_notifications_percentage = None, member_count_graph = None, join_graph = None, mute_graph = None, view_count_by_hour_graph = None, view_count_by_source_graph = None, join_by_source_graph = None, language_graph = None, message_interaction_graph = None, message_reaction_graph = None, story_interaction_graph = None, story_reaction_graph = None, instant_view_interaction_graph = None, recent_interactions = None):
        self.period = period
        self.member_count = member_count
        self.mean_message_view_count = mean_message_view_count
        self.mean_message_share_count = mean_message_share_count
        self.mean_message_reaction_count = mean_message_reaction_count
        self.mean_story_view_count = mean_story_view_count
        self.mean_story_share_count = mean_story_share_count
        self.mean_story_reaction_count = mean_story_reaction_count
        self.enabled_notifications_percentage = enabled_notifications_percentage
        self.member_count_graph = member_count_graph
        self.join_graph = join_graph
        self.mute_graph = mute_graph
        self.view_count_by_hour_graph = view_count_by_hour_graph
        self.view_count_by_source_graph = view_count_by_source_graph
        self.join_by_source_graph = join_by_source_graph
        self.language_graph = language_graph
        self.message_interaction_graph = message_interaction_graph
        self.message_reaction_graph = message_reaction_graph
        self.story_interaction_graph = story_interaction_graph
        self.story_reaction_graph = story_reaction_graph
        self.instant_view_interaction_graph = instant_view_interaction_graph
        self.recent_interactions = recent_interactions
        self._type = "chatStatisticsChannel"