from .chat_members_filter import ChatMembersFilter

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatMembersFilterRestricted(ChatMembersFilter):
    """
    Returns users under certain restrictions in the chat; can be used only by administrators in a supergroup

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "chatMembersFilterRestricted"