from .chat_background import ChatBackground
from .chat_event_action import ChatEventAction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventBackgroundChanged(ChatEventAction):
    """
    The chat background was changed

    :param old_background: Previous background; may be null if none
    :param new_background: New background; may be null if none
    """
    __slots__ = ("old_background", "new_background", "_extra", "_client_id", "_type")

    def __init__(self, old_background: ChatBackground | None = None, new_background: ChatBackground | None = None):
        self.old_background = old_background
        self.new_background = new_background
        self._type = "chatEventBackgroundChanged"