from .chat_member_status import ChatMemberStatus

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatMemberStatusCreator(ChatMemberStatus):
    """
    The user is the owner of the chat and has all the administrator privileges

    :param custom_title: A custom title of the owner; 0-16 characters without emoji; applicable to supergroups only
    :param is_anonymous: True, if the creator isn't shown in the chat member list and sends messages anonymously; applicable to supergroups only
    :param is_member: True, if the user is a member of the chat
    """
    __slots__ = ("custom_title", "is_anonymous", "is_member", "_extra", "_client_id", "_type")

    def __init__(self, custom_title: str = "", is_anonymous: bool = False, is_member: bool = False):
        self.custom_title = custom_title
        self.is_anonymous = is_anonymous
        self.is_member = is_member
        self._type = "chatMemberStatusCreator"