from .chat_event_action import ChatEventAction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventForumTopicDeleted(ChatEventAction):
    """
    A forum topic was deleted

    :param topic_info: Information about the topic
    """
    __slots__ = ("topic_info", "_extra", "_client_id", "_type")

    def __init__(self, topic_info = None):
        self.topic_info = topic_info
        self._type = "chatEventForumTopicDeleted"