from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatInviteLinkMembers(ObjectBase):
    """
    Contains a list of chat members joined a chat via an invite link

    :param total_count: Approximate total number of chat members found
    :param members: List of chat members, joined a chat via an invite link
    """
    __slots__ = ("total_count", "members", "_extra", "_client_id", "_type")

    def __init__(self, total_count = None, members = None):
        self.total_count = total_count
        self.members = members
        self._type = "chatInviteLinkMembers"