from .chat_member_status import ChatMemberStatus

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatMemberStatusAdministrator(ChatMemberStatus):
    """
    The user is a member of the chat and has some additional privileges. In basic groups, administrators can edit and delete messages sent by others, add new members, ban unprivileged members, and manage video chats. In supergroups and channels, there are more detailed options for administrator privileges

    :param custom_title: A custom title of the administrator; 0-16 characters without emoji; applicable to supergroups only
    :param can_be_edited: True, if the current user can edit the administrator privileges for the called user
    :param rights: Rights of the administrator
    """
    __slots__ = ("custom_title", "can_be_edited", "rights", "_extra", "_client_id", "_type")

    def __init__(self, custom_title = None, can_be_edited = None, rights = None):
        self.custom_title = custom_title
        self.can_be_edited = can_be_edited
        self.rights = rights
        self._type = "chatMemberStatusAdministrator"