from .chat_event_action import ChatEventAction
from .forum_topic_info import ForumTopicInfo

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventForumTopicPinned(ChatEventAction):
    """
    A pinned forum topic was changed

    :param old_topic_info: Information about the old pinned topic; may be null
    :param new_topic_info: Information about the new pinned topic; may be null
    """
    __slots__ = ("old_topic_info", "new_topic_info", "_extra", "_client_id", "_type")

    def __init__(self, old_topic_info: ForumTopicInfo | None = None, new_topic_info: ForumTopicInfo | None = None):
        self.old_topic_info = old_topic_info
        self.new_topic_info = new_topic_info
        self._type = "chatEventForumTopicPinned"