from .chat_action import ChatAction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatActionUploadingVideoNote(ChatAction):
    """
    The user is uploading a video note

    :param progress: Upload progress, as a percentage
    """
    __slots__ = ("progress", "_extra", "_client_id", "_type")

    def __init__(self, progress = None):
        self.progress = progress
        self._type = "chatActionUploadingVideoNote"