from .chat_folder_invite_link import ChatFolderInviteLink
from .object_base import ObjectBase
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatFolderInviteLinks(ObjectBase):
    """
    Represents a list of chat folder invite links

    :param invite_links: List of the invite links
    """
    __slots__ = ("invite_links", "_extra", "_client_id", "_type")

    def __init__(self, invite_links: List[ChatFolderInviteLink] | None = None):
        self.invite_links = invite_links
        self._type = "chatFolderInviteLinks"