from .chat_event_action import ChatEventAction
from .chat_permissions import ChatPermissions

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventPermissionsChanged(ChatEventAction):
    """
    The chat permissions were changed

    :param old_permissions: Previous chat permissions
    :param new_permissions: New chat permissions
    """
    __slots__ = ("old_permissions", "new_permissions", "_extra", "_client_id", "_type")

    def __init__(self, old_permissions: ChatPermissions | None = None, new_permissions: ChatPermissions | None = None):
        self.old_permissions = old_permissions
        self.new_permissions = new_permissions
        self._type = "chatEventPermissionsChanged"