from .chat_revenue_transaction_type import ChatRevenueTransactionType
from .revenue_withdrawal_state import RevenueWithdrawalState

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatRevenueTransactionTypeWithdrawal(ChatRevenueTransactionType):
    """
    Describes a withdrawal of earnings

    :param withdrawal_date: Point in time (Unix timestamp) when the earnings withdrawal started
    :param provider: Name of the payment provider
    :param state: State of the withdrawal
    """
    __slots__ = ("withdrawal_date", "provider", "state", "_extra", "_client_id", "_type")

    def __init__(self, withdrawal_date: int = 0, provider: str = "", state: RevenueWithdrawalState | None = None):
        self.withdrawal_date = withdrawal_date
        self.provider = provider
        self.state = state
        self._type = "chatRevenueTransactionTypeWithdrawal"