from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatInviteLink(ObjectBase):
    """
    Contains a chat invite link

    :param invite_link: Chat invite link
    :param name: Name of the link
    :param creator_user_id: User identifier of an administrator created the link
    :param date: Point in time (Unix timestamp) when the link was created
    :param edit_date: Point in time (Unix timestamp) when the link was last edited; 0 if never or unknown
    :param expiration_date: Point in time (Unix timestamp) when the link will expire; 0 if never
    :param subscription_pricing: Information about subscription plan that is applied to the users joining the chat by the link; may be null if the link doesn't require subscription
    :param member_limit: The maximum number of members, which can join the chat using the link simultaneously; 0 if not limited. Always 0 if the link requires approval
    :param member_count: Number of chat members, which joined the chat using the link
    :param expired_member_count: Number of chat members, which joined the chat using the link, but have already left because of expired subscription; for subscription links only
    :param pending_join_request_count: Number of pending join requests created using this link
    :param creates_join_request: True, if the link only creates join request. If true, total number of joining members will be unlimited
    :param is_primary: True, if the link is primary. Primary invite link can't have name, expiration date, or usage limit. There is exactly one primary invite link for each administrator with can_invite_users right at a given time
    :param is_revoked: True, if the link was revoked
    """
    __slots__ = ("invite_link", "name", "creator_user_id", "date", "edit_date", "expiration_date", "subscription_pricing", "member_limit", "member_count", "expired_member_count", "pending_join_request_count", "creates_join_request", "is_primary", "is_revoked", "_extra", "_client_id", "_type")

    def __init__(self, invite_link = None, name = None, creator_user_id = None, date = None, edit_date = None, expiration_date = None, subscription_pricing = None, member_limit = None, member_count = None, expired_member_count = None, pending_join_request_count = None, creates_join_request = None, is_primary = None, is_revoked = None):
        self.invite_link = invite_link
        self.name = name
        self.creator_user_id = creator_user_id
        self.date = date
        self.edit_date = edit_date
        self.expiration_date = expiration_date
        self.subscription_pricing = subscription_pricing
        self.member_limit = member_limit
        self.member_count = member_count
        self.expired_member_count = expired_member_count
        self.pending_join_request_count = pending_join_request_count
        self.creates_join_request = creates_join_request
        self.is_primary = is_primary
        self.is_revoked = is_revoked
        self._type = "chatInviteLink"