from .chat_event_action import ChatEventAction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventAccentColorChanged(ChatEventAction):
    """
    The chat accent color or background custom emoji were changed

    :param old_accent_color_id: Previous identifier of chat accent color
    :param old_background_custom_emoji_id: Previous identifier of the custom emoji; 0 if none
    :param new_accent_color_id: New identifier of chat accent color
    :param new_background_custom_emoji_id: New identifier of the custom emoji; 0 if none
    """
    __slots__ = ("old_accent_color_id", "old_background_custom_emoji_id", "new_accent_color_id", "new_background_custom_emoji_id", "_extra", "_client_id", "_type")

    def __init__(self, old_accent_color_id = None, old_background_custom_emoji_id = None, new_accent_color_id = None, new_background_custom_emoji_id = None):
        self.old_accent_color_id = old_accent_color_id
        self.old_background_custom_emoji_id = old_background_custom_emoji_id
        self.new_accent_color_id = new_accent_color_id
        self.new_background_custom_emoji_id = new_background_custom_emoji_id
        self._type = "chatEventAccentColorChanged"