from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEvent(ObjectBase):
    """
    Represents a chat event

    :param id: Chat event identifier
    :param date: Point in time (Unix timestamp) when the event happened
    :param member_id: Identifier of the user or chat who performed the action
    :param action: The action
    """
    __slots__ = ("id", "date", "member_id", "action", "_extra", "_client_id", "_type")

    def __init__(self, id = None, date = None, member_id = None, action = None):
        self.id = id
        self.date = date
        self.member_id = member_id
        self.action = action
        self._type = "chatEvent"