from .chat_message_sender import ChatMessageSender
from .object_base import ObjectBase
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatMessageSenders(ObjectBase):
    """
    Represents a list of message senders, which can be used to send messages in a chat

    :param senders: List of available message senders
    """
    __slots__ = ("senders", "_extra", "_client_id", "_type")

    def __init__(self, senders: List[ChatMessageSender] | None = None):
        self.senders = senders
        self._type = "chatMessageSenders"