from .chat_invite_link_count import ChatInviteLinkCount
from .object_base import ObjectBase
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatInviteLinkCounts(ObjectBase):
    """
    Contains a list of chat invite link counts

    :param invite_link_counts: List of invite link counts
    """
    __slots__ = ("invite_link_counts", "_extra", "_client_id", "_type")

    def __init__(self, invite_link_counts: List[ChatInviteLinkCount] | None = None):
        self.invite_link_counts = invite_link_counts
        self._type = "chatInviteLinkCounts"