from .chat_event_action import ChatEventAction
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventActiveUsernamesChanged(ChatEventAction):
    """
    The chat active usernames were changed

    :param old_usernames: Previous list of active usernames
    :param new_usernames: New list of active usernames
    """
    __slots__ = ("old_usernames", "new_usernames", "_extra", "_client_id", "_type")

    def __init__(self, old_usernames: List[str] | None = None, new_usernames: List[str] | None = None):
        self.old_usernames = old_usernames
        self.new_usernames = new_usernames
        self._type = "chatEventActiveUsernamesChanged"