from .object_base import ObjectBase
from .star_subscription_pricing import StarSubscriptionPricing

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatInviteLinkSubscriptionInfo(ObjectBase):
    """
    Contains information about subscription plan that must be paid by the user to use a chat invite link

    :param pricing: Information about subscription plan that must be paid by the user to use the link
    :param can_reuse: True, if the user has already paid for the subscription and can use joinChatByInviteLink to join the subscribed chat again
    :param form_id: Identifier of the payment form to use for subscription payment; 0 if the subscription can't be paid
    """
    __slots__ = ("pricing", "can_reuse", "form_id", "_extra", "_client_id", "_type")

    def __init__(self, pricing: StarSubscriptionPricing | None = None, can_reuse: bool = False, form_id: int = 0):
        self.pricing = pricing
        self.can_reuse = can_reuse
        self.form_id = form_id
        self._type = "chatInviteLinkSubscriptionInfo"