from .chat_list import ChatList
from .chat_source import ChatSource
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatPosition(ObjectBase):
    """
    Describes a position of a chat in a chat list

    :param list: The chat list
    :param order: A parameter used to determine order of the chat in the chat list. Chats must be sorted by the pair (order, chat.id) in descending order
    :param is_pinned: True, if the chat is pinned in the chat list
    :param source: Source of the chat in the chat list; may be null
    """
    __slots__ = ("list", "order", "is_pinned", "source", "_extra", "_client_id", "_type")

    def __init__(self, list: ChatList | None = None, order: int = 0, is_pinned: bool = False, source: ChatSource | None = None):
        self.list = list
        self.order = order
        self.is_pinned = is_pinned
        self.source = source
        self._type = "chatPosition"