from .chat_event_action import ChatEventAction
from .chat_invite_link import ChatInviteLink

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventInviteLinkRevoked(ChatEventAction):
    """
    A chat invite link was revoked

    :param invite_link: The invite link
    """
    __slots__ = ("invite_link", "_extra", "_client_id", "_type")

    def __init__(self, invite_link: ChatInviteLink | None = None):
        self.invite_link = invite_link
        self._type = "chatEventInviteLinkRevoked"