from .chat_type import ChatType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatTypeSecret(ChatType):
    """
    A secret chat with a user

    :param secret_chat_id: Secret chat identifier
    :param user_id: User identifier of the other user in the secret chat
    """
    __slots__ = ("secret_chat_id", "user_id", "_extra", "_client_id", "_type")

    def __init__(self, secret_chat_id = None, user_id = None):
        self.secret_chat_id = secret_chat_id
        self.user_id = user_id
        self._type = "chatTypeSecret"