from .chat_source import ChatSource

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatSourceMtprotoProxy(ChatSource):
    """
    The chat is sponsored by the user's MTProxy server

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "chatSourceMtprotoProxy"