from .chat_list import ChatList

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatListMain(ChatList):
    """
    A main list of chats

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "chatListMain"