from .chat_event_action import ChatEventAction
from .message_sender import MessageSender

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventVideoChatParticipantIsMutedToggled(ChatEventAction):
    """
    A video chat participant was muted or unmuted

    :param participant_id: Identifier of the affected group call participant
    :param is_muted: New value of is_muted
    """
    __slots__ = ("participant_id", "is_muted", "_extra", "_client_id", "_type")

    def __init__(self, participant_id: MessageSender | None = None, is_muted: bool = False):
        self.participant_id = participant_id
        self.is_muted = is_muted
        self._type = "chatEventVideoChatParticipantIsMutedToggled"