from .chat_member_status import ChatMemberStatus

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatMemberStatusMember(ChatMemberStatus):
    """
    The user is a member of the chat, without any additional privileges or restrictions

    :param member_until_date: Point in time (Unix timestamp) when the user will be removed from the chat because of the expired subscription; 0 if never. Ignored in setChatMemberStatus
    """
    __slots__ = ("member_until_date", "_extra", "_client_id", "_type")

    def __init__(self, member_until_date = None):
        self.member_until_date = member_until_date
        self._type = "chatMemberStatusMember"