from .chat_event_action import ChatEventAction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventMemberJoinedByRequest(ChatEventAction):
    """
    A new member was accepted to the chat by an administrator

    :param approver_user_id: User identifier of the chat administrator, approved user join request
    :param invite_link: Invite link used to join the chat; may be null
    """
    __slots__ = ("approver_user_id", "invite_link", "_extra", "_client_id", "_type")

    def __init__(self, approver_user_id = None, invite_link = None):
        self.approver_user_id = approver_user_id
        self.invite_link = invite_link
        self._type = "chatEventMemberJoinedByRequest"