from .chat_event_action import ChatEventAction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventInviteLinkEdited(ChatEventAction):
    """
    A chat invite link was edited

    :param old_invite_link: Previous information about the invite link
    :param new_invite_link: New information about the invite link
    """
    __slots__ = ("old_invite_link", "new_invite_link", "_extra", "_client_id", "_type")

    def __init__(self, old_invite_link = None, new_invite_link = None):
        self.old_invite_link = old_invite_link
        self.new_invite_link = new_invite_link
        self._type = "chatEventInviteLinkEdited"