from .chat_revenue_amount import ChatRevenueAmount
from .object_base import ObjectBase
from .statistical_graph import StatisticalGraph

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatRevenueStatistics(ObjectBase):
    """
    A detailed statistics about revenue earned from sponsored messages in a chat

    :param revenue_by_hour_graph: A graph containing amount of revenue in a given hour
    :param revenue_graph: A graph containing amount of revenue
    :param revenue_amount: Amount of earned revenue
    :param usd_rate: Current conversion rate of the cryptocurrency in which revenue is calculated to USD
    """
    __slots__ = ("revenue_by_hour_graph", "revenue_graph", "revenue_amount", "usd_rate", "_extra", "_client_id", "_type")

    def __init__(self, revenue_by_hour_graph: StatisticalGraph | None = None, revenue_graph: StatisticalGraph | None = None, revenue_amount: ChatRevenueAmount | None = None, usd_rate: float = 0):
        self.revenue_by_hour_graph = revenue_by_hour_graph
        self.revenue_graph = revenue_graph
        self.revenue_amount = revenue_amount
        self.usd_rate = usd_rate
        self._type = "chatRevenueStatistics"