from .chat_boost_source import ChatBoostSource
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatBoost(ObjectBase):
    """
    Describes a boost applied to a chat

    :param id: Unique identifier of the boost
    :param count: The number of identical boosts applied
    :param source: Source of the boost
    :param start_date: Point in time (Unix timestamp) when the chat was boosted
    :param expiration_date: Point in time (Unix timestamp) when the boost will expire
    """
    __slots__ = ("id", "count", "source", "start_date", "expiration_date", "_extra", "_client_id", "_type")

    def __init__(self, id: str = "", count: int = 0, source: ChatBoostSource | None = None, start_date: int = 0, expiration_date: int = 0):
        self.id = id
        self.count = count
        self.source = source
        self.start_date = start_date
        self.expiration_date = expiration_date
        self._type = "chatBoost"