from .chat_photo_sticker_type import ChatPhotoStickerType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatPhotoStickerTypeRegularOrMask(ChatPhotoStickerType):
    """
    Information about the sticker, which was used to create the chat photo

    :param sticker_set_id: Sticker set identifier
    :param sticker_id: Identifier of the sticker in the set
    """
    __slots__ = ("sticker_set_id", "sticker_id", "_extra", "_client_id", "_type")

    def __init__(self, sticker_set_id = None, sticker_id = None):
        self.sticker_set_id = sticker_set_id
        self.sticker_id = sticker_id
        self._type = "chatPhotoStickerTypeRegularOrMask"