from .chat_event_action import ChatEventAction
from .message import Message

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventPollStopped(ChatEventAction):
    """
    A poll in a message was stopped

    :param message: The message with the poll
    """
    __slots__ = ("message", "_extra", "_client_id", "_type")

    def __init__(self, message: Message | None = None):
        self.message = message
        self._type = "chatEventPollStopped"