from .chat_event_action import ChatEventAction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventInvitesToggled(ChatEventAction):
    """
    The can_invite_users permission of a supergroup chat was toggled

    :param can_invite_users: New value of can_invite_users permission
    """
    __slots__ = ("can_invite_users", "_extra", "_client_id", "_type")

    def __init__(self, can_invite_users = None):
        self.can_invite_users = can_invite_users
        self._type = "chatEventInvitesToggled"