from .chat_boost_source import ChatBoostSource

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatBoostSourceGiveaway(ChatBoostSource):
    """
    The chat created a giveaway

    :param user_id: Identifier of a user that won in the giveaway; 0 if none
    :param gift_code: The created Telegram Premium gift code if it was used by the user or can be claimed by the current user; an empty string otherwise; for Telegram Premium giveways only
    :param star_count: Number of Telegram Stars distributed among winners of the giveaway
    :param giveaway_message_id: Identifier of the corresponding giveaway message; can be an identifier of a deleted message
    :param is_unclaimed: True, if the winner for the corresponding giveaway prize wasn't chosen, because there were not enough participants
    """
    __slots__ = ("user_id", "gift_code", "star_count", "giveaway_message_id", "is_unclaimed", "_extra", "_client_id", "_type")

    def __init__(self, user_id = None, gift_code = None, star_count = None, giveaway_message_id = None, is_unclaimed = None):
        self.user_id = user_id
        self.gift_code = gift_code
        self.star_count = star_count
        self.giveaway_message_id = giveaway_message_id
        self.is_unclaimed = is_unclaimed
        self._type = "chatBoostSourceGiveaway"