from .chat_event_action import ChatEventAction
from .chat_location import ChatLocation

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventLocationChanged(ChatEventAction):
    """
    The supergroup location was changed

    :param old_location: Previous location; may be null
    :param new_location: New location; may be null
    """
    __slots__ = ("old_location", "new_location", "_extra", "_client_id", "_type")

    def __init__(self, old_location: ChatLocation | None = None, new_location: ChatLocation | None = None):
        self.old_location = old_location
        self.new_location = new_location
        self._type = "chatEventLocationChanged"