from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatRevenueTransactionType(ObjectBase):
    """
    Describes type of transaction for revenue earned from sponsored messages in a chat

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "ChatRevenueTransactionType"