from .chat_statistics_object_type import ChatStatisticsObjectType
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatStatisticsInteractionInfo(ObjectBase):
    """
    Contains statistics about interactions with a message sent in the chat or a story posted on behalf of the chat

    :param object_type: Type of the object
    :param view_count: Number of times the object was viewed
    :param forward_count: Number of times the object was forwarded
    :param reaction_count: Number of times reactions were added to the object
    """
    __slots__ = ("object_type", "view_count", "forward_count", "reaction_count", "_extra", "_client_id", "_type")

    def __init__(self, object_type: ChatStatisticsObjectType | None = None, view_count: int = 0, forward_count: int = 0, reaction_count: int = 0):
        self.object_type = object_type
        self.view_count = view_count
        self.forward_count = forward_count
        self.reaction_count = reaction_count
        self._type = "chatStatisticsInteractionInfo"