from .object_base import ObjectBase
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatJoinRequestsInfo(ObjectBase):
    """
    Contains information about pending join requests for a chat

    :param total_count: Total number of pending join requests
    :param user_ids: Identifiers of at most 3 users sent the newest pending join requests
    """
    __slots__ = ("total_count", "user_ids", "_extra", "_client_id", "_type")

    def __init__(self, total_count: int = 0, user_ids: List[int] | None = None):
        self.total_count = total_count
        self.user_ids = user_ids
        self._type = "chatJoinRequestsInfo"