from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatInviteLinkMember(ObjectBase):
    """
    Describes a chat member joined a chat via an invite link

    :param user_id: User identifier
    :param joined_chat_date: Point in time (Unix timestamp) when the user joined the chat
    :param via_chat_folder_invite_link: True, if the user has joined the chat using an invite link for a chat folder
    :param approver_user_id: User identifier of the chat administrator, approved user join request
    """
    __slots__ = ("user_id", "joined_chat_date", "via_chat_folder_invite_link", "approver_user_id", "_extra", "_client_id", "_type")

    def __init__(self, user_id = None, joined_chat_date = None, via_chat_folder_invite_link = None, approver_user_id = None):
        self.user_id = user_id
        self.joined_chat_date = joined_chat_date
        self.via_chat_folder_invite_link = via_chat_folder_invite_link
        self.approver_user_id = approver_user_id
        self._type = "chatInviteLinkMember"