from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatEventAction(ObjectBase):
    """
    Represents a chat event

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "ChatEventAction"