from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatNotificationSettings(ObjectBase):
    """
    Contains information about notification settings for a chat or a forum topic

    :param use_default_mute_for: If true, the value for the relevant type of chat or the forum chat is used instead of mute_for
    :param mute_for: Time left before notifications will be unmuted, in seconds
    :param use_default_sound: If true, the value for the relevant type of chat or the forum chat is used instead of sound_id
    :param sound_id: Identifier of the notification sound to be played for messages; 0 if sound is disabled
    :param use_default_show_preview: If true, the value for the relevant type of chat or the forum chat is used instead of show_preview
    :param show_preview: True, if message content must be displayed in notifications
    :param use_default_mute_stories: If true, the value for the relevant type of chat is used instead of mute_stories
    :param mute_stories: True, if story notifications are disabled for the chat
    :param use_default_story_sound: If true, the value for the relevant type of chat is used instead of story_sound_id
    :param story_sound_id: Identifier of the notification sound to be played for stories; 0 if sound is disabled
    :param use_default_show_story_poster: If true, the value for the relevant type of chat is used instead of show_story_poster
    :param show_story_poster: True, if the chat that posted a story must be displayed in notifications
    :param use_default_disable_pinned_message_notifications: If true, the value for the relevant type of chat or the forum chat is used instead of disable_pinned_message_notifications
    :param disable_pinned_message_notifications: If true, notifications for incoming pinned messages will be created as for an ordinary unread message
    :param use_default_disable_mention_notifications: If true, the value for the relevant type of chat or the forum chat is used instead of disable_mention_notifications
    :param disable_mention_notifications: If true, notifications for messages with mentions will be created as for an ordinary unread message
    """
    __slots__ = ("use_default_mute_for", "mute_for", "use_default_sound", "sound_id", "use_default_show_preview", "show_preview", "use_default_mute_stories", "mute_stories", "use_default_story_sound", "story_sound_id", "use_default_show_story_poster", "show_story_poster", "use_default_disable_pinned_message_notifications", "disable_pinned_message_notifications", "use_default_disable_mention_notifications", "disable_mention_notifications", "_extra", "_client_id", "_type")

    def __init__(self, use_default_mute_for: bool = False, mute_for: int = 0, use_default_sound: bool = False, sound_id: int = 0, use_default_show_preview: bool = False, show_preview: bool = False, use_default_mute_stories: bool = False, mute_stories: bool = False, use_default_story_sound: bool = False, story_sound_id: int = 0, use_default_show_story_poster: bool = False, show_story_poster: bool = False, use_default_disable_pinned_message_notifications: bool = False, disable_pinned_message_notifications: bool = False, use_default_disable_mention_notifications: bool = False, disable_mention_notifications: bool = False):
        self.use_default_mute_for = use_default_mute_for
        self.mute_for = mute_for
        self.use_default_sound = use_default_sound
        self.sound_id = sound_id
        self.use_default_show_preview = use_default_show_preview
        self.show_preview = show_preview
        self.use_default_mute_stories = use_default_mute_stories
        self.mute_stories = mute_stories
        self.use_default_story_sound = use_default_story_sound
        self.story_sound_id = story_sound_id
        self.use_default_show_story_poster = use_default_show_story_poster
        self.show_story_poster = show_story_poster
        self.use_default_disable_pinned_message_notifications = use_default_disable_pinned_message_notifications
        self.disable_pinned_message_notifications = disable_pinned_message_notifications
        self.use_default_disable_mention_notifications = use_default_disable_mention_notifications
        self.disable_mention_notifications = disable_mention_notifications
        self._type = "chatNotificationSettings"