from .chat_invite_link import ChatInviteLink
from .object_base import ObjectBase
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatInviteLinks(ObjectBase):
    """
    Contains a list of chat invite links

    :param total_count: Approximate total number of chat invite links found
    :param invite_links: List of invite links
    """
    __slots__ = ("total_count", "invite_links", "_extra", "_client_id", "_type")

    def __init__(self, total_count: int = 0, invite_links: List[ChatInviteLink] | None = None):
        self.total_count = total_count
        self.invite_links = invite_links
        self._type = "chatInviteLinks"