from .chat_boost_source import ChatBoostSource

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatBoostSourceGiftCode(ChatBoostSource):
    """
    The chat created a Telegram Premium gift code for a user

    :param user_id: Identifier of a user, for which the gift code was created
    :param gift_code: The created Telegram Premium gift code, which is known only if this is a gift code for the current user, or it has already been claimed
    """
    __slots__ = ("user_id", "gift_code", "_extra", "_client_id", "_type")

    def __init__(self, user_id = None, gift_code = None):
        self.user_id = user_id
        self.gift_code = gift_code
        self._type = "chatBoostSourceGiftCode"