from .formatted_text import FormattedText
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatFolderName(ObjectBase):
    """
    Describes name of a chat folder

    :param text: The text of the chat folder name; 1-12 characters without line feeds. May contain only CustomEmoji entities
    :param animate_custom_emoji: True, if custom emoji in the name must be animated
    """
    __slots__ = ("text", "animate_custom_emoji", "_extra", "_client_id", "_type")

    def __init__(self, text: FormattedText | None = None, animate_custom_emoji: bool = False):
        self.text = text
        self.animate_custom_emoji = animate_custom_emoji
        self._type = "chatFolderName"