from .message_sender import MessageSender
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ChatMessageSender(ObjectBase):
    """
    Represents a message sender, which can be used to send messages in a chat

    :param sender: The message sender
    :param needs_premium: True, if Telegram Premium is needed to use the message sender
    """
    __slots__ = ("sender", "needs_premium", "_extra", "_client_id", "_type")

    def __init__(self, sender: MessageSender | None = None, needs_premium: bool = False):
        self.sender = sender
        self.needs_premium = needs_premium
        self._type = "chatMessageSender"