from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CheckAuthenticationBotToken(Function):
    """
    Checks the authentication token of a bot; to log in as a bot. Works only when the current authorization state is authorizationStateWaitPhoneNumber. Can be used instead of setAuthenticationPhoneNumber and checkAuthenticationCode to log in

    :param token: The bot token
    :return: :class:`Ok`
    """
    __slots__ = ("token", "_extra", "_client_id", "_type")

    def __init__(self, token = None):
        self.token = token
        self._type = "checkAuthenticationBotToken"