from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CheckQuickReplyShortcutName(Function):
    """
    Checks validness of a name for a quick reply shortcut. Can be called synchronously

    :param name: The name of the shortcut; 1-32 characters
    :return: :class:`Ok`
    """
    __slots__ = ("name", "_extra", "_client_id", "_type")

    def __init__(self, name = None):
        self.name = name
        self._type = "checkQuickReplyShortcutName"