from .function import Function

from .chat_invite_link_info import ChatInviteLinkInfo

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CheckChatInviteLink(Function[ChatInviteLinkInfo]):
    """
    Checks the validity of an invite link for a chat and returns information about the corresponding chat

    :param invite_link: Invite link to be checked
    :return: :class:`ChatInviteLinkInfo`
    """
    __slots__ = ("invite_link", "_extra", "_client_id", "_type")

    def __init__(self, invite_link: str = ""):
        self.invite_link = invite_link
        self._type = "checkChatInviteLink"