from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CheckWebAppFileDownload(Function[Ok]):
    """
    Checks whether a file can be downloaded and saved locally by Web App request

    :param bot_user_id: Identifier of the bot, providing the Web App
    :param file_name: Name of the file
    :param url: URL of the file
    :return: :class:`Ok`
    """
    __slots__ = ("bot_user_id", "file_name", "url", "_extra", "_client_id", "_type")

    def __init__(self, bot_user_id: int = 0, file_name: str = "", url: str = ""):
        self.bot_user_id = bot_user_id
        self.file_name = file_name
        self.url = url
        self._type = "checkWebAppFileDownload"