from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ClearSearchedForTags(Function[Ok]):
    """
    Clears the list of recently searched for hashtags or cashtags

    :param clear_cashtags: Pass true to clear the list of recently searched for cashtags; otherwise, the list of recently searched for hashtags will be cleared
    :return: :class:`Ok`
    """
    __slots__ = ("clear_cashtags", "_extra", "_client_id", "_type")

    def __init__(self, clear_cashtags: bool = False):
        self.clear_cashtags = clear_cashtags
        self._type = "clearSearchedForTags"