from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ClearRecentEmojiStatuses(Function):
    """
    Clears the list of recently used emoji statuses for self status

    :return: :class:`Ok`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "clearRecentEmojiStatuses"