from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ClickChatSponsoredMessage(Function[Ok]):
    """
    Informs TDLib that the user opened the sponsored chat via the button, the name, the chat photo, a mention in the sponsored message text, or the media in the sponsored message

    :param chat_id: Chat identifier of the sponsored message
    :param message_id: Identifier of the sponsored message
    :param is_media_click: Pass true if the media was clicked in the sponsored message
    :param from_fullscreen: Pass true if the user expanded the video from the sponsored message fullscreen before the click
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_id", "is_media_click", "from_fullscreen", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, message_id: int = 0, is_media_click: bool = False, from_fullscreen: bool = False):
        self.chat_id = chat_id
        self.message_id = message_id
        self.is_media_click = is_media_click
        self.from_fullscreen = from_fullscreen
        self._type = "clickChatSponsoredMessage"