from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CloseSecretChat(Function):
    """
    Closes a secret chat, effectively transferring its state to secretChatStateClosed

    :param secret_chat_id: Secret chat identifier
    :return: :class:`Ok`
    """
    __slots__ = ("secret_chat_id", "_extra", "_client_id", "_type")

    def __init__(self, secret_chat_id = None):
        self.secret_chat_id = secret_chat_id
        self._type = "closeSecretChat"