from .collectible_item_type import CollectibleItemType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CollectibleItemTypeUsername(CollectibleItemType):
    """
    A username

    :param username: The username
    """
    __slots__ = ("username", "_extra", "_client_id", "_type")

    def __init__(self, username: str = ""):
        self.username = username
        self._type = "collectibleItemTypeUsername"