from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ConnectedWebsites(ObjectBase):
    """
    Contains a list of websites the current user is logged in with Telegram

    :param websites: List of connected websites
    """
    __slots__ = ("websites", "_extra", "_client_id", "_type")

    def __init__(self, websites = None):
        self.websites = websites
        self._type = "connectedWebsites"