from .connection_state import ConnectionState

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ConnectionStateReady(ConnectionState):
    """
    There is a working connection to the Telegram servers

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "connectionStateReady"