from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ConnectionState(ObjectBase):
    """
    Describes the current state of the connection to Telegram servers

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "ConnectionState"