from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ConnectedWebsite(ObjectBase):
    """
    Contains information about one website the current user is logged in with Telegram

    :param id: Website identifier
    :param domain_name: The domain name of the website
    :param bot_user_id: User identifier of a bot linked with the website
    :param browser: The version of a browser used to log in
    :param platform: Operating system the browser is running on
    :param log_in_date: Point in time (Unix timestamp) when the user was logged in
    :param last_active_date: Point in time (Unix timestamp) when obtained authorization was last used
    :param ip_address: IP address from which the user was logged in, in human-readable format
    :param location: Human-readable description of a country and a region from which the user was logged in, based on the IP address
    """
    __slots__ = ("id", "domain_name", "bot_user_id", "browser", "platform", "log_in_date", "last_active_date", "ip_address", "location", "_extra", "_client_id", "_type")

    def __init__(self, id = None, domain_name = None, bot_user_id = None, browser = None, platform = None, log_in_date = None, last_active_date = None, ip_address = None, location = None):
        self.id = id
        self.domain_name = domain_name
        self.bot_user_id = bot_user_id
        self.browser = browser
        self.platform = platform
        self.log_in_date = log_in_date
        self.last_active_date = last_active_date
        self.ip_address = ip_address
        self.location = location
        self._type = "connectedWebsite"