from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class Contact(ObjectBase):
    """
    Describes a user contact

    :param phone_number: Phone number of the user
    :param first_name: First name of the user; 1-255 characters in length
    :param last_name: Last name of the user
    :param vcard: Additional data about the user in a form of vCard; 0-2048 bytes in length
    :param user_id: Identifier of the user, if known; 0 otherwise
    """
    __slots__ = ("phone_number", "first_name", "last_name", "vcard", "user_id", "_extra", "_client_id", "_type")

    def __init__(self, phone_number: str = "", first_name: str = "", last_name: str = "", vcard: str = "", user_id: int = 0):
        self.phone_number = phone_number
        self.first_name = first_name
        self.last_name = last_name
        self.vcard = vcard
        self.user_id = user_id
        self._type = "contact"