from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CreatePrivateChat(Function):
    """
    Returns an existing chat corresponding to a given user

    :param user_id: User identifier
    :param force: Pass true to create the chat without a network request. In this case all information about the chat except its type, title and photo can be incorrect
    :return: :class:`Chat`
    """
    __slots__ = ("user_id", "force", "_extra", "_client_id", "_type")

    def __init__(self, user_id = None, force = None):
        self.user_id = user_id
        self.force = force
        self._type = "createPrivateChat"