from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CreateInvoiceLink(Function):
    """
    Creates a link for the given invoice; for bots only

    :param business_connection_id: Unique identifier of business connection on behalf of which to send the request
    :param invoice: Information about the invoice of the type inputMessageInvoice
    :return: :class:`HttpUrl`
    """
    __slots__ = ("business_connection_id", "invoice", "_extra", "_client_id", "_type")

    def __init__(self, business_connection_id = None, invoice = None):
        self.business_connection_id = business_connection_id
        self.invoice = invoice
        self._type = "createInvoiceLink"