from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CreateNewSecretChat(Function):
    """
    Creates a new secret chat. Returns the newly created chat

    :param user_id: Identifier of the target user
    :return: :class:`Chat`
    """
    __slots__ = ("user_id", "_extra", "_client_id", "_type")

    def __init__(self, user_id = None):
        self.user_id = user_id
        self._type = "createNewSecretChat"