from .function import Function

from .created_basic_group_chat import CreatedBasicGroupChat
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CreateNewBasicGroupChat(Function[CreatedBasicGroupChat]):
    """
    Creates a new basic group and sends a corresponding messageBasicGroupChatCreate. Returns information about the newly created chat

    :param user_ids: Identifiers of users to be added to the basic group; may be empty to create a basic group without other members
    :param title: Title of the new basic group; 1-128 characters
    :param message_auto_delete_time: Message auto-delete time value, in seconds; must be from 0 up to 365 * 86400 and be divisible by 86400. If 0, then messages aren't deleted automatically
    :return: :class:`CreatedBasicGroupChat`
    """
    __slots__ = ("user_ids", "title", "message_auto_delete_time", "_extra", "_client_id", "_type")

    def __init__(self, user_ids: List[int] | None = None, title: str = "", message_auto_delete_time: int = 0):
        self.user_ids = user_ids
        self.title = title
        self.message_auto_delete_time = message_auto_delete_time
        self._type = "createNewBasicGroupChat"