from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class CurrentWeather(ObjectBase):
    """
    Describes the current weather

    :param temperature: Temperature, in degree Celsius
    :param emoji: Emoji representing the weather
    """
    __slots__ = ("temperature", "emoji", "_extra", "_client_id", "_type")

    def __init__(self, temperature: float = 0, emoji: str = ""):
        self.temperature = temperature
        self.emoji = emoji
        self._type = "currentWeather"