from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class Date(ObjectBase):
    """
    Represents a date according to the Gregorian calendar

    :param day: Day of the month; 1-31
    :param month: Month; 1-12
    :param year: Year; 1-9999
    """
    __slots__ = ("day", "month", "year", "_extra", "_client_id", "_type")

    def __init__(self, day: int = 0, month: int = 0, year: int = 0):
        self.day = day
        self.month = month
        self.year = year
        self._type = "date"