from .function import Function

from .data import Data
from .group_call_data_channel import GroupCallDataChannel
from .message_sender import MessageSender

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class DecryptGroupCallData(Function[Data]):
    """
    Decrypts group call data received by tgcalls

    :param group_call_id: Group call identifier. The call must not be a video chat
    :param participant_id: Identifier of the group call participant, which sent the data
    :param data_channel: Data channel for which data was encrypted; pass null if unknown
    :param data: Data to decrypt
    :return: :class:`Data`
    """
    __slots__ = ("group_call_id", "participant_id", "data_channel", "data", "_extra", "_client_id", "_type")

    def __init__(self, group_call_id: int = 0, participant_id: MessageSender | None = None, data_channel: GroupCallDataChannel | None = None, data: bytes = b""):
        self.group_call_id = group_call_id
        self.participant_id = participant_id
        self.data_channel = data_channel
        self.data = data
        self._type = "decryptGroupCallData"