from .formatted_text import FormattedText
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class DeepLinkInfo(ObjectBase):
    """
    Contains information about a tg: deep link

    :param text: Text to be shown to the user
    :param need_update_application: True, if the user must be asked to update the application
    """
    __slots__ = ("text", "need_update_application", "_extra", "_client_id", "_type")

    def __init__(self, text: FormattedText | None = None, need_update_application: bool = False):
        self.text = text
        self.need_update_application = need_update_application
        self._type = "deepLinkInfo"