from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class DeleteStickerSet(Function):
    """
    Completely deletes a sticker set

    :param name: Sticker set name. The sticker set must be owned by the current user
    :return: :class:`Ok`
    """
    __slots__ = ("name", "_extra", "_client_id", "_type")

    def __init__(self, name = None):
        self.name = name
        self._type = "deleteStickerSet"