from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class DeleteForumTopic(Function[Ok]):
    """
    Deletes all messages in a forum topic; requires can_delete_messages administrator right in the supergroup unless the user is creator of the topic, the topic has no messages from other users and has at most 11 messages

    :param chat_id: Identifier of the chat
    :param message_thread_id: Message thread identifier of the forum topic
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_thread_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, message_thread_id: int = 0):
        self.chat_id = chat_id
        self.message_thread_id = message_thread_id
        self._type = "deleteForumTopic"