from .device_token import DeviceToken

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class DeviceTokenMicrosoftPushVoIP(DeviceToken):
    """
    A token for Microsoft Push Notification Service VoIP channel

    :param channel_uri: Push notification channel URI; may be empty to deregister a device
    """
    __slots__ = ("channel_uri", "_extra", "_client_id", "_type")

    def __init__(self, channel_uri = None):
        self.channel_uri = channel_uri
        self._type = "deviceTokenMicrosoftPushVoIP"