from .device_token import DeviceToken

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class DeviceTokenFirebaseCloudMessaging(DeviceToken):
    """
    A token for Firebase Cloud Messaging

    :param token: Device registration token; may be empty to deregister a device
    :param encrypt: True, if push notifications must be additionally encrypted
    """
    __slots__ = ("token", "encrypt", "_extra", "_client_id", "_type")

    def __init__(self, token = None, encrypt = None):
        self.token = token
        self.encrypt = encrypt
        self._type = "deviceTokenFirebaseCloudMessaging"