from .device_token import DeviceToken

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class DeviceTokenUbuntuPush(DeviceToken):
    """
    A token for Ubuntu Push Client service

    :param token: Token; may be empty to deregister a device
    """
    __slots__ = ("token", "_extra", "_client_id", "_type")

    def __init__(self, token = None):
        self.token = token
        self._type = "deviceTokenUbuntuPush"