from .dice_stickers import DiceStickers
from .sticker import Sticker

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class DiceStickersSlotMachine(DiceStickers):
    """
    Animated stickers to be combined into a slot machine

    :param background: The animated sticker with the slot machine background. The background animation must start playing after all reel animations finish
    :param lever: The animated sticker with the lever animation. The lever animation must play once in the initial dice state
    :param left_reel: The animated sticker with the left reel
    :param center_reel: The animated sticker with the center reel
    :param right_reel: The animated sticker with the right reel
    """
    __slots__ = ("background", "lever", "left_reel", "center_reel", "right_reel", "_extra", "_client_id", "_type")

    def __init__(self, background: Sticker | None = None, lever: Sticker | None = None, left_reel: Sticker | None = None, center_reel: Sticker | None = None, right_reel: Sticker | None = None):
        self.background = background
        self.lever = lever
        self.left_reel = left_reel
        self.center_reel = center_reel
        self.right_reel = right_reel
        self._type = "diceStickersSlotMachine"