from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class DisableAllSupergroupUsernames(Function):
    """
    Disables all active non-editable usernames of a supergroup or channel, requires owner privileges in the supergroup or channel

    :param supergroup_id: Identifier of the supergroup or channel
    :return: :class:`Ok`
    """
    __slots__ = ("supergroup_id", "_extra", "_client_id", "_type")

    def __init__(self, supergroup_id = None):
        self.supergroup_id = supergroup_id
        self._type = "disableAllSupergroupUsernames"