from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class DownloadFile(Function):
    """
    Downloads a file from the cloud. Download progress and completion of the download will be notified through updateFile updates

    :param file_id: Identifier of the file to download
    :param priority: Priority of the download (1-32). The higher the priority, the earlier the file will be downloaded. If the priorities of two files are equal, then the last one for which downloadFile/addFileToDownloads was called will be downloaded first
    :param offset: The starting position from which the file needs to be downloaded
    :param limit: Number of bytes which need to be downloaded starting from the "offset" position before the download will automatically be canceled; use 0 to download without a limit
    :param synchronous: Pass true to return response only after the file download has succeeded, has failed, has been canceled, or a new downloadFile request with different offset/limit parameters was sent; pass false to return file state immediately, just after the download has been started
    :return: :class:`File`
    """
    __slots__ = ("file_id", "priority", "offset", "limit", "synchronous", "_extra", "_client_id", "_type")

    def __init__(self, file_id = None, priority = None, offset = None, limit = None, synchronous = None):
        self.file_id = file_id
        self.priority = priority
        self.offset = offset
        self.limit = limit
        self.synchronous = synchronous
        self._type = "downloadFile"