from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class DraftMessage(ObjectBase):
    """
    Contains information about a message draft

    :param reply_to: Information about the message to be replied; must be of the type inputMessageReplyToMessage; may be null if none
    :param date: Point in time (Unix timestamp) when the draft was created
    :param input_message_text: Content of the message draft; must be of the type inputMessageText, inputMessageVideoNote, or inputMessageVoiceNote
    :param effect_id: Identifier of the effect to apply to the message when it is sent; 0 if none
    """
    __slots__ = ("reply_to", "date", "input_message_text", "effect_id", "_extra", "_client_id", "_type")

    def __init__(self, reply_to = None, date = None, input_message_text = None, effect_id = None):
        self.reply_to = reply_to
        self.date = date
        self.input_message_text = input_message_text
        self.effect_id = effect_id
        self._type = "draftMessage"