from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class EditMessageSchedulingState(Function):
    """
    Edits the time when a scheduled message will be sent. Scheduling state of all messages in the same album or forwarded together with the message will be also changed

    :param chat_id: The chat the message belongs to
    :param message_id: Identifier of the message. Use messageProperties.can_edit_scheduling_state to check whether the message is suitable
    :param scheduling_state: The new message scheduling state; pass null to send the message immediately. Must be null for messages in the state messageSchedulingStateSendWhenVideoProcessed
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_id", "scheduling_state", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_id = None, scheduling_state = None):
        self.chat_id = chat_id
        self.message_id = message_id
        self.scheduling_state = scheduling_state
        self._type = "editMessageSchedulingState"