from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class EditForumTopic(Function):
    """
    Edits title and icon of a topic in a forum supergroup chat; requires can_manage_topics right in the supergroup unless the user is creator of the topic

    :param chat_id: Identifier of the chat
    :param message_thread_id: Message thread identifier of the forum topic
    :param name: New name of the topic; 0-128 characters. If empty, the previous topic name is kept
    :param edit_icon_custom_emoji: Pass true to edit the icon of the topic. Icon of the General topic can't be edited
    :param icon_custom_emoji_id: Identifier of the new custom emoji for topic icon; pass 0 to remove the custom emoji. Ignored if edit_icon_custom_emoji is false. Telegram Premium users can use any custom emoji, other users can use only a custom emoji returned by getForumTopicDefaultIcons
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_thread_id", "name", "edit_icon_custom_emoji", "icon_custom_emoji_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_thread_id = None, name = None, edit_icon_custom_emoji = None, icon_custom_emoji_id = None):
        self.chat_id = chat_id
        self.message_thread_id = message_thread_id
        self.name = name
        self.edit_icon_custom_emoji = edit_icon_custom_emoji
        self.icon_custom_emoji_id = icon_custom_emoji_id
        self._type = "editForumTopic"