from .function import Function

from .formatted_text import FormattedText
from .ok import Ok
from .reply_markup import ReplyMarkup

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class EditInlineMessageCaption(Function[Ok]):
    """
    Edits the caption of an inline message sent via a bot; for bots only

    :param inline_message_id: Inline message identifier
    :param reply_markup: The new message reply markup; pass null if none
    :param caption: New message content caption; pass null to remove caption; 0-getOption("message_caption_length_max") characters
    :param show_caption_above_media: Pass true to show the caption above the media; otherwise, the caption will be shown below the media. May be true only for animation, photo, and video messages
    :return: :class:`Ok`
    """
    __slots__ = ("inline_message_id", "reply_markup", "caption", "show_caption_above_media", "_extra", "_client_id", "_type")

    def __init__(self, inline_message_id: str = "", reply_markup: ReplyMarkup | None = None, caption: FormattedText | None = None, show_caption_above_media: bool = False):
        self.inline_message_id = inline_message_id
        self.reply_markup = reply_markup
        self.caption = caption
        self.show_caption_above_media = show_caption_above_media
        self._type = "editInlineMessageCaption"