from .function import Function

from .formatted_text import FormattedText
from .input_story_areas import InputStoryAreas
from .input_story_content import InputStoryContent
from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class EditStory(Function[Ok]):
    """
    Changes content and caption of a story. Can be called only if story.can_be_edited == true

    :param story_poster_chat_id: Identifier of the chat that posted the story
    :param story_id: Identifier of the story to edit
    :param content: New content of the story; pass null to keep the current content
    :param areas: New clickable rectangle areas to be shown on the story media; pass null to keep the current areas. Areas can't be edited if story content isn't changed
    :param caption: New story caption; pass null to keep the current caption
    :return: :class:`Ok`
    """
    __slots__ = ("story_poster_chat_id", "story_id", "content", "areas", "caption", "_extra", "_client_id", "_type")

    def __init__(self, story_poster_chat_id: int = 0, story_id: int = 0, content: InputStoryContent | None = None, areas: InputStoryAreas | None = None, caption: FormattedText | None = None):
        self.story_poster_chat_id = story_poster_chat_id
        self.story_id = story_id
        self.content = content
        self.areas = areas
        self.caption = caption
        self._type = "editStory"