from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class EditBusinessChatLink(Function):
    """
    Edits a business chat link of the current account. Requires Telegram Business subscription. Returns the edited link

    :param link: The link to edit
    :param link_info: New description of the link
    :return: :class:`BusinessChatLink`
    """
    __slots__ = ("link", "link_info", "_extra", "_client_id", "_type")

    def __init__(self, link = None, link_info = None):
        self.link = link
        self.link_info = link_info
        self._type = "editBusinessChatLink"