from .emoji_category_type import EmojiCategoryType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class EmojiCategoryTypeEmojiStatus(EmojiCategoryType):
    """
    The category must be used for emoji status selection

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "emojiCategoryTypeEmojiStatus"