from .dated_file import DatedFile
from .object_base import ObjectBase
from .passport_element_type import PassportElementType
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class EncryptedPassportElement(ObjectBase):
    """
    Contains information about an encrypted Telegram Passport element; for bots only

    :param type: Type of Telegram Passport element
    :param data: Encrypted JSON-encoded data about the user
    :param front_side: The front side of an identity document
    :param reverse_side: The reverse side of an identity document; may be null
    :param selfie: Selfie with the document; may be null
    :param translation: List of files containing a certified English translation of the document
    :param files: List of attached files
    :param value: Unencrypted data, phone number or email address
    :param hash: Hash of the entire element
    """
    __slots__ = ("type", "data", "front_side", "reverse_side", "selfie", "translation", "files", "value", "hash", "_extra", "_client_id", "_type")

    def __init__(self, type: PassportElementType | None = None, data: bytes = b"", front_side: DatedFile | None = None, reverse_side: DatedFile | None = None, selfie: DatedFile | None = None, translation: List[DatedFile] | None = None, files: List[DatedFile] | None = None, value: str = "", hash: str = ""):
        self.type = type
        self.data = data
        self.front_side = front_side
        self.reverse_side = reverse_side
        self.selfie = selfie
        self.translation = translation
        self.files = files
        self.value = value
        self.hash = hash
        self._type = "encryptedPassportElement"