from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class EncryptGroupCallData(Function):
    """
    Encrypts group call data before sending them over network using tgcalls

    :param group_call_id: Group call identifier. The call must not be a video chat
    :param data_channel: Data channel for which data is encrypted
    :param data: Data to encrypt
    :param unencrypted_prefix_size: Size of data prefix that must be kept unencrypted
    :return: :class:`Data`
    """
    __slots__ = ("group_call_id", "data_channel", "data", "unencrypted_prefix_size", "_extra", "_client_id", "_type")

    def __init__(self, group_call_id = None, data_channel = None, data = None, unencrypted_prefix_size = None):
        self.group_call_id = group_call_id
        self.data_channel = data_channel
        self.data = data
        self.unencrypted_prefix_size = unencrypted_prefix_size
        self._type = "encryptGroupCallData"