from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class FeedbackChatTopic(ObjectBase):
    """
    Contains information about a topic in a feedback chat

    :param chat_id: Identifier of the chat to which the topic belongs
    :param id: Unique topic identifier
    :param sender_id: Identifier of the user or chat that sends the feedback
    :param order: A parameter used to determine order of the topic in the topic list. Topics must be sorted by the order in descending order
    :param last_read_inbox_message_id: Identifier of the last read incoming message
    :param last_read_outbox_message_id: Identifier of the last read outgoing message
    :param unread_count: Number of unread messages in the chat
    :param is_marked_as_unread: True, if the forum topic is marked as unread
    :param last_message: Last message in the topic; may be null if none or unknown
    :param draft_message: A draft of a message in the topic; may be null if none
    """
    __slots__ = ("chat_id", "id", "sender_id", "order", "last_read_inbox_message_id", "last_read_outbox_message_id", "unread_count", "is_marked_as_unread", "last_message", "draft_message", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, id = None, sender_id = None, order = None, last_read_inbox_message_id = None, last_read_outbox_message_id = None, unread_count = None, is_marked_as_unread = None, last_message = None, draft_message = None):
        self.chat_id = chat_id
        self.id = id
        self.sender_id = sender_id
        self.order = order
        self.last_read_inbox_message_id = last_read_inbox_message_id
        self.last_read_outbox_message_id = last_read_outbox_message_id
        self.unread_count = unread_count
        self.is_marked_as_unread = is_marked_as_unread
        self.last_message = last_message
        self.draft_message = draft_message
        self._type = "feedbackChatTopic"