from .message import Message
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class FileDownload(ObjectBase):
    """
    Describes a file added to file download list

    :param file_id: File identifier
    :param message: The message with the file
    :param add_date: Point in time (Unix timestamp) when the file was added to the download list
    :param complete_date: Point in time (Unix timestamp) when the file downloading was completed; 0 if the file downloading isn't completed
    :param is_paused: True, if downloading of the file is paused
    """
    __slots__ = ("file_id", "message", "add_date", "complete_date", "is_paused", "_extra", "_client_id", "_type")

    def __init__(self, file_id: int = 0, message: Message | None = None, add_date: int = 0, complete_date: int = 0, is_paused: bool = False):
        self.file_id = file_id
        self.message = message
        self.add_date = add_date
        self.complete_date = complete_date
        self.is_paused = is_paused
        self._type = "fileDownload"