from .file_type import FileType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class FileTypePhoto(FileType):
    """
    The file is a photo

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "fileTypePhoto"