from .file_type import FileType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class FileTypeAudio(FileType):
    """
    The file is an audio file

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "fileTypeAudio"