from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class FinishFileGeneration(Function):
    """
    Finishes the file generation

    :param generation_id: The identifier of the generation process
    :param error: If passed, the file generation has failed and must be terminated; pass null if the file generation succeeded
    :return: :class:`Ok`
    """
    __slots__ = ("generation_id", "error", "_extra", "_client_id", "_type")

    def __init__(self, generation_id = None, error = None):
        self.generation_id = generation_id
        self.error = error
        self._type = "finishFileGeneration"