from .firebase_authentication_settings import FirebaseAuthenticationSettings

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class FirebaseAuthenticationSettingsIos(FirebaseAuthenticationSettings):
    """
    Settings for Firebase Authentication in the official iOS application

    :param device_token: Device token from Apple Push Notification service
    :param is_app_sandbox: True, if App Sandbox is enabled
    """
    __slots__ = ("device_token", "is_app_sandbox", "_extra", "_client_id", "_type")

    def __init__(self, device_token = None, is_app_sandbox = None):
        self.device_token = device_token
        self.is_app_sandbox = is_app_sandbox
        self._type = "firebaseAuthenticationSettingsIos"