from .firebase_device_verification_parameters import FirebaseDeviceVerificationParameters

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class FirebaseDeviceVerificationParametersPlayIntegrity(FirebaseDeviceVerificationParameters):
    """
    Device verification must be performed with the classic Play Integrity verification (https://developer.android.com/google/play/integrity/classic)

    :param nonce: Base64url-encoded nonce to pass to the Play Integrity API
    :param cloud_project_number: Cloud project number to pass to the Play Integrity API
    """
    __slots__ = ("nonce", "cloud_project_number", "_extra", "_client_id", "_type")

    def __init__(self, nonce = None, cloud_project_number = None):
        self.nonce = nonce
        self.cloud_project_number = cloud_project_number
        self._type = "firebaseDeviceVerificationParametersPlayIntegrity"