from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ForumTopicIcon(ObjectBase):
    """
    Describes a forum topic icon

    :param color: Color of the topic icon in RGB format
    :param custom_emoji_id: Unique identifier of the custom emoji shown on the topic icon; 0 if none
    """
    __slots__ = ("color", "custom_emoji_id", "_extra", "_client_id", "_type")

    def __init__(self, color: int = 0, custom_emoji_id: int = 0):
        self.color = color
        self.custom_emoji_id = custom_emoji_id
        self._type = "forumTopicIcon"