from .animation import Animation
from .formatted_text import FormattedText
from .object_base import ObjectBase
from .photo import Photo

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class Game(ObjectBase):
    """
    Describes a game. Use getInternalLink with internalLinkTypeGame to share the game

    :param id: Unique game identifier
    :param short_name: Game short name
    :param title: Game title
    :param text: Game text, usually containing scoreboards for a game
    :param description: Describes a game. Use getInternalLink with internalLinkTypeGame to share the game
    :param photo: Game photo
    :param animation: Game animation; may be null
    """
    __slots__ = ("id", "short_name", "title", "text", "description", "photo", "animation", "_extra", "_client_id", "_type")

    def __init__(self, id: int = 0, short_name: str = "", title: str = "", text: FormattedText | None = None, description: str = "", photo: Photo | None = None, animation: Animation | None = None):
        self.id = id
        self.short_name = short_name
        self.title = title
        self.text = text
        self.description = description
        self.photo = photo
        self.animation = animation
        self._type = "game"