from .function import Function

from .emoji_reaction import EmojiReaction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetEmojiReaction(Function[EmojiReaction]):
    """
    Returns information about an emoji reaction. Returns a 404 error if the reaction is not found

    :param emoji: Text representation of the reaction
    :return: :class:`EmojiReaction`
    """
    __slots__ = ("emoji", "_extra", "_client_id", "_type")

    def __init__(self, emoji: str = ""):
        self.emoji = emoji
        self._type = "getEmojiReaction"