from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetMessageReadDate(Function):
    """
    Returns read date of a recent outgoing message in a private chat. The method can be called if messageProperties.can_get_read_date == true

    :param chat_id: Chat identifier
    :param message_id: Identifier of the message
    :return: :class:`MessageReadDateRead | MessageReadDateUnread | MessageReadDateTooOld | MessageReadDateUserPrivacyRestricted | MessageReadDateMyPrivacyRestricted`
    """
    __slots__ = ("chat_id", "message_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_id = None):
        self.chat_id = chat_id
        self.message_id = message_id
        self._type = "getMessageReadDate"