from .function import Function

from .http_url import HttpUrl

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetProxyLink(Function[HttpUrl]):
    """
    Returns an HTTPS link, which can be used to add a proxy. Available only for SOCKS5 and MTProto proxies. Can be called before authorization

    :param proxy_id: Proxy identifier
    :return: :class:`HttpUrl`
    """
    __slots__ = ("proxy_id", "_extra", "_client_id", "_type")

    def __init__(self, proxy_id: int = 0):
        self.proxy_id = proxy_id
        self._type = "getProxyLink"