from .function import Function

from .sponsored_messages import SponsoredMessages

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetChatSponsoredMessages(Function[SponsoredMessages]):
    """
    Returns sponsored messages to be shown in a chat; for channel chats and chats with bots only

    :param chat_id: Identifier of the chat
    :return: :class:`SponsoredMessages`
    """
    __slots__ = ("chat_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0):
        self.chat_id = chat_id
        self._type = "getChatSponsoredMessages"