from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetChatMessagePosition(Function):
    """
    Returns approximate 1-based position of a message among messages, which can be found by the specified filter in the chat and topic. Cannot be used in secret chats

    :param chat_id: Identifier of the chat in which to find message position
    :param topic_id: Pass topic identifier to get position among messages only in specific topic; pass null to get position among all chat messages
    :param filter: Filter for message content; searchMessagesFilterEmpty, searchMessagesFilterUnreadMention, searchMessagesFilterUnreadReaction, and searchMessagesFilterFailedToSend are unsupported in this function
    :param message_id: Message identifier
    :return: :class:`Count`
    """
    __slots__ = ("chat_id", "topic_id", "filter", "message_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, topic_id = None, filter = None, message_id = None):
        self.chat_id = chat_id
        self.topic_id = topic_id
        self.filter = filter
        self.message_id = message_id
        self._type = "getChatMessagePosition"