from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetCurrentWeather(Function):
    """
    Returns the current weather in the given location

    :param location: The location
    :return: :class:`CurrentWeather`
    """
    __slots__ = ("location", "_extra", "_client_id", "_type")

    def __init__(self, location = None):
        self.location = location
        self._type = "getCurrentWeather"