from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetBackgroundUrl(Function):
    """
    Constructs a persistent HTTP URL for a background

    :param name: Background name
    :param type: Background type; backgroundTypeChatTheme isn't supported
    :return: :class:`HttpUrl`
    """
    __slots__ = ("name", "type", "_extra", "_client_id", "_type")

    def __init__(self, name = None, type = None):
        self.name = name
        self.type = type
        self._type = "getBackgroundUrl"