from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetPremiumState(Function):
    """
    Returns state of Telegram Premium subscription and promotion videos for Premium features

    :return: :class:`PremiumState`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getPremiumState"