from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetSupportUser(Function):
    """
    Returns a user that can be contacted to get support

    :return: :class:`User`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getSupportUser"