from .function import Function

from .backgrounds import Backgrounds

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetInstalledBackgrounds(Function[Backgrounds]):
    """
    Returns backgrounds installed by the user

    :param for_dark_theme: Pass true to order returned backgrounds for a dark theme
    :return: :class:`Backgrounds`
    """
    __slots__ = ("for_dark_theme", "_extra", "_client_id", "_type")

    def __init__(self, for_dark_theme: bool = False):
        self.for_dark_theme = for_dark_theme
        self._type = "getInstalledBackgrounds"