from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetSearchSponsoredChats(Function):
    """
    Returns sponsored chats to be shown in the search results

    :param query: Query the user searches for
    :return: :class:`SponsoredChats`
    """
    __slots__ = ("query", "_extra", "_client_id", "_type")

    def __init__(self, query = None):
        self.query = query
        self._type = "getSearchSponsoredChats"