from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetBusinessFeatures(Function):
    """
    Returns information about features, available to Business users

    :param source: Source of the request; pass null if the method is called from settings or some non-standard source
    :return: :class:`BusinessFeatures`
    """
    __slots__ = ("source", "_extra", "_client_id", "_type")

    def __init__(self, source = None):
        self.source = source
        self._type = "getBusinessFeatures"