from .function import Function

from .language_pack_info import LanguagePackInfo

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetLanguagePackInfo(Function[LanguagePackInfo]):
    """
    Returns information about a language pack. Returned language pack identifier may be different from a provided one. Can be called before authorization

    :param language_pack_id: Language pack identifier
    :return: :class:`LanguagePackInfo`
    """
    __slots__ = ("language_pack_id", "_extra", "_client_id", "_type")

    def __init__(self, language_pack_id: str = ""):
        self.language_pack_id = language_pack_id
        self._type = "getLanguagePackInfo"