from .function import Function

from .chats import Chats
from .notification_settings_scope import NotificationSettingsScope

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetChatNotificationSettingsExceptions(Function[Chats]):
    """
    Returns the list of chats with non-default notification settings for new messages

    :param scope: If specified, only chats from the scope will be returned; pass null to return chats from all scopes
    :param compare_sound: Pass true to include in the response chats with only non-default sound
    :return: :class:`Chats`
    """
    __slots__ = ("scope", "compare_sound", "_extra", "_client_id", "_type")

    def __init__(self, scope: NotificationSettingsScope | None = None, compare_sound: bool = False):
        self.scope = scope
        self.compare_sound = compare_sound
        self._type = "getChatNotificationSettingsExceptions"