from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetChatNotificationSettingsExceptions(Function):
    """
    Returns the list of chats with non-default notification settings for new messages

    :param scope: If specified, only chats from the scope will be returned; pass null to return chats from all scopes
    :param compare_sound: Pass true to include in the response chats with only non-default sound
    :return: :class:`Chats`
    """
    __slots__ = ("scope", "compare_sound", "_extra", "_client_id", "_type")

    def __init__(self, scope = None, compare_sound = None):
        self.scope = scope
        self.compare_sound = compare_sound
        self._type = "getChatNotificationSettingsExceptions"