from .function import Function

from .chat_boost_features import ChatBoostFeatures

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetChatBoostFeatures(Function[ChatBoostFeatures]):
    """
    Returns the list of features available for different chat boost levels. This is an offline method

    :param is_channel: Pass true to get the list of features for channels; pass false to get the list of features for supergroups
    :return: :class:`ChatBoostFeatures`
    """
    __slots__ = ("is_channel", "_extra", "_client_id", "_type")

    def __init__(self, is_channel: bool = False):
        self.is_channel = is_channel
        self._type = "getChatBoostFeatures"