from .function import Function

from .forum_topics import ForumTopics

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetForumTopics(Function[ForumTopics]):
    """
    Returns found forum topics in a forum chat. This is a temporary method for getting information about topic list from the server

    :param chat_id: Identifier of the forum chat
    :param query: Query to search for in the forum topic's name
    :param offset_date: The date starting from which the results need to be fetched. Use 0 or any date in the future to get results from the last topic
    :param offset_message_id: The message identifier of the last message in the last found topic, or 0 for the first request
    :param offset_message_thread_id: The message thread identifier of the last found topic, or 0 for the first request
    :param limit: The maximum number of forum topics to be returned; up to 100. For optimal performance, the number of returned forum topics is chosen by TDLib and can be smaller than the specified limit
    :return: :class:`ForumTopics`
    """
    __slots__ = ("chat_id", "query", "offset_date", "offset_message_id", "offset_message_thread_id", "limit", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, query: str = "", offset_date: int = 0, offset_message_id: int = 0, offset_message_thread_id: int = 0, limit: int = 0):
        self.chat_id = chat_id
        self.query = query
        self.offset_date = offset_date
        self.offset_message_id = offset_message_id
        self.offset_message_thread_id = offset_message_thread_id
        self.limit = limit
        self._type = "getForumTopics"