from .function import Function

from .file import File

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetFile(Function[File]):
    """
    Returns information about a file. This is an offline method

    :param file_id: Identifier of the file to get
    :return: :class:`File`
    """
    __slots__ = ("file_id", "_extra", "_client_id", "_type")

    def __init__(self, file_id: int = 0):
        self.file_id = file_id
        self._type = "getFile"