from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetLogStream(Function):
    """
    Returns information about currently used log stream for internal logging of TDLib. Can be called synchronously

    :return: :class:`LogStreamDefault | LogStreamFile | LogStreamEmpty`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getLogStream"