from .function import Function

from .emoji_statuses import EmojiStatuses

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetUpgradedGiftEmojiStatuses(Function[EmojiStatuses]):
    """
    Returns available upgraded gift emoji statuses for self status

    :return: :class:`EmojiStatuses`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getUpgradedGiftEmojiStatuses"