from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetAutoDownloadSettingsPresets(Function):
    """
    Returns auto-download settings presets for the current user

    :return: :class:`AutoDownloadSettingsPresets`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getAutoDownloadSettingsPresets"