from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetGroupCallParticipants(Function):
    """
    Returns information about participants of a non-joined group call that is not bound to a chat

    :param input_group_call: The group call which participants will be returned
    :param limit: The maximum number of participants to return; must be positive
    :return: :class:`GroupCallParticipants`
    """
    __slots__ = ("input_group_call", "limit", "_extra", "_client_id", "_type")

    def __init__(self, input_group_call = None, limit = None):
        self.input_group_call = input_group_call
        self.limit = limit
        self._type = "getGroupCallParticipants"