from .function import Function

from .star_amount import StarAmount

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetBusinessAccountStarAmount(Function[StarAmount]):
    """
    Returns the amount of Telegram Stars owned by a business account; for bots only

    :param business_connection_id: Unique identifier of business connection
    :return: :class:`StarAmount`
    """
    __slots__ = ("business_connection_id", "_extra", "_client_id", "_type")

    def __init__(self, business_connection_id: str = ""):
        self.business_connection_id = business_connection_id
        self._type = "getBusinessAccountStarAmount"