from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetInternalLinkType(Function):
    """
    Returns information about the type of internal link. Returns a 404 error if the link is not internal. Can be called before authorization

    :param link: The link
    :return: :class:`InternalLinkTypeActiveSessions | InternalLinkTypeAttachmentMenuBot | InternalLinkTypeAuthenticationCode | InternalLinkTypeBackground | InternalLinkTypeBotAddToChannel | InternalLinkTypeBotStart | InternalLinkTypeBotStartInGroup | InternalLinkTypeBusinessChat | InternalLinkTypeBuyStars | InternalLinkTypeChangePhoneNumber | InternalLinkTypeChatAffiliateProgram | InternalLinkTypeChatBoost | InternalLinkTypeChatFolderInvite | InternalLinkTypeChatFolderSettings | InternalLinkTypeChatInvite | InternalLinkTypeDefaultMessageAutoDeleteTimerSettings | InternalLinkTypeEditProfileSettings | InternalLinkTypeGame | InternalLinkTypeGroupCall | InternalLinkTypeInstantView | InternalLinkTypeInvoice | InternalLinkTypeLanguagePack | InternalLinkTypeLanguageSettings | InternalLinkTypeMainWebApp | InternalLinkTypeMessage | InternalLinkTypeMessageDraft | InternalLinkTypeMyStars | InternalLinkTypePassportDataRequest | InternalLinkTypePhoneNumberConfirmation | InternalLinkTypePremiumFeatures | InternalLinkTypePremiumGift | InternalLinkTypePremiumGiftCode | InternalLinkTypePrivacyAndSecuritySettings | InternalLinkTypeProxy | InternalLinkTypePublicChat | InternalLinkTypeQrCodeAuthentication | InternalLinkTypeRestorePurchases | InternalLinkTypeSettings | InternalLinkTypeStickerSet | InternalLinkTypeStory | InternalLinkTypeTheme | InternalLinkTypeThemeSettings | InternalLinkTypeUnknownDeepLink | InternalLinkTypeUnsupportedProxy | InternalLinkTypeUpgradedGift | InternalLinkTypeUserPhoneNumber | InternalLinkTypeUserToken | InternalLinkTypeVideoChat | InternalLinkTypeWebApp`
    """
    __slots__ = ("link", "_extra", "_client_id", "_type")

    def __init__(self, link = None):
        self.link = link
        self._type = "getInternalLinkType"