from .function import Function

from .text import Text

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetPreferredCountryLanguage(Function[Text]):
    """
    Returns an IETF language tag of the language preferred in the country, which must be used to fill native fields in Telegram Passport personal details. Returns a 404 error if unknown

    :param country_code: A two-letter ISO 3166-1 alpha-2 country code
    :return: :class:`Text`
    """
    __slots__ = ("country_code", "_extra", "_client_id", "_type")

    def __init__(self, country_code: str = ""):
        self.country_code = country_code
        self._type = "getPreferredCountryLanguage"