from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetEmojiCategories(Function):
    """
    Returns available emoji categories

    :param type: Type of emoji categories to return; pass null to get default emoji categories
    :return: :class:`EmojiCategories`
    """
    __slots__ = ("type", "_extra", "_client_id", "_type")

    def __init__(self, type = None):
        self.type = type
        self._type = "getEmojiCategories"