from .function import Function

from .bot_media_previews import BotMediaPreviews

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetBotMediaPreviews(Function[BotMediaPreviews]):
    """
    Returns the list of media previews of a bot

    :param bot_user_id: Identifier of the target bot. The bot must have the main Web App
    :return: :class:`BotMediaPreviews`
    """
    __slots__ = ("bot_user_id", "_extra", "_client_id", "_type")

    def __init__(self, bot_user_id: int = 0):
        self.bot_user_id = bot_user_id
        self._type = "getBotMediaPreviews"