from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetDisallowedChatEmojiStatuses(Function):
    """
    Returns the list of emoji statuses, which can't be used as chat emoji status, even they are from a sticker set with is_allowed_as_chat_emoji_status == true

    :return: :class:`EmojiStatusCustomEmojis`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getDisallowedChatEmojiStatuses"