from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetMessageThread(Function):
    """
    Returns information about a message thread. Can be used only if messageProperties.can_get_message_thread == true

    :param chat_id: Chat identifier
    :param message_id: Identifier of the message
    :return: :class:`MessageThreadInfo`
    """
    __slots__ = ("chat_id", "message_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_id = None):
        self.chat_id = chat_id
        self.message_id = message_id
        self._type = "getMessageThread"