from .function import Function

from .sessions import Sessions

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetActiveSessions(Function[Sessions]):
    """
    Returns all active sessions of the current user

    :return: :class:`Sessions`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getActiveSessions"