from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetLogTagVerbosityLevel(Function):
    """
    Returns current verbosity level for a specified TDLib internal log tag. Can be called synchronously

    :param tag: Logging tag to change verbosity level
    :return: :class:`LogVerbosityLevel`
    """
    __slots__ = ("tag", "_extra", "_client_id", "_type")

    def __init__(self, tag = None):
        self.tag = tag
        self._type = "getLogTagVerbosityLevel"