from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetRecommendedChats(Function):
    """
    Returns a list of channel chats recommended to the current user

    :return: :class:`Chats`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getRecommendedChats"