from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetFileMimeType(Function):
    """
    Returns the MIME type of a file, guessed by its extension. Returns an empty string on failure. Can be called synchronously

    :param file_name: The name of the file or path to the file
    :return: :class:`Text`
    """
    __slots__ = ("file_name", "_extra", "_client_id", "_type")

    def __init__(self, file_name = None):
        self.file_name = file_name
        self._type = "getFileMimeType"