from .function import Function

from .option_value_boolean import OptionValueBoolean
from .option_value_empty import OptionValueEmpty
from .option_value_integer import OptionValueInteger
from .option_value_string import OptionValueString

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetOption(Function[OptionValueBoolean | OptionValueEmpty | OptionValueInteger | OptionValueString]):
    """
    Returns the value of an option by its name. (Check the list of available options on https://core.telegram.org/tdlib/options.) Can be called before authorization. Can be called synchronously for options "version" and "commit_hash"

    :param name: The name of the option
    :return: :class:`OptionValueBoolean | OptionValueEmpty | OptionValueInteger | OptionValueString`
    """
    __slots__ = ("name", "_extra", "_client_id", "_type")

    def __init__(self, name: str = ""):
        self.name = name
        self._type = "getOption"