from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetChatAdministrators(Function):
    """
    Returns a list of administrators of the chat with their custom titles

    :param chat_id: Chat identifier
    :return: :class:`ChatAdministrators`
    """
    __slots__ = ("chat_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None):
        self.chat_id = chat_id
        self._type = "getChatAdministrators"