from .function import Function

from .animated_emoji import AnimatedEmoji

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetAnimatedEmoji(Function[AnimatedEmoji]):
    """
    Returns an animated emoji corresponding to a given emoji. Returns a 404 error if the emoji has no animated emoji

    :param emoji: The emoji
    :return: :class:`AnimatedEmoji`
    """
    __slots__ = ("emoji", "_extra", "_client_id", "_type")

    def __init__(self, emoji: str = ""):
        self.emoji = emoji
        self._type = "getAnimatedEmoji"