from .function import Function

from .affiliate_type import AffiliateType
from .connected_affiliate_program import ConnectedAffiliateProgram

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetConnectedAffiliateProgram(Function[ConnectedAffiliateProgram]):
    """
    Returns an affiliate program that were connected to the given affiliate by identifier of the bot that created the program

    :param affiliate: The affiliate to which the affiliate program will be connected
    :param bot_user_id: Identifier of the bot that created the program
    :return: :class:`ConnectedAffiliateProgram`
    """
    __slots__ = ("affiliate", "bot_user_id", "_extra", "_client_id", "_type")

    def __init__(self, affiliate: AffiliateType | None = None, bot_user_id: int = 0):
        self.affiliate = affiliate
        self.bot_user_id = bot_user_id
        self._type = "getConnectedAffiliateProgram"