from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetMapThumbnailFile(Function):
    """
    Returns information about a file with a map thumbnail in PNG format. Only map thumbnail files with size less than 1MB can be downloaded

    :param location: Location of the map center
    :param zoom: Map zoom level; 13-20
    :param width: Map width in pixels before applying scale; 16-1024
    :param height: Map height in pixels before applying scale; 16-1024
    :param scale: Map scale; 1-3
    :param chat_id: Identifier of a chat in which the thumbnail will be shown. Use 0 if unknown
    :return: :class:`File`
    """
    __slots__ = ("location", "zoom", "width", "height", "scale", "chat_id", "_extra", "_client_id", "_type")

    def __init__(self, location = None, zoom = None, width = None, height = None, scale = None, chat_id = None):
        self.location = location
        self.zoom = zoom
        self.width = width
        self.height = height
        self.scale = scale
        self.chat_id = chat_id
        self._type = "getMapThumbnailFile"