from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetPaymentReceipt(Function):
    """
    Returns information about a successful payment

    :param chat_id: Chat identifier of the messagePaymentSuccessful message
    :param message_id: Message identifier
    :return: :class:`PaymentReceipt`
    """
    __slots__ = ("chat_id", "message_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_id = None):
        self.chat_id = chat_id
        self.message_id = message_id
        self._type = "getPaymentReceipt"