from .function import Function

from .hashtags import Hashtags

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetSearchedForTags(Function[Hashtags]):
    """
    Returns recently searched for hashtags or cashtags by their prefix

    :param tag_prefix: Prefix of hashtags or cashtags to return
    :param limit: The maximum number of items to be returned
    :return: :class:`Hashtags`
    """
    __slots__ = ("tag_prefix", "limit", "_extra", "_client_id", "_type")

    def __init__(self, tag_prefix: str = "", limit: int = 0):
        self.tag_prefix = tag_prefix
        self.limit = limit
        self._type = "getSearchedForTags"