from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetDirectMessagesChatTopicMessageByDate(Function):
    """
    Returns the last message sent in the topic in a channel direct messages chat administered by the current user no later than the specified date

    :param chat_id: Chat identifier of the channel direct messages chat
    :param topic_id: Identifier of the topic which messages will be fetched
    :param date: Point in time (Unix timestamp) relative to which to search for messages
    :return: :class:`Message`
    """
    __slots__ = ("chat_id", "topic_id", "date", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, topic_id = None, date = None):
        self.chat_id = chat_id
        self.topic_id = topic_id
        self.date = date
        self._type = "getDirectMessagesChatTopicMessageByDate"