from .function import Function

from .updates import Updates

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetCurrentState(Function[Updates]):
    """
    Returns all updates needed to restore current TDLib state, i.e. all actual updateAuthorizationState/updateUser/updateNewChat and others. This is especially useful if TDLib is run in a separate process. Can be called before initialization

    :return: :class:`Updates`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getCurrentState"