from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetSuggestedStickerSetName(Function):
    """
    Returns a suggested name for a new sticker set with a given title

    :param title: Sticker set title; 1-64 characters
    :return: :class:`Text`
    """
    __slots__ = ("title", "_extra", "_client_id", "_type")

    def __init__(self, title = None):
        self.title = title
        self._type = "getSuggestedStickerSetName"