from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetLoginUrlInfo(Function):
    """
    Returns information about a button of type inlineKeyboardButtonTypeLoginUrl. The method needs to be called when the user presses the button

    :param chat_id: Chat identifier of the message with the button
    :param message_id: Message identifier of the message with the button. The message must not be scheduled
    :param button_id: Button identifier
    :return: :class:`LoginUrlInfoOpen | LoginUrlInfoRequestConfirmation`
    """
    __slots__ = ("chat_id", "message_id", "button_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_id = None, button_id = None):
        self.chat_id = chat_id
        self.message_id = message_id
        self.button_id = button_id
        self._type = "getLoginUrlInfo"