from .function import Function

from .archive_chat_list_settings import ArchiveChatListSettings

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetArchiveChatListSettings(Function[ArchiveChatListSettings]):
    """
    Returns settings for automatic moving of chats to and from the Archive chat lists

    :return: :class:`ArchiveChatListSettings`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getArchiveChatListSettings"