from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetTemporaryPasswordState(Function):
    """
    Returns information about the current temporary password

    :return: :class:`TemporaryPasswordState`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getTemporaryPasswordState"