from .function import Function

from .chat_message_senders import ChatMessageSenders

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetChatAvailableMessageSenders(Function[ChatMessageSenders]):
    """
    Returns the list of message sender identifiers, which can be used to send messages in a chat

    :param chat_id: Chat identifier
    :return: :class:`ChatMessageSenders`
    """
    __slots__ = ("chat_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0):
        self.chat_id = chat_id
        self._type = "getChatAvailableMessageSenders"