from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetChatSimilarChats(Function):
    """
    Returns a list of chats similar to the given chat

    :param chat_id: Identifier of the target chat; must be an identifier of a channel chat
    :return: :class:`Chats`
    """
    __slots__ = ("chat_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None):
        self.chat_id = chat_id
        self._type = "getChatSimilarChats"