from .function import Function

from .chats import Chats

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetChatSimilarChats(Function[Chats]):
    """
    Returns a list of chats similar to the given chat

    :param chat_id: Identifier of the target chat; must be an identifier of a channel chat
    :return: :class:`Chats`
    """
    __slots__ = ("chat_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0):
        self.chat_id = chat_id
        self._type = "getChatSimilarChats"