from .function import Function

from .story_statistics import StoryStatistics

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetStoryStatistics(Function[StoryStatistics]):
    """
    Returns detailed statistics about a story. Can be used only if story.can_get_statistics == true

    :param chat_id: Chat identifier
    :param story_id: Story identifier
    :param is_dark: Pass true if a dark theme is used by the application
    :return: :class:`StoryStatistics`
    """
    __slots__ = ("chat_id", "story_id", "is_dark", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, story_id: int = 0, is_dark: bool = False):
        self.chat_id = chat_id
        self.story_id = story_id
        self.is_dark = is_dark
        self._type = "getStoryStatistics"