from .function import Function

from .available_gifts import AvailableGifts

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetAvailableGifts(Function[AvailableGifts]):
    """
    Returns gifts that can be sent to other users and channel chats

    :return: :class:`AvailableGifts`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getAvailableGifts"