from .function import Function

from .read_date_privacy_settings import ReadDatePrivacySettings

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetReadDatePrivacySettings(Function[ReadDatePrivacySettings]):
    """
    Returns privacy settings for message read date

    :return: :class:`ReadDatePrivacySettings`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getReadDatePrivacySettings"