from .function import Function

from .stickers import Stickers
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetCustomEmojiStickers(Function[Stickers]):
    """
    Returns the list of custom emoji stickers by their identifiers. Stickers are returned in arbitrary order. Only found stickers are returned

    :param custom_emoji_ids: Identifiers of custom emoji stickers. At most 200 custom emoji stickers can be received simultaneously
    :return: :class:`Stickers`
    """
    __slots__ = ("custom_emoji_ids", "_extra", "_client_id", "_type")

    def __init__(self, custom_emoji_ids: List[int] | None = None):
        self.custom_emoji_ids = custom_emoji_ids
        self._type = "getCustomEmojiStickers"