from .function import Function

from .story import Story

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetStory(Function[Story]):
    """
    Returns a story

    :param story_poster_chat_id: Identifier of the chat that posted the story
    :param story_id: Story identifier
    :param only_local: Pass true to get only locally available information without sending network requests
    :return: :class:`Story`
    """
    __slots__ = ("story_poster_chat_id", "story_id", "only_local", "_extra", "_client_id", "_type")

    def __init__(self, story_poster_chat_id: int = 0, story_id: int = 0, only_local: bool = False):
        self.story_poster_chat_id = story_poster_chat_id
        self.story_id = story_id
        self.only_local = only_local
        self._type = "getStory"