from .function import Function

from .premium_gift_payment_options import PremiumGiftPaymentOptions

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetPremiumGiftPaymentOptions(Function[PremiumGiftPaymentOptions]):
    """
    Returns available options for gifting Telegram Premium to a user

    :return: :class:`PremiumGiftPaymentOptions`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getPremiumGiftPaymentOptions"