from .function import Function

from .sponsored_chats import SponsoredChats

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetSearchSponsoredChats(Function[SponsoredChats]):
    """
    Returns sponsored chats to be shown in the search results

    :param query: Query the user searches for
    :return: :class:`SponsoredChats`
    """
    __slots__ = ("query", "_extra", "_client_id", "_type")

    def __init__(self, query: str = ""):
        self.query = query
        self._type = "getSearchSponsoredChats"