from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetThemedChatEmojiStatuses(Function):
    """
    Returns up to 8 emoji statuses, which must be shown in the emoji status list for chats

    :return: :class:`EmojiStatusCustomEmojis`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "getThemedChatEmojiStatuses"