from .function import Function

from .user_full_info import UserFullInfo

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetUserFullInfo(Function[UserFullInfo]):
    """
    Returns full information about a user by their identifier

    :param user_id: User identifier
    :return: :class:`UserFullInfo`
    """
    __slots__ = ("user_id", "_extra", "_client_id", "_type")

    def __init__(self, user_id: int = 0):
        self.user_id = user_id
        self._type = "getUserFullInfo"