from .function import Function

from .http_url import HttpUrl

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetVideoChatInviteLink(Function[HttpUrl]):
    """
    Returns invite link to a video chat in a public chat

    :param group_call_id: Group call identifier
    :param can_self_unmute: Pass true if the invite link needs to contain an invite hash, passing which to joinVideoChat would allow the invited user to unmute themselves. Requires groupCall.can_be_managed right
    :return: :class:`HttpUrl`
    """
    __slots__ = ("group_call_id", "can_self_unmute", "_extra", "_client_id", "_type")

    def __init__(self, group_call_id: int = 0, can_self_unmute: bool = False):
        self.group_call_id = group_call_id
        self.can_self_unmute = can_self_unmute
        self._type = "getVideoChatInviteLink"