from .function import Function

from .added_reactions import AddedReactions
from .reaction_type import ReactionType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetMessageAddedReactions(Function[AddedReactions]):
    """
    Returns reactions added for a message, along with their sender

    :param chat_id: Identifier of the chat to which the message belongs
    :param message_id: Identifier of the message. Use message.interaction_info.reactions.can_get_added_reactions to check whether added reactions can be received for the message
    :param reaction_type: Type of the reactions to return; pass null to return all added reactions; reactionTypePaid isn't supported
    :param offset: Offset of the first entry to return as received from the previous request; use empty string to get the first chunk of results
    :param limit: The maximum number of reactions to be returned; must be positive and can't be greater than 100
    :return: :class:`AddedReactions`
    """
    __slots__ = ("chat_id", "message_id", "reaction_type", "offset", "limit", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, message_id: int = 0, reaction_type: ReactionType | None = None, offset: str = "", limit: int = 0):
        self.chat_id = chat_id
        self.message_id = message_id
        self.reaction_type = reaction_type
        self.offset = offset
        self.limit = limit
        self._type = "getMessageAddedReactions"