from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GetSupergroupMembers(Function):
    """
    Returns information about members or banned users in a supergroup or channel. Can be used only if supergroupFullInfo.can_get_members == true; additionally, administrator privileges may be required for some filters

    :param supergroup_id: Identifier of the supergroup or channel
    :param filter: The type of users to return; pass null to use supergroupMembersFilterRecent
    :param offset: Number of users to skip
    :param limit: The maximum number of users to be returned; up to 200
    :return: :class:`ChatMembers`
    """
    __slots__ = ("supergroup_id", "filter", "offset", "limit", "_extra", "_client_id", "_type")

    def __init__(self, supergroup_id = None, filter = None, offset = None, limit = None):
        self.supergroup_id = supergroup_id
        self.filter = filter
        self.offset = offset
        self.limit = limit
        self._type = "getSupergroupMembers"