from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GiveawayParticipantStatus(ObjectBase):
    """
    Contains information about status of a user in a giveaway

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "GiveawayParticipantStatus"