from .message_sender import MessageSender
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class GroupCallRecentSpeaker(ObjectBase):
    """
    Describes a recently speaking participant in a group call

    :param participant_id: Group call participant identifier
    :param is_speaking: True, is the user has spoken recently
    """
    __slots__ = ("participant_id", "is_speaking", "_extra", "_client_id", "_type")

    def __init__(self, participant_id: MessageSender | None = None, is_speaking: bool = False):
        self.participant_id = participant_id
        self.is_speaking = is_speaking
        self._type = "groupCallRecentSpeaker"