from .inline_keyboard_button_type import InlineKeyboardButtonType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InlineKeyboardButtonTypeSwitchInline(InlineKeyboardButtonType):
    """
    A button that forces an inline query to the bot to be inserted in the input field

    :param query: Inline query to be sent to the bot
    :param target_chat: Target chat from which to send the inline query
    """
    __slots__ = ("query", "target_chat", "_extra", "_client_id", "_type")

    def __init__(self, query = None, target_chat = None):
        self.query = query
        self.target_chat = target_chat
        self._type = "inlineKeyboardButtonTypeSwitchInline"