from .inline_keyboard_button_type import InlineKeyboardButtonType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InlineKeyboardButtonTypeCopyText(InlineKeyboardButtonType):
    """
    A button that copies specified text to clipboard

    :param text: The text to copy to clipboard
    """
    __slots__ = ("text", "_extra", "_client_id", "_type")

    def __init__(self, text: str = ""):
        self.text = text
        self._type = "inlineKeyboardButtonTypeCopyText"