from .input_story_content import InputStoryContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputStoryContentPhoto(InputStoryContent):
    """
    A photo story

    :param photo: Photo to send. The photo must be at most 10 MB in size. The photo size must be 1080x1920
    :param added_sticker_file_ids: File identifiers of the stickers added to the photo, if applicable
    """
    __slots__ = ("photo", "added_sticker_file_ids", "_extra", "_client_id", "_type")

    def __init__(self, photo = None, added_sticker_file_ids = None):
        self.photo = photo
        self.added_sticker_file_ids = added_sticker_file_ids
        self._type = "inputStoryContentPhoto"