from .input_file import InputFile

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputFileGenerated(InputFile):
    """
    A file generated by the application. The application must handle updates updateFileGenerationStart and updateFileGenerationStop to generate the file when asked by TDLib

    :param original_path: Local path to a file from which the file is generated. The path doesn't have to be a valid path and is used by TDLib only to detect name and MIME type of the generated file
    :param conversion: String specifying the conversion applied to the original file; must be persistent across application restarts. Conversions beginning with '#' are reserved for internal TDLib usage
    :param expected_size: Expected size of the generated file, in bytes; pass 0 if unknown
    """
    __slots__ = ("original_path", "conversion", "expected_size", "_extra", "_client_id", "_type")

    def __init__(self, original_path = None, conversion = None, expected_size = None):
        self.original_path = original_path
        self.conversion = conversion
        self.expected_size = expected_size
        self._type = "inputFileGenerated"