from .input_passport_element import InputPassportElement
from .input_personal_document import InputPersonalDocument

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputPassportElementPassportRegistration(InputPassportElement):
    """
    A Telegram Passport element to be saved containing the user's passport registration

    :param passport_registration: The passport registration page to be saved
    """
    __slots__ = ("passport_registration", "_extra", "_client_id", "_type")

    def __init__(self, passport_registration: InputPersonalDocument | None = None):
        self.passport_registration = passport_registration
        self._type = "inputPassportElementPassportRegistration"