from .input_file import InputFile

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputFileLocal(InputFile):
    """
    A file defined by a local path

    :param path: Local path to the file
    """
    __slots__ = ("path", "_extra", "_client_id", "_type")

    def __init__(self, path = None):
        self.path = path
        self._type = "inputFileLocal"