from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputGroupCall(ObjectBase):
    """
    Describes a non-joined group call that isn't bound to a chat

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "InputGroupCall"