from .input_passport_element import InputPassportElement

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputPassportElementPassport(InputPassportElement):
    """
    A Telegram Passport element to be saved containing the user's passport

    :param passport: The passport to be saved
    """
    __slots__ = ("passport", "_extra", "_client_id", "_type")

    def __init__(self, passport = None):
        self.passport = passport
        self._type = "inputPassportElementPassport"