from .input_background import InputBackground

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputBackgroundLocal(InputBackground):
    """
    A background from a local file

    :param background: Background file to use. Only inputFileLocal and inputFileGenerated are supported. The file must be in JPEG format for wallpapers and in PNG format for patterns
    """
    __slots__ = ("background", "_extra", "_client_id", "_type")

    def __init__(self, background = None):
        self.background = background
        self._type = "inputBackgroundLocal"