from .input_passport_element_error_source import InputPassportElementErrorSource

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputPassportElementErrorSourceFrontSide(InputPassportElementErrorSource):
    """
    The front side of the document contains an error. The error is considered resolved when the file with the front side of the document changes

    :param file_hash: Current hash of the file containing the front side
    """
    __slots__ = ("file_hash", "_extra", "_client_id", "_type")

    def __init__(self, file_hash: bytes = b""):
        self.file_hash = file_hash
        self._type = "inputPassportElementErrorSourceFrontSide"