from .formatted_text import FormattedText
from .input_file import InputFile
from .input_message_content import InputMessageContent
from .input_thumbnail import InputThumbnail
from .message_self_destruct_type import MessageSelfDestructType
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputMessageVideo(InputMessageContent):
    """
    A video message

    :param video: Video to be sent. The video is expected to be re-encoded to MPEG4 format with H.264 codec by the sender
    :param thumbnail: Video thumbnail; pass null to skip thumbnail uploading
    :param cover: Cover of the video; pass null to skip cover uploading; not supported in secret chats and for self-destructing messages
    :param start_timestamp: Timestamp from which the video playing must start, in seconds
    :param added_sticker_file_ids: File identifiers of the stickers added to the video, if applicable
    :param duration: Duration of the video, in seconds
    :param width: Video width
    :param height: Video height
    :param supports_streaming: True, if the video is expected to be streamed
    :param caption: Video caption; pass null to use an empty caption; 0-getOption("message_caption_length_max") characters
    :param show_caption_above_media: True, if the caption must be shown above the video; otherwise, the caption must be shown below the video; not supported in secret chats
    :param self_destruct_type: Video self-destruct type; pass null if none; private chats only
    :param has_spoiler: True, if the video preview must be covered by a spoiler animation; not supported in secret chats
    """
    __slots__ = ("video", "thumbnail", "cover", "start_timestamp", "added_sticker_file_ids", "duration", "width", "height", "supports_streaming", "caption", "show_caption_above_media", "self_destruct_type", "has_spoiler", "_extra", "_client_id", "_type")

    def __init__(self, video: InputFile | None = None, thumbnail: InputThumbnail | None = None, cover: InputFile | None = None, start_timestamp: int = 0, added_sticker_file_ids: List[int] | None = None, duration: int = 0, width: int = 0, height: int = 0, supports_streaming: bool = False, caption: FormattedText | None = None, show_caption_above_media: bool = False, self_destruct_type: MessageSelfDestructType | None = None, has_spoiler: bool = False):
        self.video = video
        self.thumbnail = thumbnail
        self.cover = cover
        self.start_timestamp = start_timestamp
        self.added_sticker_file_ids = added_sticker_file_ids
        self.duration = duration
        self.width = width
        self.height = height
        self.supports_streaming = supports_streaming
        self.caption = caption
        self.show_caption_above_media = show_caption_above_media
        self.self_destruct_type = self_destruct_type
        self.has_spoiler = has_spoiler
        self._type = "inputMessageVideo"