from .input_message_content import InputMessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputMessageSticker(InputMessageContent):
    """
    A sticker message

    :param sticker: Sticker to be sent
    :param thumbnail: Sticker thumbnail; pass null to skip thumbnail uploading
    :param width: Sticker width
    :param height: Sticker height
    :param emoji: Emoji used to choose the sticker
    """
    __slots__ = ("sticker", "thumbnail", "width", "height", "emoji", "_extra", "_client_id", "_type")

    def __init__(self, sticker = None, thumbnail = None, width = None, height = None, emoji = None):
        self.sticker = sticker
        self.thumbnail = thumbnail
        self.width = width
        self.height = height
        self.emoji = emoji
        self._type = "inputMessageSticker"