from .input_passport_element_error_source import InputPassportElementErrorSource

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputPassportElementErrorSourceFile(InputPassportElementErrorSource):
    """
    The file contains an error. The error is considered resolved when the file changes

    :param file_hash: Current hash of the file which has the error
    """
    __slots__ = ("file_hash", "_extra", "_client_id", "_type")

    def __init__(self, file_hash = None):
        self.file_hash = file_hash
        self._type = "inputPassportElementErrorSourceFile"