from .input_passport_element_error_source import InputPassportElementErrorSource

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputPassportElementErrorSourceTranslationFile(InputPassportElementErrorSource):
    """
    One of the files containing the translation of the document contains an error. The error is considered resolved when the file with the translation changes

    :param file_hash: Current hash of the file containing the translation
    """
    __slots__ = ("file_hash", "_extra", "_client_id", "_type")

    def __init__(self, file_hash = None):
        self.file_hash = file_hash
        self._type = "inputPassportElementErrorSourceTranslationFile"