from .input_identity_document import InputIdentityDocument
from .input_passport_element import InputPassportElement

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputPassportElementIdentityCard(InputPassportElement):
    """
    A Telegram Passport element to be saved containing the user's identity card

    :param identity_card: The identity card to be saved
    """
    __slots__ = ("identity_card", "_extra", "_client_id", "_type")

    def __init__(self, identity_card: InputIdentityDocument | None = None):
        self.identity_card = identity_card
        self._type = "inputPassportElementIdentityCard"