from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputPersonalDocument(ObjectBase):
    """
    A personal document to be saved to Telegram Passport

    :param files: List of files containing the pages of the document
    :param translation: List of files containing a certified English translation of the document
    """
    __slots__ = ("files", "translation", "_extra", "_client_id", "_type")

    def __init__(self, files = None, translation = None):
        self.files = files
        self.translation = translation
        self._type = "inputPersonalDocument"