from .input_credentials import InputCredentials

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputCredentialsSaved(InputCredentials):
    """
    Applies if a user chooses some previously saved payment credentials. To use their previously saved credentials, the user must have a valid temporary password

    :param saved_credentials_id: Identifier of the saved credentials
    """
    __slots__ = ("saved_credentials_id", "_extra", "_client_id", "_type")

    def __init__(self, saved_credentials_id: str = ""):
        self.saved_credentials_id = saved_credentials_id
        self._type = "inputCredentialsSaved"