from .input_passport_element_error_source import InputPassportElementErrorSource

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputPassportElementErrorSourceUnspecified(InputPassportElementErrorSource):
    """
    The element contains an error in an unspecified place. The error will be considered resolved when new data is added

    :param element_hash: Current hash of the entire element
    """
    __slots__ = ("element_hash", "_extra", "_client_id", "_type")

    def __init__(self, element_hash = None):
        self.element_hash = element_hash
        self._type = "inputPassportElementErrorSourceUnspecified"