from .input_passport_element import InputPassportElement

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InputPassportElementPhoneNumber(InputPassportElement):
    """
    A Telegram Passport element to be saved containing the user's phone number

    :param phone_number: The phone number to be saved
    """
    __slots__ = ("phone_number", "_extra", "_client_id", "_type")

    def __init__(self, phone_number: str = ""):
        self.phone_number = phone_number
        self._type = "inputPassportElementPhoneNumber"