from .internal_link_type import InternalLinkType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InternalLinkTypeVideoChat(InternalLinkType):
    """
    The link is a link to a video chat. Call searchPublicChat with the given chat username, and then joinVideoChat with the given invite hash to process the link

    :param chat_username: Username of the chat with the video chat
    :param invite_hash: If non-empty, invite hash to be used to join the video chat without being muted by administrators
    :param is_live_stream: True, if the video chat is expected to be a live stream in a channel or a broadcast group
    """
    __slots__ = ("chat_username", "invite_hash", "is_live_stream", "_extra", "_client_id", "_type")

    def __init__(self, chat_username: str = "", invite_hash: str = "", is_live_stream: bool = False):
        self.chat_username = chat_username
        self.invite_hash = invite_hash
        self.is_live_stream = is_live_stream
        self._type = "internalLinkTypeVideoChat"