from .internal_link_type import InternalLinkType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InternalLinkTypeChatFolderSettings(InternalLinkType):
    """
    The link is a link to the folder section of the application settings

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "internalLinkTypeChatFolderSettings"