from .internal_link_type import InternalLinkType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InternalLinkTypeBuyStars(InternalLinkType):
    """
    The link is a link to the Telegram Star purchase section of the application

    :param star_count: The number of Telegram Stars that must be owned by the user
    :param purpose: Purpose of Telegram Star purchase. Arbitrary string specified by the server, for example, "subs" if the Telegram Stars are required to extend channel subscriptions
    """
    __slots__ = ("star_count", "purpose", "_extra", "_client_id", "_type")

    def __init__(self, star_count = None, purpose = None):
        self.star_count = star_count
        self.purpose = purpose
        self._type = "internalLinkTypeBuyStars"