from .internal_link_type import InternalLinkType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InternalLinkTypeBusinessChat(InternalLinkType):
    """
    The link is a link to a business chat. Use getBusinessChatLinkInfo with the provided link name to get information about the link, then open received private chat and replace chat draft with the provided text

    :param link_name: Name of the link
    """
    __slots__ = ("link_name", "_extra", "_client_id", "_type")

    def __init__(self, link_name: str = ""):
        self.link_name = link_name
        self._type = "internalLinkTypeBusinessChat"