from .internal_link_type import InternalLinkType
from .proxy_type import ProxyType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InternalLinkTypeProxy(InternalLinkType):
    """
    The link is a link to a proxy. Call addProxy with the given parameters to process the link and add the proxy

    :param server: Proxy server domain or IP address
    :param port: Proxy server port
    :param type: Type of the proxy
    """
    __slots__ = ("server", "port", "type", "_extra", "_client_id", "_type")

    def __init__(self, server: str = "", port: int = 0, type: ProxyType | None = None):
        self.server = server
        self.port = port
        self.type = type
        self._type = "internalLinkTypeProxy"