from .internal_link_type import InternalLinkType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InternalLinkTypeGroupCall(InternalLinkType):
    """
    The link is a link to a group call that isn't bound to a chat. Use getGroupCallParticipants to get the list of group call participants and show them on the join group call screen. Call joinGroupCall with the given invite_link to join the call

    :param invite_link: Internal representation of the invite link
    """
    __slots__ = ("invite_link", "_extra", "_client_id", "_type")

    def __init__(self, invite_link: str = ""):
        self.invite_link = invite_link
        self._type = "internalLinkTypeGroupCall"