from .internal_link_type import InternalLinkType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class InternalLinkTypePremiumGiftCode(InternalLinkType):
    """
    The link is a link with a Telegram Premium gift code. Call checkPremiumGiftCode with the given code to process the link. If the code is valid and the user wants to apply it, then call applyPremiumGiftCode

    :param code: The Telegram Premium gift code
    """
    __slots__ = ("code", "_extra", "_client_id", "_type")

    def __init__(self, code: str = ""):
        self.code = code
        self._type = "internalLinkTypePremiumGiftCode"