from .keyboard_button_type import KeyboardButtonType
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class KeyboardButton(ObjectBase):
    """
    Represents a single button in a bot keyboard

    :param text: Text of the button
    :param type: Type of the button
    """
    __slots__ = ("text", "type", "_extra", "_client_id", "_type")

    def __init__(self, text: str = "", type: KeyboardButtonType | None = None):
        self.text = text
        self.type = type
        self._type = "keyboardButton"