from .keyboard_button_type import KeyboardButtonType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class KeyboardButtonTypeRequestLocation(KeyboardButtonType):
    """
    A button that sends the user's location when pressed; available only in private chats

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "keyboardButtonTypeRequestLocation"