from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class LanguagePackStrings(ObjectBase):
    """
    Contains a list of language pack strings

    :param strings: A list of language pack strings
    """
    __slots__ = ("strings", "_extra", "_client_id", "_type")

    def __init__(self, strings = None):
        self.strings = strings
        self._type = "languagePackStrings"