from .function import Function

from .giveaway_parameters import GiveawayParameters
from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class LaunchPrepaidGiveaway(Function[Ok]):
    """
    Launches a prepaid giveaway

    :param giveaway_id: Unique identifier of the prepaid giveaway
    :param parameters: Giveaway parameters
    :param winner_count: The number of users to receive giveaway prize
    :param star_count: The number of Telegram Stars to be distributed through the giveaway; pass 0 for Telegram Premium giveaways
    :return: :class:`Ok`
    """
    __slots__ = ("giveaway_id", "parameters", "winner_count", "star_count", "_extra", "_client_id", "_type")

    def __init__(self, giveaway_id: int = 0, parameters: GiveawayParameters | None = None, winner_count: int = 0, star_count: int = 0):
        self.giveaway_id = giveaway_id
        self.parameters = parameters
        self.winner_count = winner_count
        self.star_count = star_count
        self._type = "launchPrepaidGiveaway"