from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class LeaveChat(Function):
    """
    Removes the current user from chat members. Private and secret chats can't be left using this method

    :param chat_id: Chat identifier
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None):
        self.chat_id = chat_id
        self._type = "leaveChat"