from .link_preview_type import LinkPreviewType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class LinkPreviewTypeExternalVideo(LinkPreviewType):
    """
    The link is a link to a video file

    :param url: URL of the video file
    :param mime_type: MIME type of the video file
    :param width: Expected width of the video preview; 0 if unknown
    :param height: Expected height of the video preview; 0 if unknown
    :param duration: Duration of the video, in seconds; 0 if unknown
    """
    __slots__ = ("url", "mime_type", "width", "height", "duration", "_extra", "_client_id", "_type")

    def __init__(self, url: str = "", mime_type: str = "", width: int = 0, height: int = 0, duration: int = 0):
        self.url = url
        self.mime_type = mime_type
        self.width = width
        self.height = height
        self.duration = duration
        self._type = "linkPreviewTypeExternalVideo"