from .link_preview_type import LinkPreviewType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class LinkPreviewTypeApp(LinkPreviewType):
    """
    The link is a link to an app at App Store or Google Play

    :param photo: Photo for the app
    """
    __slots__ = ("photo", "_extra", "_client_id", "_type")

    def __init__(self, photo = None):
        self.photo = photo
        self._type = "linkPreviewTypeApp"