from .link_preview_type import LinkPreviewType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class LinkPreviewTypeVideo(LinkPreviewType):
    """
    The link is a link to a video

    :param video: The video description
    :param cover: Cover of the video; may be null if none
    :param start_timestamp: Timestamp from which the video playing must start, in seconds
    """
    __slots__ = ("video", "cover", "start_timestamp", "_extra", "_client_id", "_type")

    def __init__(self, video = None, cover = None, start_timestamp = None):
        self.video = video
        self.cover = cover
        self.start_timestamp = start_timestamp
        self._type = "linkPreviewTypeVideo"