from .chat_photo import ChatPhoto
from .link_preview_type import LinkPreviewType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class LinkPreviewTypeSupergroupBoost(LinkPreviewType):
    """
    The link is a link to boost a supergroup chat

    :param photo: Photo of the chat; may be null
    """
    __slots__ = ("photo", "_extra", "_client_id", "_type")

    def __init__(self, photo: ChatPhoto | None = None):
        self.photo = photo
        self._type = "linkPreviewTypeSupergroupBoost"