from .link_preview_type import LinkPreviewType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class LinkPreviewTypeGroupCall(LinkPreviewType):
    """
    The link is a link to a group call that isn't bound to a chat

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "linkPreviewTypeGroupCall"