from .link_preview_type import LinkPreviewType
from .photo import Photo

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class LinkPreviewTypeArticle(LinkPreviewType):
    """
    The link is a link to a web site

    :param photo: Article's main photo; may be null
    """
    __slots__ = ("photo", "_extra", "_client_id", "_type")

    def __init__(self, photo: Photo | None = None):
        self.photo = photo
        self._type = "linkPreviewTypeArticle"