from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class LoadQuickReplyShortcutMessages(Function[Ok]):
    """
    Loads quick reply messages that can be sent by a given quick reply shortcut. The loaded messages will be sent through updateQuickReplyShortcutMessages

    :param shortcut_id: Unique identifier of the quick reply shortcut
    :return: :class:`Ok`
    """
    __slots__ = ("shortcut_id", "_extra", "_client_id", "_type")

    def __init__(self, shortcut_id: int = 0):
        self.shortcut_id = shortcut_id
        self._type = "loadQuickReplyShortcutMessages"