from .object_base import ObjectBase
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class LogTags(ObjectBase):
    """
    Contains a list of available TDLib internal log tags

    :param tags: List of log tags
    """
    __slots__ = ("tags", "_extra", "_client_id", "_type")

    def __init__(self, tags: List[str] | None = None):
        self.tags = tags
        self._type = "logTags"