from .mask_point import MaskPoint
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MaskPosition(ObjectBase):
    """
    Position on a photo where a mask is placed

    :param point: Part of the face, relative to which the mask is placed
    :param x_shift: Shift by X-axis measured in widths of the mask scaled to the face size, from left to right. (For example, -1.0 will place the mask just to the left of the default mask position)
    :param y_shift: Shift by Y-axis measured in heights of the mask scaled to the face size, from top to bottom. (For example, 1.0 will place the mask just below the default mask position)
    :param scale: Mask scaling coefficient. (For example, 2.0 means a doubled size)
    """
    __slots__ = ("point", "x_shift", "y_shift", "scale", "_extra", "_client_id", "_type")

    def __init__(self, point: MaskPoint | None = None, x_shift: float = 0, y_shift: float = 0, scale: float = 0):
        self.point = point
        self.x_shift = x_shift
        self.y_shift = y_shift
        self.scale = scale
        self._type = "maskPosition"