from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageProperties(ObjectBase):
    """
    Contains properties of a message and describes actions that can be done with the message right now

    :param can_be_copied: True, if content of the message can be copied using inputMessageForwarded or forwardMessages with copy options
    :param can_be_copied_to_secret_chat: True, if content of the message can be copied to a secret chat using inputMessageForwarded or forwardMessages with copy options
    :param can_be_deleted_only_for_self: True, if the message can be deleted only for the current user while other users will continue to see it using the method deleteMessages with revoke == false
    :param can_be_deleted_for_all_users: True, if the message can be deleted for all users using the method deleteMessages with revoke == true
    :param can_be_edited: True, if the message can be edited using the methods editMessageText, editMessageCaption, or editMessageReplyMarkup. For live location and poll messages this fields shows whether editMessageLiveLocation or stopPoll can be used with this message
    :param can_be_forwarded: True, if the message can be forwarded using inputMessageForwarded or forwardMessages without copy options
    :param can_be_paid: True, if the message can be paid using inputInvoiceMessage
    :param can_be_pinned: True, if the message can be pinned or unpinned in the chat using pinChatMessage or unpinChatMessage
    :param can_be_replied: True, if the message can be replied in the same chat and forum topic using inputMessageReplyToMessage
    :param can_be_replied_in_another_chat: True, if the message can be replied in another chat or forum topic using inputMessageReplyToExternalMessage
    :param can_be_saved: True, if content of the message can be saved locally
    :param can_be_shared_in_story: True, if the message can be shared in a story using inputStoryAreaTypeMessage
    :param can_edit_media: True, if the message can be edited using the method editMessageMedia
    :param can_edit_scheduling_state: True, if scheduling state of the message can be edited
    :param can_get_author: True, if author of the message sent on behalf of a chat can be received through getMessageAuthor
    :param can_get_embedding_code: True, if code for message embedding can be received using getMessageEmbeddingCode
    :param can_get_link: True, if a link can be generated for the message using getMessageLink
    :param can_get_media_timestamp_links: True, if media timestamp links can be generated for media timestamp entities in the message text, caption or link preview description using getMessageLink
    :param can_get_message_thread: True, if information about the message thread is available through getMessageThread and getMessageThreadHistory
    :param can_get_read_date: True, if read date of the message can be received through getMessageReadDate
    :param can_get_statistics: True, if message statistics are available through getMessageStatistics and message forwards can be received using getMessagePublicForwards
    :param can_get_viewers: True, if chat members already viewed the message can be received through getMessageViewers
    :param can_recognize_speech: True, if speech can be recognized for the message through recognizeSpeech
    :param can_report_chat: True, if the message can be reported using reportChat
    :param can_report_reactions: True, if reactions on the message can be reported through reportMessageReactions
    :param can_report_supergroup_spam: True, if the message can be reported using reportSupergroupSpam
    :param can_set_fact_check: True, if fact check for the message can be changed through setMessageFactCheck
    :param need_show_statistics: True, if message statistics must be available from context menu of the message
    """
    __slots__ = ("can_be_copied", "can_be_copied_to_secret_chat", "can_be_deleted_only_for_self", "can_be_deleted_for_all_users", "can_be_edited", "can_be_forwarded", "can_be_paid", "can_be_pinned", "can_be_replied", "can_be_replied_in_another_chat", "can_be_saved", "can_be_shared_in_story", "can_edit_media", "can_edit_scheduling_state", "can_get_author", "can_get_embedding_code", "can_get_link", "can_get_media_timestamp_links", "can_get_message_thread", "can_get_read_date", "can_get_statistics", "can_get_viewers", "can_recognize_speech", "can_report_chat", "can_report_reactions", "can_report_supergroup_spam", "can_set_fact_check", "need_show_statistics", "_extra", "_client_id", "_type")

    def __init__(self, can_be_copied = None, can_be_copied_to_secret_chat = None, can_be_deleted_only_for_self = None, can_be_deleted_for_all_users = None, can_be_edited = None, can_be_forwarded = None, can_be_paid = None, can_be_pinned = None, can_be_replied = None, can_be_replied_in_another_chat = None, can_be_saved = None, can_be_shared_in_story = None, can_edit_media = None, can_edit_scheduling_state = None, can_get_author = None, can_get_embedding_code = None, can_get_link = None, can_get_media_timestamp_links = None, can_get_message_thread = None, can_get_read_date = None, can_get_statistics = None, can_get_viewers = None, can_recognize_speech = None, can_report_chat = None, can_report_reactions = None, can_report_supergroup_spam = None, can_set_fact_check = None, need_show_statistics = None):
        self.can_be_copied = can_be_copied
        self.can_be_copied_to_secret_chat = can_be_copied_to_secret_chat
        self.can_be_deleted_only_for_self = can_be_deleted_only_for_self
        self.can_be_deleted_for_all_users = can_be_deleted_for_all_users
        self.can_be_edited = can_be_edited
        self.can_be_forwarded = can_be_forwarded
        self.can_be_paid = can_be_paid
        self.can_be_pinned = can_be_pinned
        self.can_be_replied = can_be_replied
        self.can_be_replied_in_another_chat = can_be_replied_in_another_chat
        self.can_be_saved = can_be_saved
        self.can_be_shared_in_story = can_be_shared_in_story
        self.can_edit_media = can_edit_media
        self.can_edit_scheduling_state = can_edit_scheduling_state
        self.can_get_author = can_get_author
        self.can_get_embedding_code = can_get_embedding_code
        self.can_get_link = can_get_link
        self.can_get_media_timestamp_links = can_get_media_timestamp_links
        self.can_get_message_thread = can_get_message_thread
        self.can_get_read_date = can_get_read_date
        self.can_get_statistics = can_get_statistics
        self.can_get_viewers = can_get_viewers
        self.can_recognize_speech = can_recognize_speech
        self.can_report_chat = can_report_chat
        self.can_report_reactions = can_report_reactions
        self.can_report_supergroup_spam = can_report_supergroup_spam
        self.can_set_fact_check = can_set_fact_check
        self.need_show_statistics = need_show_statistics
        self._type = "messageProperties"