from .message_content import MessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessagePaidMessagePriceChanged(MessageContent):
    """
    A price for paid messages was changed in the supergroup chat

    :param paid_message_star_count: The new number of Telegram Stars that must be paid by non-administrator users of the supergroup chat for each sent message
    """
    __slots__ = ("paid_message_star_count", "_extra", "_client_id", "_type")

    def __init__(self, paid_message_star_count: int = 0):
        self.paid_message_star_count = paid_message_star_count
        self._type = "messagePaidMessagePriceChanged"