from .message_content import MessageContent
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageBasicGroupChatCreate(MessageContent):
    """
    A newly created basic group

    :param title: Title of the basic group
    :param member_user_ids: User identifiers of members in the basic group
    """
    __slots__ = ("title", "member_user_ids", "_extra", "_client_id", "_type")

    def __init__(self, title: str = "", member_user_ids: List[int] | None = None):
        self.title = title
        self.member_user_ids = member_user_ids
        self._type = "messageBasicGroupChatCreate"