from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class Messages(ObjectBase):
    """
    Contains a list of messages

    :param total_count: Approximate total number of messages found
    :param messages: List of messages; messages may be null
    """
    __slots__ = ("total_count", "messages", "_extra", "_client_id", "_type")

    def __init__(self, total_count = None, messages = None):
        self.total_count = total_count
        self.messages = messages
        self._type = "messages"