from .message_source import MessageSource

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageSourceNotification(MessageSource):
    """
    The message is from a notification

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "messageSourceNotification"