from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageImportInfo(ObjectBase):
    """
    Contains information about a message created with importMessages

    :param sender_name: Name of the original sender
    :param date: Point in time (Unix timestamp) when the message was originally sent
    """
    __slots__ = ("sender_name", "date", "_extra", "_client_id", "_type")

    def __init__(self, sender_name: str = "", date: int = 0):
        self.sender_name = sender_name
        self.date = date
        self._type = "messageImportInfo"