from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageCopyOptions(ObjectBase):
    """
    Options to be used when a message content is copied without reference to the original sender. Service messages, messages with messageInvoice, messagePaidMedia, messageGiveaway, or messageGiveawayWinners content can't be copied

    :param send_copy: True, if content of the message needs to be copied without reference to the original sender. Always true if the message is forwarded to a secret chat or is local. Use messageProperties.can_be_copied and messageProperties.can_be_copied_to_secret_chat to check whether the message is suitable
    :param replace_caption: True, if media caption of the message copy needs to be replaced. Ignored if send_copy is false
    :param new_caption: New message caption; pass null to copy message without caption. Ignored if replace_caption is false
    :param new_show_caption_above_media: True, if new caption must be shown above the media; otherwise, new caption must be shown below the media; not supported in secret chats. Ignored if replace_caption is false
    """
    __slots__ = ("send_copy", "replace_caption", "new_caption", "new_show_caption_above_media", "_extra", "_client_id", "_type")

    def __init__(self, send_copy = None, replace_caption = None, new_caption = None, new_show_caption_above_media = None):
        self.send_copy = send_copy
        self.replace_caption = replace_caption
        self.new_caption = new_caption
        self.new_show_caption_above_media = new_show_caption_above_media
        self._type = "messageCopyOptions"