from .message_content import MessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageChatJoinByLink(MessageContent):
    """
    A new member joined the chat via an invite link

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "messageChatJoinByLink"