from .message_content import MessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessagePassportDataReceived(MessageContent):
    """
    Telegram Passport data has been received; for bots only

    :param elements: List of received Telegram Passport elements
    :param credentials: Encrypted data credentials
    """
    __slots__ = ("elements", "credentials", "_extra", "_client_id", "_type")

    def __init__(self, elements = None, credentials = None):
        self.elements = elements
        self.credentials = credentials
        self._type = "messagePassportDataReceived"