from .message_content import MessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageChatChangeTitle(MessageContent):
    """
    An updated chat title

    :param title: New chat title
    """
    __slots__ = ("title", "_extra", "_client_id", "_type")

    def __init__(self, title: str = ""):
        self.title = title
        self._type = "messageChatChangeTitle"