from .message_content import MessageContent
from .shared_chat import SharedChat

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageChatShared(MessageContent):
    """
    The current user shared a chat, which was requested by the bot

    :param chat: The shared chat
    :param button_id: Identifier of the keyboard button with the request
    """
    __slots__ = ("chat", "button_id", "_extra", "_client_id", "_type")

    def __init__(self, chat: SharedChat | None = None, button_id: int = 0):
        self.chat = chat
        self.button_id = button_id
        self._type = "messageChatShared"