from .message_origin import MessageOrigin

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageOriginHiddenUser(MessageOrigin):
    """
    The message was originally sent by a user, which is hidden by their privacy settings

    :param sender_name: Name of the sender
    """
    __slots__ = ("sender_name", "_extra", "_client_id", "_type")

    def __init__(self, sender_name: str = ""):
        self.sender_name = sender_name
        self._type = "messageOriginHiddenUser"