from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageTopic(ObjectBase):
    """
    Describes a topic of messages in a chat

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "MessageTopic"