from .message_source import MessageSource

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageSourceForumTopicHistory(MessageSource):
    """
    The message is from history of a forum topic

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "messageSourceForumTopicHistory"