from .formatted_text import FormattedText
from .message_content import MessageContent
from .paid_media import PaidMedia
from .product_info import ProductInfo

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageInvoice(MessageContent):
    """
    A message with an invoice from a bot. Use getInternalLink with internalLinkTypeBotStart to share the invoice

    :param product_info: Information about the product
    :param currency: Currency for the product price
    :param total_amount: Product total price in the smallest units of the currency
    :param start_parameter: Unique invoice bot start_parameter to be passed to getInternalLink
    :param is_test: True, if the invoice is a test invoice
    :param need_shipping_address: True, if the shipping address must be specified
    :param receipt_message_id: The identifier of the message with the receipt, after the product has been purchased
    :param paid_media: Extended media attached to the invoice; may be null if none
    :param paid_media_caption: Extended media caption; may be null if none
    """
    __slots__ = ("product_info", "currency", "total_amount", "start_parameter", "is_test", "need_shipping_address", "receipt_message_id", "paid_media", "paid_media_caption", "_extra", "_client_id", "_type")

    def __init__(self, product_info: ProductInfo | None = None, currency: str = "", total_amount: int = 0, start_parameter: str = "", is_test: bool = False, need_shipping_address: bool = False, receipt_message_id: int = 0, paid_media: PaidMedia | None = None, paid_media_caption: FormattedText | None = None):
        self.product_info = product_info
        self.currency = currency
        self.total_amount = total_amount
        self.start_parameter = start_parameter
        self.is_test = is_test
        self.need_shipping_address = need_shipping_address
        self.receipt_message_id = receipt_message_id
        self.paid_media = paid_media
        self.paid_media_caption = paid_media_caption
        self._type = "messageInvoice"