from .message_content import MessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessageGiveawayPrizeStars(MessageContent):
    """
    A Telegram Stars were received by the current user from a giveaway

    :param star_count: Number of Telegram Stars that were received
    :param transaction_id: Identifier of the transaction for Telegram Stars credit
    :param boosted_chat_id: Identifier of the supergroup or channel chat, which was automatically boosted by the winners of the giveaway
    :param giveaway_message_id: Identifier of the message with the giveaway in the boosted chat; can be 0 if the message was deleted
    :param is_unclaimed: True, if the corresponding winner wasn't chosen and the Telegram Stars were received by the owner of the boosted chat
    :param sticker: A sticker to be shown in the message; may be null if unknown
    """
    __slots__ = ("star_count", "transaction_id", "boosted_chat_id", "giveaway_message_id", "is_unclaimed", "sticker", "_extra", "_client_id", "_type")

    def __init__(self, star_count = None, transaction_id = None, boosted_chat_id = None, giveaway_message_id = None, is_unclaimed = None, sticker = None):
        self.star_count = star_count
        self.transaction_id = transaction_id
        self.boosted_chat_id = boosted_chat_id
        self.giveaway_message_id = giveaway_message_id
        self.is_unclaimed = is_unclaimed
        self.sticker = sticker
        self._type = "messageGiveawayPrizeStars"