from .message_content import MessageContent
from .poll import Poll

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class MessagePoll(MessageContent):
    """
    A message with a poll

    :param poll: The poll description
    """
    __slots__ = ("poll", "_extra", "_client_id", "_type")

    def __init__(self, poll: Poll | None = None):
        self.poll = poll
        self._type = "messagePoll"