from .notification_group_type import NotificationGroupType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class NotificationGroupTypeSecretChat(NotificationGroupType):
    """
    A group containing a notification of type notificationTypeNewSecretChat

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "notificationGroupTypeSecretChat"