from .message_sender import MessageSender
from .notification_type import NotificationType
from .push_message_content import PushMessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class NotificationTypeNewPushMessage(NotificationType):
    """
    New message was received through a push notification

    :param message_id: The message identifier. The message will not be available in the chat history, but the identifier can be used in viewMessages, or as a message to be replied in the same chat
    :param sender_id: Identifier of the sender of the message. Corresponding user or chat may be inaccessible
    :param sender_name: Name of the sender
    :param is_outgoing: True, if the message is outgoing
    :param content: Push message content
    """
    __slots__ = ("message_id", "sender_id", "sender_name", "is_outgoing", "content", "_extra", "_client_id", "_type")

    def __init__(self, message_id: int = 0, sender_id: MessageSender | None = None, sender_name: str = "", is_outgoing: bool = False, content: PushMessageContent | None = None):
        self.message_id = message_id
        self.sender_id = sender_id
        self.sender_name = sender_name
        self.is_outgoing = is_outgoing
        self.content = content
        self._type = "notificationTypeNewPushMessage"