from .notification_sound import NotificationSound
from .object_base import ObjectBase
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class NotificationSounds(ObjectBase):
    """
    Contains a list of notification sounds

    :param notification_sounds: A list of notification sounds
    """
    __slots__ = ("notification_sounds", "_extra", "_client_id", "_type")

    def __init__(self, notification_sounds: List[NotificationSound] | None = None):
        self.notification_sounds = notification_sounds
        self._type = "notificationSounds"