from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class NotificationGroup(ObjectBase):
    """
    Describes a group of notifications

    :param id: Unique persistent auto-incremented from 1 identifier of the notification group
    :param type: Type of the group
    :param chat_id: Identifier of a chat to which all notifications in the group belong
    :param total_count: Total number of active notifications in the group
    :param notifications: The list of active notifications
    """
    __slots__ = ("id", "type", "chat_id", "total_count", "notifications", "_extra", "_client_id", "_type")

    def __init__(self, id = None, type = None, chat_id = None, total_count = None, notifications = None):
        self.id = id
        self.type = type
        self.chat_id = chat_id
        self.total_count = total_count
        self.notifications = notifications
        self._type = "notificationGroup"