from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class OpenMessageContent(Function):
    """
    Informs TDLib that the message content has been opened (e.g., the user has opened a photo, video, document, location or venue, or has listened to an audio file or voice note message). An updateMessageContentOpened update will be generated if something has changed

    :param chat_id: Chat identifier of the message
    :param message_id: Identifier of the message with the opened content
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_id = None):
        self.chat_id = chat_id
        self.message_id = message_id
        self._type = "openMessageContent"