from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class OrderInfo(ObjectBase):
    """
    Order information

    :param name: Name of the user
    :param phone_number: Phone number of the user
    :param email_address: Email address of the user
    :param shipping_address: Shipping address for this order; may be null
    """
    __slots__ = ("name", "phone_number", "email_address", "shipping_address", "_extra", "_client_id", "_type")

    def __init__(self, name = None, phone_number = None, email_address = None, shipping_address = None):
        self.name = name
        self.phone_number = phone_number
        self.email_address = email_address
        self.shipping_address = shipping_address
        self._type = "orderInfo"