from .page_block import PageBlock
from .page_block_caption import PageBlockCaption
from .voice_note import VoiceNote

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PageBlockVoiceNote(PageBlock):
    """
    A voice note

    :param voice_note: Voice note; may be null
    :param caption: Voice note caption
    """
    __slots__ = ("voice_note", "caption", "_extra", "_client_id", "_type")

    def __init__(self, voice_note: VoiceNote | None = None, caption: PageBlockCaption | None = None):
        self.voice_note = voice_note
        self.caption = caption
        self._type = "pageBlockVoiceNote"