from .page_block import PageBlock

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PageBlockHeader(PageBlock):
    """
    A header

    :param header: Header
    """
    __slots__ = ("header", "_extra", "_client_id", "_type")

    def __init__(self, header = None):
        self.header = header
        self._type = "pageBlockHeader"