from .page_block import PageBlock
from .page_block_caption import PageBlockCaption
from .photo import Photo

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PageBlockPhoto(PageBlock):
    """
    A photo

    :param photo: Photo file; may be null
    :param caption: Photo caption
    :param url: URL that needs to be opened when the photo is clicked
    """
    __slots__ = ("photo", "caption", "url", "_extra", "_client_id", "_type")

    def __init__(self, photo: Photo | None = None, caption: PageBlockCaption | None = None, url: str = ""):
        self.photo = photo
        self.caption = caption
        self.url = url
        self._type = "pageBlockPhoto"