from .page_block import PageBlock

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PageBlockTable(PageBlock):
    """
    A table

    :param caption: Table caption
    :param cells: Table cells
    :param is_bordered: True, if the table is bordered
    :param is_striped: True, if the table is striped
    """
    __slots__ = ("caption", "cells", "is_bordered", "is_striped", "_extra", "_client_id", "_type")

    def __init__(self, caption = None, cells = None, is_bordered = None, is_striped = None):
        self.caption = caption
        self.cells = cells
        self.is_bordered = is_bordered
        self.is_striped = is_striped
        self._type = "pageBlockTable"