from .page_block import PageBlock
from .page_block_list_item import PageBlockListItem
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PageBlockList(PageBlock):
    """
    A list of data blocks

    :param items: The items of the list
    """
    __slots__ = ("items", "_extra", "_client_id", "_type")

    def __init__(self, items: List[PageBlockListItem] | None = None):
        self.items = items
        self._type = "pageBlockList"