from .page_block import PageBlock
from .rich_text import RichText
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PageBlockDetails(PageBlock):
    """
    A collapsible block

    :param header: Always visible heading for the block
    :param page_blocks: Block contents
    :param is_open: True, if the block is open by default
    """
    __slots__ = ("header", "page_blocks", "is_open", "_extra", "_client_id", "_type")

    def __init__(self, header: RichText | None = None, page_blocks: List[PageBlock] | None = None, is_open: bool = False):
        self.header = header
        self.page_blocks = page_blocks
        self.is_open = is_open
        self._type = "pageBlockDetails"