from .paid_reaction_type import PaidReactionType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PaidReactionTypeChat(PaidReactionType):
    """
    A paid reaction on behalf of an owned chat

    :param chat_id: Identifier of the chat
    """
    __slots__ = ("chat_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None):
        self.chat_id = chat_id
        self._type = "paidReactionTypeChat"