from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PaidReactionType(ObjectBase):
    """
    Describes type of paid message reaction

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "PaidReactionType"