from .object_base import ObjectBase
from .passport_element import PassportElement
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PassportElements(ObjectBase):
    """
    Contains information about saved Telegram Passport elements

    :param elements: Telegram Passport elements
    """
    __slots__ = ("elements", "_extra", "_client_id", "_type")

    def __init__(self, elements: List[PassportElement] | None = None):
        self.elements = elements
        self._type = "passportElements"