from .object_base import ObjectBase
from .passport_suitable_element import PassportSuitableElement
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PassportRequiredElement(ObjectBase):
    """
    Contains a description of the required Telegram Passport element that was requested by a service

    :param suitable_elements: List of Telegram Passport elements any of which is enough to provide
    """
    __slots__ = ("suitable_elements", "_extra", "_client_id", "_type")

    def __init__(self, suitable_elements: List[PassportSuitableElement] | None = None):
        self.suitable_elements = suitable_elements
        self._type = "passportRequiredElement"