from .identity_document import IdentityDocument
from .passport_element import PassportElement

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PassportElementDriverLicense(PassportElement):
    """
    A Telegram Passport element containing the user's driver license

    :param driver_license: Driver license
    """
    __slots__ = ("driver_license", "_extra", "_client_id", "_type")

    def __init__(self, driver_license: IdentityDocument | None = None):
        self.driver_license = driver_license
        self._type = "passportElementDriverLicense"