from .passport_element_error_source import PassportElementErrorSource

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PassportElementErrorSourceFiles(PassportElementErrorSource):
    """
    The list of attached files contains an error. The error will be considered resolved when the list of files changes

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "passportElementErrorSourceFiles"