from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PassportAuthorizationForm(ObjectBase):
    """
    Contains information about a Telegram Passport authorization form that was requested

    :param id: Unique identifier of the authorization form
    :param required_elements: Telegram Passport elements that must be provided to complete the form
    :param privacy_policy_url: URL for the privacy policy of the service; may be empty
    """
    __slots__ = ("id", "required_elements", "privacy_policy_url", "_extra", "_client_id", "_type")

    def __init__(self, id = None, required_elements = None, privacy_policy_url = None):
        self.id = id
        self.required_elements = required_elements
        self.privacy_policy_url = privacy_policy_url
        self._type = "passportAuthorizationForm"