from .payment_form_type import PaymentFormType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PaymentFormTypeStars(PaymentFormType):
    """
    The payment form is for a payment in Telegram Stars

    :param star_count: Number of Telegram Stars that will be paid
    """
    __slots__ = ("star_count", "_extra", "_client_id", "_type")

    def __init__(self, star_count: int = 0):
        self.star_count = star_count
        self._type = "paymentFormTypeStars"