from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PaymentProvider(ObjectBase):
    """
    Contains information about a payment provider

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "PaymentProvider"