from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PaymentForm(ObjectBase):
    """
    Contains information about an invoice payment form

    :param id: The payment form identifier
    :param type: Type of the payment form
    :param seller_bot_user_id: User identifier of the seller bot
    :param product_info: Information about the product
    """
    __slots__ = ("id", "type", "seller_bot_user_id", "product_info", "_extra", "_client_id", "_type")

    def __init__(self, id = None, type = None, seller_bot_user_id = None, product_info = None):
        self.id = id
        self.type = type
        self.seller_bot_user_id = seller_bot_user_id
        self.product_info = product_info
        self._type = "paymentForm"