from .payment_form_type import PaymentFormType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PaymentFormTypeRegular(PaymentFormType):
    """
    The payment form is for a regular payment

    :param invoice: Full information about the invoice
    :param payment_provider_user_id: User identifier of the payment provider bot
    :param payment_provider: Information about the payment provider
    :param additional_payment_options: The list of additional payment options
    :param saved_order_info: Saved server-side order information; may be null
    :param saved_credentials: The list of saved payment credentials
    :param can_save_credentials: True, if the user can choose to save credentials
    :param need_password: True, if the user will be able to save credentials, if sets up a 2-step verification password
    """
    __slots__ = ("invoice", "payment_provider_user_id", "payment_provider", "additional_payment_options", "saved_order_info", "saved_credentials", "can_save_credentials", "need_password", "_extra", "_client_id", "_type")

    def __init__(self, invoice = None, payment_provider_user_id = None, payment_provider = None, additional_payment_options = None, saved_order_info = None, saved_credentials = None, can_save_credentials = None, need_password = None):
        self.invoice = invoice
        self.payment_provider_user_id = payment_provider_user_id
        self.payment_provider = payment_provider
        self.additional_payment_options = additional_payment_options
        self.saved_order_info = saved_order_info
        self.saved_credentials = saved_credentials
        self.can_save_credentials = can_save_credentials
        self.need_password = need_password
        self._type = "paymentFormTypeRegular"