from .payment_receipt_type import PaymentReceiptType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PaymentReceiptTypeRegular(PaymentReceiptType):
    """
    The payment was done using a third-party payment provider

    :param payment_provider_user_id: User identifier of the payment provider bot
    :param invoice: Information about the invoice
    :param order_info: Order information; may be null
    :param shipping_option: Chosen shipping option; may be null
    :param credentials_title: Title of the saved credentials chosen by the buyer
    :param tip_amount: The amount of tip chosen by the buyer in the smallest units of the currency
    """
    __slots__ = ("payment_provider_user_id", "invoice", "order_info", "shipping_option", "credentials_title", "tip_amount", "_extra", "_client_id", "_type")

    def __init__(self, payment_provider_user_id = None, invoice = None, order_info = None, shipping_option = None, credentials_title = None, tip_amount = None):
        self.payment_provider_user_id = payment_provider_user_id
        self.invoice = invoice
        self.order_info = order_info
        self.shipping_option = shipping_option
        self.credentials_title = credentials_title
        self.tip_amount = tip_amount
        self._type = "paymentReceiptTypeRegular"