from .date import Date
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PersonalDetails(ObjectBase):
    """
    Contains the user's personal details

    :param first_name: First name of the user written in English; 1-255 characters
    :param middle_name: Middle name of the user written in English; 0-255 characters
    :param last_name: Last name of the user written in English; 1-255 characters
    :param native_first_name: Native first name of the user; 1-255 characters
    :param native_middle_name: Native middle name of the user; 0-255 characters
    :param native_last_name: Native last name of the user; 1-255 characters
    :param birthdate: Birthdate of the user
    :param gender: Gender of the user, "male" or "female"
    :param country_code: A two-letter ISO 3166-1 alpha-2 country code of the user's country
    :param residence_country_code: A two-letter ISO 3166-1 alpha-2 country code of the user's residence country
    """
    __slots__ = ("first_name", "middle_name", "last_name", "native_first_name", "native_middle_name", "native_last_name", "birthdate", "gender", "country_code", "residence_country_code", "_extra", "_client_id", "_type")

    def __init__(self, first_name: str = "", middle_name: str = "", last_name: str = "", native_first_name: str = "", native_middle_name: str = "", native_last_name: str = "", birthdate: Date | None = None, gender: str = "", country_code: str = "", residence_country_code: str = ""):
        self.first_name = first_name
        self.middle_name = middle_name
        self.last_name = last_name
        self.native_first_name = native_first_name
        self.native_middle_name = native_middle_name
        self.native_last_name = native_last_name
        self.birthdate = birthdate
        self.gender = gender
        self.country_code = country_code
        self.residence_country_code = residence_country_code
        self._type = "personalDetails"