from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PinChatMessage(Function):
    """
    Pins a message in a chat. A message can be pinned only if messageProperties.can_be_pinned

    :param chat_id: Identifier of the chat
    :param message_id: Identifier of the new pinned message
    :param disable_notification: Pass true to disable notification about the pinned message. Notifications are always disabled in channels and private chats
    :param only_for_self: Pass true to pin the message only for self; private chats only
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_id", "disable_notification", "only_for_self", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_id = None, disable_notification = None, only_for_self = None):
        self.chat_id = chat_id
        self.message_id = message_id
        self.disable_notification = disable_notification
        self.only_for_self = only_for_self
        self._type = "pinChatMessage"