from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class Point(ObjectBase):
    """
    A point on a Cartesian plane

    :param x: The point's first coordinate
    :param y: The point's second coordinate
    """
    __slots__ = ("x", "y", "_extra", "_client_id", "_type")

    def __init__(self, x = None, y = None):
        self.x = x
        self.y = y
        self._type = "point"