from .poll_type import PollType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PollTypeRegular(PollType):
    """
    A regular poll

    :param allow_multiple_answers: True, if multiple answer options can be chosen simultaneously
    """
    __slots__ = ("allow_multiple_answers", "_extra", "_client_id", "_type")

    def __init__(self, allow_multiple_answers = None):
        self.allow_multiple_answers = allow_multiple_answers
        self._type = "pollTypeRegular"