from .premium_limit_type import PremiumLimitType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PremiumLimitTypeStorySuggestedReactionAreaCount(PremiumLimitType):
    """
    The maximum number of suggested reaction areas on a story

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "premiumLimitTypeStorySuggestedReactionAreaCount"