from .premium_source import PremiumSource

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PremiumSourceStoryFeature(PremiumSource):
    """
    A user tried to use a Premium story feature

    :param feature: The used feature
    """
    __slots__ = ("feature", "_extra", "_client_id", "_type")

    def __init__(self, feature = None):
        self.feature = feature
        self._type = "premiumSourceStoryFeature"