from .premium_feature import PremiumFeature

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PremiumFeatureRealTimeChatTranslation(PremiumFeature):
    """
    Allowed to translate chat messages real-time

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "premiumFeatureRealTimeChatTranslation"