from .premium_feature import PremiumFeature

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PremiumFeatureAccentColor(PremiumFeature):
    """
    The ability to choose accent color for replies and user profile

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "premiumFeatureAccentColor"