from .premium_limit_type import PremiumLimitType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PremiumLimitTypePinnedArchivedChatCount(PremiumLimitType):
    """
    The maximum number of pinned chats in the archive chat list

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "premiumLimitTypePinnedArchivedChatCount"