from .premium_limit_type import PremiumLimitType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PremiumLimitTypeSupergroupCount(PremiumLimitType):
    """
    The maximum number of joined supergroups and channels

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "premiumLimitTypeSupergroupCount"