from .premium_limit_type import PremiumLimitType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PremiumLimitTypeChatFolderCount(PremiumLimitType):
    """
    The maximum number of chat folders

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "premiumLimitTypeChatFolderCount"