from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PremiumGiveawayPaymentOptions(ObjectBase):
    """
    Contains a list of options for creating of Telegram Premium giveaway or manual distribution of Telegram Premium among chat members

    :param options: The list of options
    """
    __slots__ = ("options", "_extra", "_client_id", "_type")

    def __init__(self, options = None):
        self.options = options
        self._type = "premiumGiveawayPaymentOptions"