from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ProcessChatFolderNewChats(Function):
    """
    Process new chats added to a shareable chat folder by its owner

    :param chat_folder_id: Chat folder identifier
    :param added_chat_ids: Identifiers of the new chats, which are added to the chat folder. The chats are automatically joined if they aren't joined yet
    :return: :class:`Ok`
    """
    __slots__ = ("chat_folder_id", "added_chat_ids", "_extra", "_client_id", "_type")

    def __init__(self, chat_folder_id = None, added_chat_ids = None):
        self.chat_folder_id = chat_folder_id
        self.added_chat_ids = added_chat_ids
        self._type = "processChatFolderNewChats"