from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ProfileAccentColor(ObjectBase):
    """
    Contains information about supported accent color for user profile photo background

    :param id: Profile accent color identifier
    :param light_theme_colors: Accent colors expected to be used in light themes
    :param dark_theme_colors: Accent colors expected to be used in dark themes
    :param min_supergroup_chat_boost_level: The minimum chat boost level required to use the color in a supergroup chat
    :param min_channel_chat_boost_level: The minimum chat boost level required to use the color in a channel chat
    """
    __slots__ = ("id", "light_theme_colors", "dark_theme_colors", "min_supergroup_chat_boost_level", "min_channel_chat_boost_level", "_extra", "_client_id", "_type")

    def __init__(self, id = None, light_theme_colors = None, dark_theme_colors = None, min_supergroup_chat_boost_level = None, min_channel_chat_boost_level = None):
        self.id = id
        self.light_theme_colors = light_theme_colors
        self.dark_theme_colors = dark_theme_colors
        self.min_supergroup_chat_boost_level = min_supergroup_chat_boost_level
        self.min_channel_chat_boost_level = min_channel_chat_boost_level
        self._type = "profileAccentColor"