from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ProfileAccentColors(ObjectBase):
    """
    Contains information about supported accent colors for user profile photo background in RGB format

    :param palette_colors: The list of 1-2 colors in RGB format, describing the colors, as expected to be shown in the color palette settings
    :param background_colors: The list of 1-2 colors in RGB format, describing the colors, as expected to be used for the profile photo background
    :param story_colors: The list of 2 colors in RGB format, describing the colors of the gradient to be used for the unread active story indicator around profile photo
    """
    __slots__ = ("palette_colors", "background_colors", "story_colors", "_extra", "_client_id", "_type")

    def __init__(self, palette_colors = None, background_colors = None, story_colors = None):
        self.palette_colors = palette_colors
        self.background_colors = background_colors
        self.story_colors = story_colors
        self._type = "profileAccentColors"