from .object_base import ObjectBase
from .proxy_type import ProxyType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class Proxy(ObjectBase):
    """
    Contains information about a proxy server

    :param id: Unique identifier of the proxy
    :param server: Proxy server domain or IP address
    :param port: Proxy server port
    :param last_used_date: Point in time (Unix timestamp) when the proxy was last used; 0 if never
    :param is_enabled: True, if the proxy is enabled now
    :param type: Type of the proxy
    """
    __slots__ = ("id", "server", "port", "last_used_date", "is_enabled", "type", "_extra", "_client_id", "_type")

    def __init__(self, id: int = 0, server: str = "", port: int = 0, last_used_date: int = 0, is_enabled: bool = False, type: ProxyType | None = None):
        self.id = id
        self.server = server
        self.port = port
        self.last_used_date = last_used_date
        self.is_enabled = is_enabled
        self.type = type
        self._type = "proxy"