from .push_message_content import PushMessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PushMessageContentRecurringPayment(PushMessageContent):
    """
    A new recurring payment was made by the current user

    :param amount: The paid amount
    """
    __slots__ = ("amount", "_extra", "_client_id", "_type")

    def __init__(self, amount: str = ""):
        self.amount = amount
        self._type = "pushMessageContentRecurringPayment"