from .push_message_content import PushMessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PushMessageContentPoll(PushMessageContent):
    """
    A message with a poll

    :param question: Poll question
    :param is_regular: True, if the poll is regular and not in quiz mode
    :param is_pinned: True, if the message is a pinned message with the specified content
    """
    __slots__ = ("question", "is_regular", "is_pinned", "_extra", "_client_id", "_type")

    def __init__(self, question = None, is_regular = None, is_pinned = None):
        self.question = question
        self.is_regular = is_regular
        self.is_pinned = is_pinned
        self._type = "pushMessageContentPoll"