from .push_message_content import PushMessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PushMessageContentGame(PushMessageContent):
    """
    A message with a game

    :param title: Game title, empty for pinned game message
    :param is_pinned: True, if the message is a pinned message with the specified content
    """
    __slots__ = ("title", "is_pinned", "_extra", "_client_id", "_type")

    def __init__(self, title = None, is_pinned = None):
        self.title = title
        self.is_pinned = is_pinned
        self._type = "pushMessageContentGame"