from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PushMessageContent(ObjectBase):
    """
    Contains content of a push message notification

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "PushMessageContent"