from .animation import Animation
from .push_message_content import PushMessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PushMessageContentAnimation(PushMessageContent):
    """
    An animation message (GIF-style).

    :param animation: Message content; may be null
    :param caption: Animation caption
    :param is_pinned: True, if the message is a pinned message with the specified content
    """
    __slots__ = ("animation", "caption", "is_pinned", "_extra", "_client_id", "_type")

    def __init__(self, animation: Animation | None = None, caption: str = "", is_pinned: bool = False):
        self.animation = animation
        self.caption = caption
        self.is_pinned = is_pinned
        self._type = "pushMessageContentAnimation"