from .push_message_content import PushMessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PushMessageContentPaidMedia(PushMessageContent):
    """
    A message with paid media

    :param star_count: Number of Telegram Stars needed to buy access to the media in the message; 0 for pinned message
    :param is_pinned: True, if the message is a pinned message with the specified content
    """
    __slots__ = ("star_count", "is_pinned", "_extra", "_client_id", "_type")

    def __init__(self, star_count = None, is_pinned = None):
        self.star_count = star_count
        self.is_pinned = is_pinned
        self._type = "pushMessageContentPaidMedia"