from .push_message_content import PushMessageContent

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class PushMessageContentMediaAlbum(PushMessageContent):
    """
    A media album

    :param total_count: Number of messages in the album
    :param has_photos: True, if the album has at least one photo
    :param has_videos: True, if the album has at least one video file
    :param has_audios: True, if the album has at least one audio file
    :param has_documents: True, if the album has at least one document
    """
    __slots__ = ("total_count", "has_photos", "has_videos", "has_audios", "has_documents", "_extra", "_client_id", "_type")

    def __init__(self, total_count = None, has_photos = None, has_videos = None, has_audios = None, has_documents = None):
        self.total_count = total_count
        self.has_photos = has_photos
        self.has_videos = has_videos
        self.has_audios = has_audios
        self.has_documents = has_documents
        self._type = "pushMessageContentMediaAlbum"