from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class QuickReplyMessages(ObjectBase):
    """
    Contains a list of quick reply messages

    :param messages: List of quick reply messages; messages may be null
    """
    __slots__ = ("messages", "_extra", "_client_id", "_type")

    def __init__(self, messages = None):
        self.messages = messages
        self._type = "quickReplyMessages"