from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class RateSpeechRecognition(Function[Ok]):
    """
    Rates recognized speech in a video note or a voice note message

    :param chat_id: Identifier of the chat to which the message belongs
    :param message_id: Identifier of the message
    :param is_good: Pass true if the speech recognition is good
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_id", "is_good", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, message_id: int = 0, is_good: bool = False):
        self.chat_id = chat_id
        self.message_id = message_id
        self.is_good = is_good
        self._type = "rateSpeechRecognition"