from .function import Function

from .data import Data

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ReadFilePart(Function[Data]):
    """
    Reads a part of a file from the TDLib file cache and returns read bytes. This method is intended to be used only if the application has no direct access to TDLib's file system, because it is usually slower than a direct read from the file

    :param file_id: Identifier of the file. The file must be located in the TDLib file cache
    :param offset: The offset from which to read the file
    :param count: Number of bytes to read. An error will be returned if there are not enough bytes available in the file from the specified position. Pass 0 to read all available data from the specified position
    :return: :class:`Data`
    """
    __slots__ = ("file_id", "offset", "count", "_extra", "_client_id", "_type")

    def __init__(self, file_id: int = 0, offset: int = 0, count: int = 0):
        self.file_id = file_id
        self.offset = offset
        self.count = count
        self._type = "readFilePart"