from .function import Function

from .chat_list import ChatList
from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ReadChatList(Function[Ok]):
    """
    Traverse all chats in a chat list and marks all messages in the chats as read

    :param chat_list: Chat list in which to mark all chats as read
    :return: :class:`Ok`
    """
    __slots__ = ("chat_list", "_extra", "_client_id", "_type")

    def __init__(self, chat_list: ChatList | None = None):
        self.chat_list = chat_list
        self._type = "readChatList"