from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ReadAllMessageThreadReactions(Function):
    """
    Marks all reactions in a forum topic as read

    :param chat_id: Chat identifier
    :param message_thread_id: Message thread identifier in which reactions are marked as read
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_thread_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_thread_id = None):
        self.chat_id = chat_id
        self.message_thread_id = message_thread_id
        self._type = "readAllMessageThreadReactions"