from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class RecognizeSpeech(Function):
    """
    Recognizes speech in a video note or a voice note message

    :param chat_id: Identifier of the chat to which the message belongs
    :param message_id: Identifier of the message. Use messageProperties.can_recognize_speech to check whether the message is suitable
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_id = None):
        self.chat_id = chat_id
        self.message_id = message_id
        self._type = "recognizeSpeech"