from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class RemoveRecentlyFoundChat(Function[Ok]):
    """
    Removes a chat from the list of recently found chats

    :param chat_id: Identifier of the chat to be removed
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0):
        self.chat_id = chat_id
        self._type = "removeRecentlyFoundChat"