from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class RemoveSearchedForTag(Function[Ok]):
    """
    Removes a hashtag or a cashtag from the list of recently searched for hashtags or cashtags

    :param tag: Hashtag or cashtag to delete
    :return: :class:`Ok`
    """
    __slots__ = ("tag", "_extra", "_client_id", "_type")

    def __init__(self, tag: str = ""):
        self.tag = tag
        self._type = "removeSearchedForTag"