from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class RemoveContacts(Function):
    """
    Removes users from the contact list

    :param user_ids: Identifiers of users to be deleted
    :return: :class:`Ok`
    """
    __slots__ = ("user_ids", "_extra", "_client_id", "_type")

    def __init__(self, user_ids = None):
        self.user_ids = user_ids
        self._type = "removeContacts"