from .function import Function

from .ok import Ok
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ReorderSupergroupActiveUsernames(Function[Ok]):
    """
    Changes order of active usernames of a supergroup or channel, requires owner privileges in the supergroup or channel

    :param supergroup_id: Identifier of the supergroup or channel
    :param usernames: The new order of active usernames. All currently active usernames must be specified
    :return: :class:`Ok`
    """
    __slots__ = ("supergroup_id", "usernames", "_extra", "_client_id", "_type")

    def __init__(self, supergroup_id: int = 0, usernames: List[str] | None = None):
        self.supergroup_id = supergroup_id
        self.usernames = usernames
        self._type = "reorderSupergroupActiveUsernames"