from .function import Function

from .ok import Ok
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ReorderActiveUsernames(Function[Ok]):
    """
    Changes order of active usernames of the current user

    :param usernames: The new order of active usernames. All currently active usernames must be specified
    :return: :class:`Ok`
    """
    __slots__ = ("usernames", "_extra", "_client_id", "_type")

    def __init__(self, usernames: List[str] | None = None):
        self.usernames = usernames
        self._type = "reorderActiveUsernames"