from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ReorderChatFolders(Function):
    """
    Changes the order of chat folders

    :param chat_folder_ids: Identifiers of chat folders in the new correct order
    :param main_chat_list_position: Position of the main chat list among chat folders, 0-based. Can be non-zero only for Premium users
    :return: :class:`Ok`
    """
    __slots__ = ("chat_folder_ids", "main_chat_list_position", "_extra", "_client_id", "_type")

    def __init__(self, chat_folder_ids = None, main_chat_list_position = None):
        self.chat_folder_ids = chat_folder_ids
        self.main_chat_list_position = main_chat_list_position
        self._type = "reorderChatFolders"