from .inline_keyboard_button import InlineKeyboardButton
from .reply_markup import ReplyMarkup
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ReplyMarkupInlineKeyboard(ReplyMarkup):
    """
    Contains an inline keyboard layout

    :param rows: A list of rows of inline keyboard buttons
    """
    __slots__ = ("rows", "_extra", "_client_id", "_type")

    def __init__(self, rows: List[List[InlineKeyboardButton]] | None = None):
        self.rows = rows
        self._type = "replyMarkupInlineKeyboard"