from .function import Function

from .chat_invite_link import ChatInviteLink

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ReplacePrimaryChatInviteLink(Function[ChatInviteLink]):
    """
    Replaces current primary invite link for a chat with a new primary invite link. Available for basic groups, supergroups, and channels. Requires administrator privileges and can_invite_users right

    :param chat_id: Chat identifier
    :return: :class:`ChatInviteLink`
    """
    __slots__ = ("chat_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0):
        self.chat_id = chat_id
        self._type = "replacePrimaryChatInviteLink"