from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ReportMessageReactions(Function):
    """
    Reports reactions set on a message to the Telegram moderators. Reactions on a message can be reported only if messageProperties.can_report_reactions

    :param chat_id: Chat identifier
    :param message_id: Message identifier
    :param sender_id: Identifier of the sender, which added the reaction
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_id", "sender_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_id = None, sender_id = None):
        self.chat_id = chat_id
        self.message_id = message_id
        self.sender_id = sender_id
        self._type = "reportMessageReactions"