from .report_reason import ReportReason

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ReportReasonSpam(ReportReason):
    """
    The chat contains spam messages

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "reportReasonSpam"