from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ReportOption(ObjectBase):
    """
    Describes an option to report an entity to Telegram

    :param id: Unique identifier of the option
    :param text: Text of the option
    """
    __slots__ = ("id", "text", "_extra", "_client_id", "_type")

    def __init__(self, id: bytes = b"", text: str = ""):
        self.id = id
        self.text = text
        self._type = "reportOption"