from .function import Function

from .ok import Ok
from .report_reason import ReportReason

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ReportChatPhoto(Function[Ok]):
    """
    Reports a chat photo to the Telegram moderators. A chat photo can be reported only if chat.can_be_reported

    :param chat_id: Chat identifier
    :param file_id: Identifier of the photo to report. Only full photos from chatPhoto can be reported
    :param reason: The reason for reporting the chat photo
    :param text: Additional report details; 0-1024 characters
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "file_id", "reason", "text", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, file_id: int = 0, reason: ReportReason | None = None, text: str = ""):
        self.chat_id = chat_id
        self.file_id = file_id
        self.reason = reason
        self.text = text
        self._type = "reportChatPhoto"