from .function import Function

from .reset_password_result_declined import ResetPasswordResultDeclined
from .reset_password_result_ok import ResetPasswordResultOk
from .reset_password_result_pending import ResetPasswordResultPending

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ResetPassword(Function[ResetPasswordResultOk | ResetPasswordResultPending | ResetPasswordResultDeclined]):
    """
    Removes 2-step verification password without previous password and access to recovery email address. The password can't be reset immediately and the request needs to be repeated after the specified time

    :return: :class:`ResetPasswordResultOk | ResetPasswordResultPending | ResetPasswordResultDeclined`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "resetPassword"