from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ResetPassword(Function):
    """
    Removes 2-step verification password without previous password and access to recovery email address. The password can't be reset immediately and the request needs to be repeated after the specified time

    :return: :class:`ResetPasswordResultOk | ResetPasswordResultPending | ResetPasswordResultDeclined`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "resetPassword"