from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ResendAuthenticationCode(Function):
    """
    Resends an authentication code to the user. Works only when the current authorization state is authorizationStateWaitCode, the next_code_type of the result is not null and the server-specified timeout has passed, or when the current authorization state is authorizationStateWaitEmailCode

    :param reason: Reason of code resending; pass null if unknown
    :return: :class:`Ok`
    """
    __slots__ = ("reason", "_extra", "_client_id", "_type")

    def __init__(self, reason = None):
        self.reason = reason
        self._type = "resendAuthenticationCode"