from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ResetInstalledBackgrounds(Function[Ok]):
    """
    Resets list of installed backgrounds to its default value

    :return: :class:`Ok`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "resetInstalledBackgrounds"