from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ResendLoginEmailAddressCode(Function):
    """
    Resends the login email address verification code

    :return: :class:`EmailAddressAuthenticationCodeInfo`
    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "resendLoginEmailAddressCode"