from .revenue_withdrawal_state import RevenueWithdrawalState

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class RevenueWithdrawalStateFailed(RevenueWithdrawalState):
    """
    Withdrawal failed

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "revenueWithdrawalStateFailed"