from .rich_text import RichText

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class RichTextPhoneNumber(RichText):
    """
    A rich text phone number

    :param text: Text
    :param phone_number: Phone number
    """
    __slots__ = ("text", "phone_number", "_extra", "_client_id", "_type")

    def __init__(self, text: RichText | None = None, phone_number: str = ""):
        self.text = text
        self.phone_number = phone_number
        self._type = "richTextPhoneNumber"