from .rich_text import RichText

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class RichTextStrikethrough(RichText):
    """
    A strikethrough rich text

    :param text: Text
    """
    __slots__ = ("text", "_extra", "_client_id", "_type")

    def __init__(self, text: RichText | None = None):
        self.text = text
        self._type = "richTextStrikethrough"