from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SavedMessagesTopic(ObjectBase):
    """
    Contains information about a Saved Messages topic

    :param id: Unique topic identifier
    :param type: Type of the topic
    :param is_pinned: True, if the topic is pinned
    :param order: A parameter used to determine order of the topic in the topic list. Topics must be sorted by the order in descending order
    :param last_message: Last message in the topic; may be null if none or unknown
    :param draft_message: A draft of a message in the topic; may be null if none
    """
    __slots__ = ("id", "type", "is_pinned", "order", "last_message", "draft_message", "_extra", "_client_id", "_type")

    def __init__(self, id = None, type = None, is_pinned = None, order = None, last_message = None, draft_message = None):
        self.id = id
        self.type = type
        self.is_pinned = is_pinned
        self.order = order
        self.last_message = last_message
        self.draft_message = draft_message
        self._type = "savedMessagesTopic"