from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SavedMessagesTopicType(ObjectBase):
    """
    Describes type of Saved Messages topic

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "SavedMessagesTopicType"