from .saved_messages_topic_type import SavedMessagesTopicType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SavedMessagesTopicTypeMyNotes(SavedMessagesTopicType):
    """
    Topic containing messages sent by the current user of forwarded from an unknown chat

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "savedMessagesTopicTypeMyNotes"