from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SearchChatAffiliateProgram(Function):
    """
    Searches a chat with an affiliate program. Returns the chat if found and the program is active

    :param username: Username of the chat
    :param referrer: The referrer from an internalLinkTypeChatAffiliateProgram link
    :return: :class:`Chat`
    """
    __slots__ = ("username", "referrer", "_extra", "_client_id", "_type")

    def __init__(self, username = None, referrer = None):
        self.username = username
        self.referrer = referrer
        self._type = "searchChatAffiliateProgram"