from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SearchHashtags(Function):
    """
    Searches for recently used hashtags by their prefix

    :param prefix: Hashtag prefix to search for
    :param limit: The maximum number of hashtags to be returned
    :return: :class:`Hashtags`
    """
    __slots__ = ("prefix", "limit", "_extra", "_client_id", "_type")

    def __init__(self, prefix = None, limit = None):
        self.prefix = prefix
        self.limit = limit
        self._type = "searchHashtags"