from .search_messages_filter import SearchMessagesFilter

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SearchMessagesFilterUnreadMention(SearchMessagesFilter):
    """
    Returns only messages with unread mentions of the current user, or messages that are replies to their messages. When using this filter the results can't be additionally filtered by a query, a message thread or by the sending user

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "searchMessagesFilterUnreadMention"