from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SearchMessagesChatTypeFilter(ObjectBase):
    """
    Represents a filter for type of the chats in which to search messages

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "SearchMessagesChatTypeFilter"