from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SearchQuote(Function):
    """
    Searches for a given quote in a text. Returns found quote start position in UTF-16 code units. Returns a 404 error if the quote is not found. Can be called synchronously

    :param text: Text in which to search for the quote
    :param quote: Quote to search for
    :param quote_position: Approximate quote position in UTF-16 code units
    :return: :class:`FoundPosition`
    """
    __slots__ = ("text", "quote", "quote_position", "_extra", "_client_id", "_type")

    def __init__(self, text = None, quote = None, quote_position = None):
        self.text = text
        self.quote = quote
        self.quote_position = quote_position
        self._type = "searchQuote"