from .search_messages_chat_type_filter import SearchMessagesChatTypeFilter

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SearchMessagesChatTypeFilterChannel(SearchMessagesChatTypeFilter):
    """
    Returns only messages in channel chats

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "searchMessagesChatTypeFilterChannel"