from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SearchPublicMessagesByTag(Function):
    """
    Searches for public channel posts containing the given hashtag or cashtag. For optimal performance, the number of returned messages is chosen by TDLib and can be smaller than the specified limit

    :param tag: Hashtag or cashtag to search for
    :param offset: Offset of the first entry to return as received from the previous request; use empty string to get the first chunk of results
    :param limit: The maximum number of messages to be returned; up to 100. For optimal performance, the number of returned messages is chosen by TDLib and can be smaller than the specified limit
    :return: :class:`FoundMessages`
    """
    __slots__ = ("tag", "offset", "limit", "_extra", "_client_id", "_type")

    def __init__(self, tag = None, offset = None, limit = None):
        self.tag = tag
        self.offset = offset
        self.limit = limit
        self._type = "searchPublicMessagesByTag"