from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SearchChatRecentLocationMessages(Function):
    """
    Returns information about the recent locations of chat members that were sent to the chat. Returns up to 1 location message per user

    :param chat_id: Chat identifier
    :param limit: The maximum number of messages to be returned
    :return: :class:`Messages`
    """
    __slots__ = ("chat_id", "limit", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, limit = None):
        self.chat_id = chat_id
        self.limit = limit
        self._type = "searchChatRecentLocationMessages"