from .function import Function

from .authentication_code_info import AuthenticationCodeInfo
from .phone_number_authentication_settings import PhoneNumberAuthenticationSettings
from .phone_number_code_type import PhoneNumberCodeType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SendPhoneNumberCode(Function[AuthenticationCodeInfo]):
    """
    Sends a code to the specified phone number. Aborts previous phone number verification if there was one. On success, returns information about the sent code

    :param phone_number: The phone number, in international format
    :param settings: Settings for the authentication of the user's phone number; pass null to use default settings
    :param type: Type of the request for which the code is sent
    :return: :class:`AuthenticationCodeInfo`
    """
    __slots__ = ("phone_number", "settings", "type", "_extra", "_client_id", "_type")

    def __init__(self, phone_number: str = "", settings: PhoneNumberAuthenticationSettings | None = None, type: PhoneNumberCodeType | None = None):
        self.phone_number = phone_number
        self.settings = settings
        self.type = type
        self._type = "sendPhoneNumberCode"