from .function import Function

from .input_message_content import InputMessageContent
from .input_message_reply_to import InputMessageReplyTo
from .message import Message
from .message_send_options import MessageSendOptions
from .reply_markup import ReplyMarkup

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SendMessage(Function[Message]):
    """
    Sends a message. Returns the sent message

    :param chat_id: Target chat
    :param message_thread_id: If not 0, the message thread identifier in which the message will be sent
    :param reply_to: Information about the message or story to be replied; pass null if none
    :param options: Options to be used to send the message; pass null to use default options
    :param reply_markup: Markup for replying to the message; pass null if none; for bots only
    :param input_message_content: The content of the message to be sent
    :return: :class:`Message`
    """
    __slots__ = ("chat_id", "message_thread_id", "reply_to", "options", "reply_markup", "input_message_content", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, message_thread_id: int = 0, reply_to: InputMessageReplyTo | None = None, options: MessageSendOptions | None = None, reply_markup: ReplyMarkup | None = None, input_message_content: InputMessageContent | None = None):
        self.chat_id = chat_id
        self.message_thread_id = message_thread_id
        self.reply_to = reply_to
        self.options = options
        self.reply_markup = reply_markup
        self.input_message_content = input_message_content
        self._type = "sendMessage"