from .function import Function

from .email_address_authentication_code_info import EmailAddressAuthenticationCodeInfo

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SendEmailAddressVerificationCode(Function[EmailAddressAuthenticationCodeInfo]):
    """
    Sends a code to verify an email address to be added to a user's Telegram Passport

    :param email_address: Email address
    :return: :class:`EmailAddressAuthenticationCodeInfo`
    """
    __slots__ = ("email_address", "_extra", "_client_id", "_type")

    def __init__(self, email_address: str = ""):
        self.email_address = email_address
        self._type = "sendEmailAddressVerificationCode"