from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SendWebAppCustomRequest(Function):
    """
    Sends a custom request from a Web App

    :param bot_user_id: Identifier of the bot
    :param method: The method name
    :param parameters: JSON-serialized method parameters
    :return: :class:`CustomRequestResult`
    """
    __slots__ = ("bot_user_id", "method", "parameters", "_extra", "_client_id", "_type")

    def __init__(self, bot_user_id = None, method = None, parameters = None):
        self.bot_user_id = bot_user_id
        self.method = method
        self.parameters = parameters
        self._type = "sendWebAppCustomRequest"