from .function import Function

from .call_problem import CallProblem
from .ok import Ok
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SendCallRating(Function[Ok]):
    """
    Sends a call rating

    :param call_id: Call identifier
    :param rating: Call rating; 1-5
    :param comment: An optional user comment if the rating is less than 5
    :param problems: List of the exact types of problems with the call, specified by the user
    :return: :class:`Ok`
    """
    __slots__ = ("call_id", "rating", "comment", "problems", "_extra", "_client_id", "_type")

    def __init__(self, call_id: int = 0, rating: int = 0, comment: str = "", problems: List[CallProblem] | None = None):
        self.call_id = call_id
        self.rating = rating
        self.comment = comment
        self.problems = problems
        self._type = "sendCallRating"