from .function import Function

from .input_file import InputFile
from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SendCallLog(Function[Ok]):
    """
    Sends log file for a call to Telegram servers

    :param call_id: Call identifier
    :param log_file: Call log file. Only inputFileLocal and inputFileGenerated are supported
    :return: :class:`Ok`
    """
    __slots__ = ("call_id", "log_file", "_extra", "_client_id", "_type")

    def __init__(self, call_id: int = 0, log_file: InputFile | None = None):
        self.call_id = call_id
        self.log_file = log_file
        self._type = "sendCallLog"