from .sent_gift import SentGift
from .upgraded_gift import UpgradedGift

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SentGiftUpgraded(SentGift):
    """
    Upgraded gift

    :param gift: The gift
    """
    __slots__ = ("gift", "_extra", "_client_id", "_type")

    def __init__(self, gift: UpgradedGift | None = None):
        self.gift = gift
        self._type = "sentGiftUpgraded"