from .session_type import SessionType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SessionTypeOpera(SessionType):
    """
    The session is running on the Opera browser

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "sessionTypeOpera"