from .session_type import SessionType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SessionTypeLinux(SessionType):
    """
    The session is running on a Linux device

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "sessionTypeLinux"