from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class Sessions(ObjectBase):
    """
    Contains a list of sessions

    :param sessions: List of sessions
    :param inactive_session_ttl_days: Number of days of inactivity before sessions will automatically be terminated; 1-366 days
    """
    __slots__ = ("sessions", "inactive_session_ttl_days", "_extra", "_client_id", "_type")

    def __init__(self, sessions = None, inactive_session_ttl_days = None):
        self.sessions = sessions
        self.inactive_session_ttl_days = inactive_session_ttl_days
        self._type = "sessions"