from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetChatDescription(Function[Ok]):
    """
    Changes information about a chat. Available for basic groups, supergroups, and channels. Requires can_change_info member right

    :param chat_id: Identifier of the chat
    :param description: Changes information about a chat. Available for basic groups, supergroups, and channels. Requires can_change_info member right
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "description", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, description: str = ""):
        self.chat_id = chat_id
        self.description = description
        self._type = "setChatDescription"