from .function import Function

from .background import Background
from .background_type import BackgroundType
from .input_background import InputBackground

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetDefaultBackground(Function[Background]):
    """
    Sets default background for chats; adds the background to the list of installed backgrounds

    :param background: The input background to use; pass null to create a new filled background
    :param type: Background type; pass null to use the default type of the remote background; backgroundTypeChatTheme isn't supported
    :param for_dark_theme: Pass true if the background is set for a dark theme
    :return: :class:`Background`
    """
    __slots__ = ("background", "type", "for_dark_theme", "_extra", "_client_id", "_type")

    def __init__(self, background: InputBackground | None = None, type: BackgroundType | None = None, for_dark_theme: bool = False):
        self.background = background
        self.type = type
        self.for_dark_theme = for_dark_theme
        self._type = "setDefaultBackground"