from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetBotUpdatesStatus(Function[Ok]):
    """
    Informs the server about the number of pending bot updates if they haven't been processed for a long time; for bots only

    :param pending_update_count: The number of pending updates
    :param error_message: The last error message
    :return: :class:`Ok`
    """
    __slots__ = ("pending_update_count", "error_message", "_extra", "_client_id", "_type")

    def __init__(self, pending_update_count: int = 0, error_message: str = ""):
        self.pending_update_count = pending_update_count
        self.error_message = error_message
        self._type = "setBotUpdatesStatus"