from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetBio(Function):
    """
    Changes the bio of the current user

    :param bio: The new value of the user bio; 0-getOption("bio_length_max") characters without line feeds
    :return: :class:`Ok`
    """
    __slots__ = ("bio", "_extra", "_client_id", "_type")

    def __init__(self, bio = None):
        self.bio = bio
        self._type = "setBio"