from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetScopeNotificationSettings(Function):
    """
    Changes notification settings for chats of a given type

    :param scope: Types of chats for which to change the notification settings
    :param notification_settings: The new notification settings for the given scope
    :return: :class:`Ok`
    """
    __slots__ = ("scope", "notification_settings", "_extra", "_client_id", "_type")

    def __init__(self, scope = None, notification_settings = None):
        self.scope = scope
        self.notification_settings = notification_settings
        self._type = "setScopeNotificationSettings"