from .function import Function

from .ok import Ok
from .reaction_type import ReactionType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetSavedMessagesTagLabel(Function[Ok]):
    """
    Changes label of a Saved Messages tag; for Telegram Premium users only

    :param tag: The tag which label will be changed
    :param label: New label for the tag; 0-12 characters
    :return: :class:`Ok`
    """
    __slots__ = ("tag", "label", "_extra", "_client_id", "_type")

    def __init__(self, tag: ReactionType | None = None, label: str = ""):
        self.tag = tag
        self.label = label
        self._type = "setSavedMessagesTagLabel"