from .function import Function

from .message_sender import MessageSender
from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetGroupCallParticipantVolumeLevel(Function[Ok]):
    """
    Changes volume level of a participant of an active group call. If the current user can manage the group call or is the owner of the group call, then the participant's volume level will be changed for all users with the default volume level

    :param group_call_id: Group call identifier
    :param participant_id: Participant identifier
    :param volume_level: New participant's volume level; 1-20000 in hundreds of percents
    :return: :class:`Ok`
    """
    __slots__ = ("group_call_id", "participant_id", "volume_level", "_extra", "_client_id", "_type")

    def __init__(self, group_call_id: int = 0, participant_id: MessageSender | None = None, volume_level: int = 0):
        self.group_call_id = group_call_id
        self.participant_id = participant_id
        self.volume_level = volume_level
        self._type = "setGroupCallParticipantVolumeLevel"