from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetUserPrivacySettingRules(Function):
    """
    Changes user privacy settings

    :param setting: The privacy setting
    :param rules: The new privacy rules
    :return: :class:`Ok`
    """
    __slots__ = ("setting", "rules", "_extra", "_client_id", "_type")

    def __init__(self, setting = None, rules = None):
        self.setting = setting
        self.rules = rules
        self._type = "setUserPrivacySettingRules"