from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetBusinessAccountBio(Function[Ok]):
    """
    Changes the bio of a business account; for bots only

    :param business_connection_id: Unique identifier of business connection
    :param bio: The new value of the bio; 0-getOption("bio_length_max") characters without line feeds
    :return: :class:`Ok`
    """
    __slots__ = ("business_connection_id", "bio", "_extra", "_client_id", "_type")

    def __init__(self, business_connection_id: str = "", bio: str = ""):
        self.business_connection_id = business_connection_id
        self.bio = bio
        self._type = "setBusinessAccountBio"