from .function import Function

from .password_state import PasswordState

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetPassword(Function[PasswordState]):
    """
    Changes the 2-step verification password for the current user. If a new recovery email address is specified, then the change will not be applied until the new recovery email address is confirmed

    :param old_password: Previous 2-step verification password of the user
    :param new_password: New 2-step verification password of the user; may be empty to remove the password
    :param new_hint: New password hint; may be empty
    :param set_recovery_email_address: Pass true to change also the recovery email address
    :param new_recovery_email_address: New recovery email address; may be empty
    :return: :class:`PasswordState`
    """
    __slots__ = ("old_password", "new_password", "new_hint", "set_recovery_email_address", "new_recovery_email_address", "_extra", "_client_id", "_type")

    def __init__(self, old_password: str = "", new_password: str = "", new_hint: str = "", set_recovery_email_address: bool = False, new_recovery_email_address: str = ""):
        self.old_password = old_password
        self.new_password = new_password
        self.new_hint = new_hint
        self.set_recovery_email_address = set_recovery_email_address
        self.new_recovery_email_address = new_recovery_email_address
        self._type = "setPassword"