from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetForumTopicNotificationSettings(Function):
    """
    Changes the notification settings of a forum topic

    :param chat_id: Chat identifier
    :param message_thread_id: Message thread identifier of the forum topic
    :param notification_settings: New notification settings for the forum topic. If the topic is muted for more than 366 days, it is considered to be muted forever
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_thread_id", "notification_settings", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_thread_id = None, notification_settings = None):
        self.chat_id = chat_id
        self.message_thread_id = message_thread_id
        self.notification_settings = notification_settings
        self._type = "setForumTopicNotificationSettings"