from .function import Function

from .gift_settings import GiftSettings
from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetBusinessAccountGiftSettings(Function[Ok]):
    """
    Changes settings for gift receiving of a business account; for bots only

    :param business_connection_id: Unique identifier of business connection
    :param settings: The new settings
    :return: :class:`Ok`
    """
    __slots__ = ("business_connection_id", "settings", "_extra", "_client_id", "_type")

    def __init__(self, business_connection_id: str = "", settings: GiftSettings | None = None):
        self.business_connection_id = business_connection_id
        self.settings = settings
        self._type = "setBusinessAccountGiftSettings"