from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetFeedbackChatTopicIsMarkedAsUnread(Function):
    """
    Changes the marked as unread state of a feedback chat topic

    :param chat_id: Chat identifier of the feedback group
    :param topic_id: Topic identifier
    :param is_marked_as_unread: New value of is_marked_as_unread
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "topic_id", "is_marked_as_unread", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, topic_id = None, is_marked_as_unread = None):
        self.chat_id = chat_id
        self.topic_id = topic_id
        self.is_marked_as_unread = is_marked_as_unread
        self._type = "setFeedbackChatTopicIsMarkedAsUnread"