from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetVideoChatDefaultParticipant(Function):
    """
    Changes default participant identifier, on whose behalf a video chat in the chat will be joined

    :param chat_id: Chat identifier
    :param default_participant_id: Default group call participant identifier to join the video chats
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "default_participant_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, default_participant_id = None):
        self.chat_id = chat_id
        self.default_participant_id = default_participant_id
        self._type = "setVideoChatDefaultParticipant"