from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetPassportElement(Function):
    """
    Adds an element to the user's Telegram Passport. May return an error with a message "PHONE_VERIFICATION_NEEDED" or "EMAIL_VERIFICATION_NEEDED" if the chosen phone number or the chosen email address must be verified first

    :param element: Input Telegram Passport element
    :param password: The 2-step verification password of the current user
    :return: :class:`PassportElementPersonalDetails | PassportElementPassport | PassportElementDriverLicense | PassportElementIdentityCard | PassportElementInternalPassport | PassportElementAddress | PassportElementUtilityBill | PassportElementBankStatement | PassportElementRentalAgreement | PassportElementPassportRegistration | PassportElementTemporaryRegistration | PassportElementPhoneNumber | PassportElementEmailAddress`
    """
    __slots__ = ("element", "password", "_extra", "_client_id", "_type")

    def __init__(self, element = None, password = None):
        self.element = element
        self.password = password
        self._type = "setPassportElement"