from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetDatabaseEncryptionKey(Function):
    """
    Changes the database encryption key. Usually the encryption key is never changed and is stored in some OS keychain

    :param new_encryption_key: New encryption key
    :return: :class:`Ok`
    """
    __slots__ = ("new_encryption_key", "_extra", "_client_id", "_type")

    def __init__(self, new_encryption_key = None):
        self.new_encryption_key = new_encryption_key
        self._type = "setDatabaseEncryptionKey"