from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetArchiveChatListSettings(Function):
    """
    Changes settings for automatic moving of chats to and from the Archive chat lists

    :param settings: New settings
    :return: :class:`Ok`
    """
    __slots__ = ("settings", "_extra", "_client_id", "_type")

    def __init__(self, settings = None):
        self.settings = settings
        self._type = "setArchiveChatListSettings"