from .function import Function

from .input_chat_photo import InputChatPhoto
from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetBotProfilePhoto(Function[Ok]):
    """
    Changes a profile photo for a bot

    :param bot_user_id: Identifier of the target bot
    :param photo: Profile photo to set; pass null to delete the chat photo
    :return: :class:`Ok`
    """
    __slots__ = ("bot_user_id", "photo", "_extra", "_client_id", "_type")

    def __init__(self, bot_user_id: int = 0, photo: InputChatPhoto | None = None):
        self.bot_user_id = bot_user_id
        self.photo = photo
        self._type = "setBotProfilePhoto"