from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetBotInfoShortDescription(Function):
    """
    Sets the text shown on a bot's profile page and sent together with the link when users share the bot. Can be called only if userTypeBot.can_be_edited == true

    :param bot_user_id: Identifier of the target bot
    :param language_code: A two-letter ISO 639-1 language code. If empty, the short description will be shown to all users for whose languages there is no dedicated description
    :param short_description: New bot's short description on the specified language
    :return: :class:`Ok`
    """
    __slots__ = ("bot_user_id", "language_code", "short_description", "_extra", "_client_id", "_type")

    def __init__(self, bot_user_id = None, language_code = None, short_description = None):
        self.bot_user_id = bot_user_id
        self.language_code = language_code
        self.short_description = short_description
        self._type = "setBotInfoShortDescription"