from .function import Function

from .input_file import InputFile
from .mask_position import MaskPosition
from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetStickerMaskPosition(Function[Ok]):
    """
    Changes the mask position of a mask sticker. The sticker must belong to a mask sticker set that is owned by the current user

    :param sticker: Sticker
    :param mask_position: Position where the mask is placed; pass null to remove mask position
    :return: :class:`Ok`
    """
    __slots__ = ("sticker", "mask_position", "_extra", "_client_id", "_type")

    def __init__(self, sticker: InputFile | None = None, mask_position: MaskPosition | None = None):
        self.sticker = sticker
        self.mask_position = mask_position
        self._type = "setStickerMaskPosition"