from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetCustomLanguagePack(Function):
    """
    Adds or changes a custom local language pack to the current localization target

    :param info: Information about the language pack. Language pack identifier must start with 'X', consist only of English letters, digits and hyphens, and must not exceed 64 characters. Can be called before authorization
    :param strings: Strings of the new language pack
    :return: :class:`Ok`
    """
    __slots__ = ("info", "strings", "_extra", "_client_id", "_type")

    def __init__(self, info = None, strings = None):
        self.info = info
        self.strings = strings
        self._type = "setCustomLanguagePack"