from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetLogStream(Function):
    """
    Sets new log stream for internal logging of TDLib. Can be called synchronously

    :param log_stream: New log stream
    :return: :class:`Ok`
    """
    __slots__ = ("log_stream", "_extra", "_client_id", "_type")

    def __init__(self, log_stream = None):
        self.log_stream = log_stream
        self._type = "setLogStream"