from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetDefaultReactionType(Function):
    """
    Changes type of default reaction for the current user

    :param reaction_type: New type of the default reaction. The paid reaction can't be set as default
    :return: :class:`Ok`
    """
    __slots__ = ("reaction_type", "_extra", "_client_id", "_type")

    def __init__(self, reaction_type = None):
        self.reaction_type = reaction_type
        self._type = "setDefaultReactionType"