from .function import Function

from .chat_administrator_rights import ChatAdministratorRights
from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetDefaultGroupAdministratorRights(Function[Ok]):
    """
    Sets default administrator rights for adding the bot to basic group and supergroup chats; for bots only

    :param default_group_administrator_rights: Default administrator rights for adding the bot to basic group and supergroup chats; pass null to remove default rights
    :return: :class:`Ok`
    """
    __slots__ = ("default_group_administrator_rights", "_extra", "_client_id", "_type")

    def __init__(self, default_group_administrator_rights: ChatAdministratorRights | None = None):
        self.default_group_administrator_rights = default_group_administrator_rights
        self._type = "setDefaultGroupAdministratorRights"