from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SetPinnedChats(Function):
    """
    Changes the order of pinned chats

    :param chat_list: Chat list in which to change the order of pinned chats
    :param chat_ids: The new list of pinned chats
    :return: :class:`Ok`
    """
    __slots__ = ("chat_list", "chat_ids", "_extra", "_client_id", "_type")

    def __init__(self, chat_list = None, chat_ids = None):
        self.chat_list = chat_list
        self.chat_ids = chat_ids
        self._type = "setPinnedChats"