from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ShareChatWithBot(Function[Ok]):
    """
    Shares a chat after pressing a keyboardButtonTypeRequestChat button with the bot

    :param chat_id: Identifier of the chat with the bot
    :param message_id: Identifier of the message with the button
    :param button_id: Identifier of the button
    :param shared_chat_id: Identifier of the shared chat
    :param only_check: Pass true to check that the chat can be shared by the button instead of actually sharing it. Doesn't check bot_is_member and bot_administrator_rights restrictions. If the bot must be a member, then all chats from getGroupsInCommon and all chats, where the user can add the bot, are suitable. In the latter case the bot will be automatically added to the chat. If the bot must be an administrator, then all chats, where the bot already has requested rights or can be added to administrators by the user, are suitable. In the latter case the bot will be automatically granted requested rights
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_id", "button_id", "shared_chat_id", "only_check", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, message_id: int = 0, button_id: int = 0, shared_chat_id: int = 0, only_check: bool = False):
        self.chat_id = chat_id
        self.message_id = message_id
        self.button_id = button_id
        self.shared_chat_id = shared_chat_id
        self.only_check = only_check
        self._type = "shareChatWithBot"