from .star_transaction_type import StarTransactionType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StarTransactionTypeTelegramAdsWithdrawal(StarTransactionType):
    """
    The transaction is a withdrawal of earned Telegram Stars to Telegram Ad platform; for bots and channel chats only

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "starTransactionTypeTelegramAdsWithdrawal"