from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StarSubscriptionPricing(ObjectBase):
    """
    Describes subscription plan paid in Telegram Stars

    :param period: The number of seconds between consecutive Telegram Star debiting
    :param star_count: The amount of Telegram Stars that must be paid for each period
    """
    __slots__ = ("period", "star_count", "_extra", "_client_id", "_type")

    def __init__(self, period: int = 0, star_count: int = 0):
        self.period = period
        self.star_count = star_count
        self._type = "starSubscriptionPricing"