from .message_sender import MessageSender
from .star_transaction_type import StarTransactionType
from .upgraded_gift import UpgradedGift

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StarTransactionTypeGiftTransfer(StarTransactionType):
    """
    The transaction is a transfer of an upgraded gift; for regular users only

    :param owner_id: Identifier of the user or the channel that received the gift
    :param gift: The gift
    """
    __slots__ = ("owner_id", "gift", "_extra", "_client_id", "_type")

    def __init__(self, owner_id: MessageSender | None = None, gift: UpgradedGift | None = None):
        self.owner_id = owner_id
        self.gift = gift
        self._type = "starTransactionTypeGiftTransfer"