from .star_transaction_type import StarTransactionType
from .sticker import Sticker

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StarTransactionTypePremiumPurchase(StarTransactionType):
    """
    The transaction is a purchase of Telegram Premium subscription; for regular users and bots only

    :param user_id: Identifier of the user that received the Telegram Premium subscription
    :param month_count: Number of months the Telegram Premium subscription will be active
    :param sticker: A sticker to be shown in the transaction information; may be null if unknown
    """
    __slots__ = ("user_id", "month_count", "sticker", "_extra", "_client_id", "_type")

    def __init__(self, user_id: int = 0, month_count: int = 0, sticker: Sticker | None = None):
        self.user_id = user_id
        self.month_count = month_count
        self.sticker = sticker
        self._type = "starTransactionTypePremiumPurchase"