from .affiliate_info import AffiliateInfo
from .star_transaction_type import StarTransactionType
from .upgraded_gift import UpgradedGift

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StarTransactionTypeUpgradedGiftSale(StarTransactionType):
    """
    The transaction is a sale of an upgraded gift; for regular users only

    :param user_id: Identifier of the user that bought the gift
    :param gift: The gift
    :param affiliate: Information about commission received by Telegram from the transaction
    """
    __slots__ = ("user_id", "gift", "affiliate", "_extra", "_client_id", "_type")

    def __init__(self, user_id: int = 0, gift: UpgradedGift | None = None, affiliate: AffiliateInfo | None = None):
        self.user_id = user_id
        self.gift = gift
        self.affiliate = affiliate
        self._type = "starTransactionTypeUpgradedGiftSale"