from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StarGiveawayWinnerOption(ObjectBase):
    """
    Describes an option for the number of winners of a Telegram Star giveaway

    :param winner_count: The number of users that will be chosen as winners
    :param won_star_count: The number of Telegram Stars that will be won by the winners of the giveaway
    :param is_default: True, if the option must be chosen by default
    """
    __slots__ = ("winner_count", "won_star_count", "is_default", "_extra", "_client_id", "_type")

    def __init__(self, winner_count = None, won_star_count = None, is_default = None):
        self.winner_count = winner_count
        self.won_star_count = won_star_count
        self.is_default = is_default
        self._type = "starGiveawayWinnerOption"