from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StartGroupCallRecording(Function):
    """
    Starts recording of an active group call; for video chats only. Requires groupCall.can_be_managed right

    :param group_call_id: Group call identifier
    :param title: Group call recording title; 0-64 characters
    :param record_video: Pass true to record a video file instead of an audio file
    :param use_portrait_orientation: Pass true to use portrait orientation for video instead of landscape one
    :return: :class:`Ok`
    """
    __slots__ = ("group_call_id", "title", "record_video", "use_portrait_orientation", "_extra", "_client_id", "_type")

    def __init__(self, group_call_id = None, title = None, record_video = None, use_portrait_orientation = None):
        self.group_call_id = group_call_id
        self.title = title
        self.record_video = record_video
        self.use_portrait_orientation = use_portrait_orientation
        self._type = "startGroupCallRecording"