from .object_base import ObjectBase
from .star_giveaway_payment_option import StarGiveawayPaymentOption
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StarGiveawayPaymentOptions(ObjectBase):
    """
    Contains a list of options for creating of Telegram Star giveaway

    :param options: The list of options
    """
    __slots__ = ("options", "_extra", "_client_id", "_type")

    def __init__(self, options: List[StarGiveawayPaymentOption] | None = None):
        self.options = options
        self._type = "starGiveawayPaymentOptions"