from .affiliate_info import AffiliateInfo
from .paid_media import PaidMedia
from .star_transaction_type import StarTransactionType
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StarTransactionTypeBotPaidMediaSale(StarTransactionType):
    """
    The transaction is a sale of paid media by the bot or a business account managed by the bot; for bots only

    :param user_id: Identifier of the user that bought the media
    :param media: The bought media
    :param payload: Bot-provided payload
    :param affiliate: Information about the affiliate which received commission from the transaction; may be null if none
    """
    __slots__ = ("user_id", "media", "payload", "affiliate", "_extra", "_client_id", "_type")

    def __init__(self, user_id: int = 0, media: List[PaidMedia] | None = None, payload: str = "", affiliate: AffiliateInfo | None = None):
        self.user_id = user_id
        self.media = media
        self.payload = payload
        self.affiliate = affiliate
        self._type = "starTransactionTypeBotPaidMediaSale"