from .statistical_graph import StatisticalGraph

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StatisticalGraphAsync(StatisticalGraph):
    """
    The graph data to be asynchronously loaded through getStatisticalGraph

    :param token: The token to use for data loading
    """
    __slots__ = ("token", "_extra", "_client_id", "_type")

    def __init__(self, token = None):
        self.token = token
        self._type = "statisticalGraphAsync"