from .statistical_graph import StatisticalGraph

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StatisticalGraphData(StatisticalGraph):
    """
    A graph data

    :param json_data: Graph data in JSON format
    :param zoom_token: If non-empty, a token which can be used to receive a zoomed in graph
    """
    __slots__ = ("json_data", "zoom_token", "_extra", "_client_id", "_type")

    def __init__(self, json_data: str = "", zoom_token: str = ""):
        self.json_data = json_data
        self.zoom_token = zoom_token
        self._type = "statisticalGraphData"