from .sticker_full_type import StickerFullType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StickerFullTypeCustomEmoji(StickerFullType):
    """
    The sticker is a custom emoji to be used inside message text and caption. Currently, only Telegram Premium users can use custom emoji

    :param custom_emoji_id: Identifier of the custom emoji
    :param needs_repainting: True, if the sticker must be repainted to a text color in messages, the color of the Telegram Premium badge in emoji status, white color on chat photos, or another appropriate color in other places
    """
    __slots__ = ("custom_emoji_id", "needs_repainting", "_extra", "_client_id", "_type")

    def __init__(self, custom_emoji_id = None, needs_repainting = None):
        self.custom_emoji_id = custom_emoji_id
        self.needs_repainting = needs_repainting
        self._type = "stickerFullTypeCustomEmoji"