from .sticker_format import StickerFormat

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StickerFormatWebp(StickerFormat):
    """
    The sticker is an image in WEBP format

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "stickerFormatWebp"