from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StopPoll(Function):
    """
    Stops a poll

    :param chat_id: Identifier of the chat to which the poll belongs
    :param message_id: Identifier of the message containing the poll. Use messageProperties.can_be_edited to check whether the poll can be stopped
    :param reply_markup: The new message reply markup; pass null if none; for bots only
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_id", "reply_markup", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_id = None, reply_markup = None):
        self.chat_id = chat_id
        self.message_id = message_id
        self.reply_markup = reply_markup
        self._type = "stopPoll"