from .story_area_type import StoryAreaType
from .venue import Venue

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StoryAreaTypeVenue(StoryAreaType):
    """
    An area pointing to a venue

    :param venue: Information about the venue
    """
    __slots__ = ("venue", "_extra", "_client_id", "_type")

    def __init__(self, venue: Venue | None = None):
        self.venue = venue
        self._type = "storyAreaTypeVenue"