from .location import Location
from .location_address import LocationAddress
from .story_area_type import StoryAreaType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StoryAreaTypeLocation(StoryAreaType):
    """
    An area pointing to a location

    :param location: The location
    :param address: Address of the location; may be null if unknown
    """
    __slots__ = ("location", "address", "_extra", "_client_id", "_type")

    def __init__(self, location: Location | None = None, address: LocationAddress | None = None):
        self.location = location
        self.address = address
        self._type = "storyAreaTypeLocation"