from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StoryRepostInfo(ObjectBase):
    """
    Contains information about original story that was reposted

    :param origin: Origin of the story that was reposted
    :param is_content_modified: True, if story content was modified during reposting; otherwise, story wasn't modified
    """
    __slots__ = ("origin", "is_content_modified", "_extra", "_client_id", "_type")

    def __init__(self, origin = None, is_content_modified = None):
        self.origin = origin
        self.is_content_modified = is_content_modified
        self._type = "storyRepostInfo"