from .story_content import StoryContent
from .story_video import StoryVideo

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StoryContentVideo(StoryContent):
    """
    A video story

    :param video: The video in MPEG4 format
    :param alternative_video: Alternative version of the video in MPEG4 format, encoded with H.264 codec; may be null
    """
    __slots__ = ("video", "alternative_video", "_extra", "_client_id", "_type")

    def __init__(self, video: StoryVideo | None = None, alternative_video: StoryVideo | None = None):
        self.video = video
        self.alternative_video = alternative_video
        self._type = "storyContentVideo"