from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StoryAreaType(ObjectBase):
    """
    Describes type of clickable area on a story media

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "StoryAreaType"