from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StoryInteractionType(ObjectBase):
    """
    Describes type of interaction with a story

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "StoryInteractionType"