from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StoryInteraction(ObjectBase):
    """
    Represents interaction with a story

    :param actor_id: Identifier of the user or chat that made the interaction
    :param interaction_date: Approximate point in time (Unix timestamp) when the interaction happened
    :param block_list: Block list to which the actor is added; may be null if none or for chat stories
    :param type: Type of the interaction
    """
    __slots__ = ("actor_id", "interaction_date", "block_list", "type", "_extra", "_client_id", "_type")

    def __init__(self, actor_id = None, interaction_date = None, block_list = None, type = None):
        self.actor_id = actor_id
        self.interaction_date = interaction_date
        self.block_list = block_list
        self.type = type
        self._type = "storyInteraction"