from .story_area_type import StoryAreaType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StoryAreaTypeSuggestedReaction(StoryAreaType):
    """
    An area pointing to a suggested reaction. App needs to show a clickable reaction on the area and call setStoryReaction when the are is clicked

    :param reaction_type: Type of the reaction
    :param total_count: Number of times the reaction was added
    :param is_dark: True, if reaction has a dark background
    :param is_flipped: True, if reaction corner is flipped
    """
    __slots__ = ("reaction_type", "total_count", "is_dark", "is_flipped", "_extra", "_client_id", "_type")

    def __init__(self, reaction_type = None, total_count = None, is_dark = None, is_flipped = None):
        self.reaction_type = reaction_type
        self.total_count = total_count
        self.is_dark = is_dark
        self.is_flipped = is_flipped
        self._type = "storyAreaTypeSuggestedReaction"