from .store_payment_purpose import StorePaymentPurpose

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class StorePaymentPurposePremiumSubscription(StorePaymentPurpose):
    """
    The user subscribing to Telegram Premium

    :param is_restore: Pass true if this is a restore of a Telegram Premium purchase; only for App Store
    :param is_upgrade: Pass true if this is an upgrade from a monthly subscription to early subscription; only for App Store
    """
    __slots__ = ("is_restore", "is_upgrade", "_extra", "_client_id", "_type")

    def __init__(self, is_restore = None, is_upgrade = None):
        self.is_restore = is_restore
        self.is_upgrade = is_upgrade
        self._type = "storePaymentPurposePremiumSubscription"