from .suggested_action import SuggestedAction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SuggestedActionCustom(SuggestedAction):
    """
    A custom suggestion to be shown at the top of the chat list

    :param name: Unique name of the suggestion
    :param title: Title of the suggestion
    :param description: A custom suggestion to be shown at the top of the chat list
    :param url: The link to open when the suggestion is clicked
    """
    __slots__ = ("name", "title", "description", "url", "_extra", "_client_id", "_type")

    def __init__(self, name = None, title = None, description = None, url = None):
        self.name = name
        self.title = title
        self.description = description
        self.url = url
        self._type = "suggestedActionCustom"