from .suggested_action import SuggestedAction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SuggestedActionRestorePremium(SuggestedAction):
    """
    Suggests the user to restore a recently expired Premium subscription

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "suggestedActionRestorePremium"