from .suggested_action import SuggestedAction

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SuggestedActionSetBirthdate(SuggestedAction):
    """
    Suggests the user to set birthdate

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "suggestedActionSetBirthdate"