from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class SynchronizeLanguagePack(Function[Ok]):
    """
    Fetches the latest versions of all strings from a language pack in the current localization target from the server. This method doesn't need to be called explicitly for the current used/base language packs. Can be called before authorization

    :param language_pack_id: Language pack identifier
    :return: :class:`Ok`
    """
    __slots__ = ("language_pack_id", "_extra", "_client_id", "_type")

    def __init__(self, language_pack_id: str = ""):
        self.language_pack_id = language_pack_id
        self._type = "synchronizeLanguagePack"