from .t_me_url_type import TMeUrlType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TMeUrlTypeSupergroup(TMeUrlType):
    """
    A URL linking to a public supergroup or channel

    :param supergroup_id: Identifier of the supergroup or channel
    """
    __slots__ = ("supergroup_id", "_extra", "_client_id", "_type")

    def __init__(self, supergroup_id = None):
        self.supergroup_id = supergroup_id
        self._type = "tMeUrlTypeSupergroup"