from .t_me_url_type import TMeUrlType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TMeUrlTypeStickerSet(TMeUrlType):
    """
    A URL linking to a sticker set

    :param sticker_set_id: Identifier of the sticker set
    """
    __slots__ = ("sticker_set_id", "_extra", "_client_id", "_type")

    def __init__(self, sticker_set_id: int = 0):
        self.sticker_set_id = sticker_set_id
        self._type = "tMeUrlTypeStickerSet"