from .telegram_payment_purpose import TelegramPaymentPurpose

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TelegramPaymentPurposeJoinChat(TelegramPaymentPurpose):
    """
    The user joins a chat and subscribes to regular payments in Telegram Stars

    :param invite_link: Invite link to use
    """
    __slots__ = ("invite_link", "_extra", "_client_id", "_type")

    def __init__(self, invite_link = None):
        self.invite_link = invite_link
        self._type = "telegramPaymentPurposeJoinChat"