from .telegram_payment_purpose import TelegramPaymentPurpose

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TelegramPaymentPurposeStarGiveaway(TelegramPaymentPurpose):
    """
    The user creating a Telegram Star giveaway

    :param parameters: Giveaway parameters
    :param currency: ISO 4217 currency code of the payment currency
    :param amount: Paid amount, in the smallest units of the currency
    :param winner_count: The number of users to receive Telegram Stars
    :param star_count: The number of Telegram Stars to be distributed through the giveaway
    """
    __slots__ = ("parameters", "currency", "amount", "winner_count", "star_count", "_extra", "_client_id", "_type")

    def __init__(self, parameters = None, currency = None, amount = None, winner_count = None, star_count = None):
        self.parameters = parameters
        self.currency = currency
        self.amount = amount
        self.winner_count = winner_count
        self.star_count = star_count
        self._type = "telegramPaymentPurposeStarGiveaway"