from .formatted_text import FormattedText
from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TermsOfService(ObjectBase):
    """
    Contains Telegram terms of service

    :param text: Text of the terms of service
    :param min_user_age: The minimum age of a user to be able to accept the terms; 0 if age isn't restricted
    :param show_popup: True, if a blocking popup with terms of service must be shown to the user
    """
    __slots__ = ("text", "min_user_age", "show_popup", "_extra", "_client_id", "_type")

    def __init__(self, text: FormattedText | None = None, min_user_age: int = 0, show_popup: bool = False):
        self.text = text
        self.min_user_age = min_user_age
        self.show_popup = show_popup
        self._type = "termsOfService"