from .function import Function

from .test_string import TestString

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TestCallString(Function[TestString]):
    """
    Returns the received string; for testing only. This is an offline method. Can be called before authorization

    :param x: String to return
    :return: :class:`TestString`
    """
    __slots__ = ("x", "_extra", "_client_id", "_type")

    def __init__(self, x: str = ""):
        self.x = x
        self._type = "testCallString"