from .function import Function

from .test_int import TestInt
from .test_vector_int_object import TestVectorIntObject
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TestCallVectorIntObject(Function[TestVectorIntObject]):
    """
    Returns the received vector of objects containing a number; for testing only. This is an offline method. Can be called before authorization

    :param x: Vector of objects to return
    :return: :class:`TestVectorIntObject`
    """
    __slots__ = ("x", "_extra", "_client_id", "_type")

    def __init__(self, x: List[TestInt] | None = None):
        self.x = x
        self._type = "testCallVectorIntObject"