from .function import Function

from .test_int import TestInt

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TestSquareInt(Function[TestInt]):
    """
    Returns the squared received number; for testing only. This is an offline method. Can be called before authorization

    :param x: Number to square
    :return: :class:`TestInt`
    """
    __slots__ = ("x", "_extra", "_client_id", "_type")

    def __init__(self, x: int = 0):
        self.x = x
        self._type = "testSquareInt"