from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TestVectorInt(ObjectBase):
    """
    A simple object containing a vector of numbers; for testing only

    :param value: Vector of numbers
    """
    __slots__ = ("value", "_extra", "_client_id", "_type")

    def __init__(self, value = None):
        self.value = value
        self._type = "testVectorInt"