from .text_entity_type import TextEntityType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TextEntityTypeMentionName(TextEntityType):
    """
    A text shows instead of a raw mention of the user (e.g., when the user has no username)

    :param user_id: Identifier of the mentioned user
    """
    __slots__ = ("user_id", "_extra", "_client_id", "_type")

    def __init__(self, user_id = None):
        self.user_id = user_id
        self._type = "textEntityTypeMentionName"