from .text_entity_type import TextEntityType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TextEntityTypeBold(TextEntityType):
    """
    A bold text

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "textEntityTypeBold"