from .text_entity_type import TextEntityType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TextEntityTypeMediaTimestamp(TextEntityType):
    """
    A media timestamp

    :param media_timestamp: Timestamp from which a video/audio/video note/voice note/story playing must start, in seconds. The media can be in the content or the link preview of the current message, or in the same places in the replied message
    """
    __slots__ = ("media_timestamp", "_extra", "_client_id", "_type")

    def __init__(self, media_timestamp = None):
        self.media_timestamp = media_timestamp
        self._type = "textEntityTypeMediaTimestamp"