from .thumbnail_format import ThumbnailFormat

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ThumbnailFormatJpeg(ThumbnailFormat):
    """
    The thumbnail is in JPEG format

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "thumbnailFormatJpeg"