from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TimeZone(ObjectBase):
    """
    Describes a time zone

    :param id: Unique time zone identifier
    :param name: Time zone name
    :param utc_time_offset: Current UTC time offset for the time zone
    """
    __slots__ = ("id", "name", "utc_time_offset", "_extra", "_client_id", "_type")

    def __init__(self, id = None, name = None, utc_time_offset = None):
        self.id = id
        self.name = name
        self.utc_time_offset = utc_time_offset
        self._type = "timeZone"