from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleBotCanManageEmojiStatus(Function[Ok]):
    """
    Toggles whether the bot can manage emoji status of the current user

    :param bot_user_id: User identifier of the bot
    :param can_manage_emoji_status: Pass true if the bot is allowed to change emoji status of the user; pass false otherwise
    :return: :class:`Ok`
    """
    __slots__ = ("bot_user_id", "can_manage_emoji_status", "_extra", "_client_id", "_type")

    def __init__(self, bot_user_id: int = 0, can_manage_emoji_status: bool = False):
        self.bot_user_id = bot_user_id
        self.can_manage_emoji_status = can_manage_emoji_status
        self._type = "toggleBotCanManageEmojiStatus"