from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleStoryIsPostedToChatPage(Function):
    """
    Toggles whether a story is accessible after expiration. Can be called only if story.can_toggle_is_posted_to_chat_page == true

    :param story_poster_chat_id: Identifier of the chat that posted the story
    :param story_id: Identifier of the story
    :param is_posted_to_chat_page: Pass true to make the story accessible after expiration; pass false to make it private
    :return: :class:`Ok`
    """
    __slots__ = ("story_poster_chat_id", "story_id", "is_posted_to_chat_page", "_extra", "_client_id", "_type")

    def __init__(self, story_poster_chat_id = None, story_id = None, is_posted_to_chat_page = None):
        self.story_poster_chat_id = story_poster_chat_id
        self.story_id = story_id
        self.is_posted_to_chat_page = is_posted_to_chat_page
        self._type = "toggleStoryIsPostedToChatPage"