from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleSessionCanAcceptSecretChats(Function):
    """
    Toggles whether a session can accept incoming secret chats

    :param session_id: Session identifier
    :param can_accept_secret_chats: Pass true to allow accepting secret chats by the session; pass false otherwise
    :return: :class:`Ok`
    """
    __slots__ = ("session_id", "can_accept_secret_chats", "_extra", "_client_id", "_type")

    def __init__(self, session_id = None, can_accept_secret_chats = None):
        self.session_id = session_id
        self.can_accept_secret_chats = can_accept_secret_chats
        self._type = "toggleSessionCanAcceptSecretChats"