from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleBusinessConnectedBotChatIsPaused(Function):
    """
    Pauses or resumes the connected business bot in a specific chat

    :param chat_id: Chat identifier
    :param is_paused: Pass true to pause the connected bot in the chat; pass false to resume the bot
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "is_paused", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, is_paused = None):
        self.chat_id = chat_id
        self.is_paused = is_paused
        self._type = "toggleBusinessConnectedBotChatIsPaused"