from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleSavedMessagesTopicIsPinned(Function):
    """
    Changes the pinned state of a Saved Messages topic. There can be up to getOption("pinned_saved_messages_topic_count_max") pinned topics. The limit can be increased with Telegram Premium

    :param saved_messages_topic_id: Identifier of Saved Messages topic to pin or unpin
    :param is_pinned: Pass true to pin the topic; pass false to unpin it
    :return: :class:`Ok`
    """
    __slots__ = ("saved_messages_topic_id", "is_pinned", "_extra", "_client_id", "_type")

    def __init__(self, saved_messages_topic_id = None, is_pinned = None):
        self.saved_messages_topic_id = saved_messages_topic_id
        self.is_pinned = is_pinned
        self._type = "toggleSavedMessagesTopicIsPinned"