from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleSupergroupIsAllHistoryAvailable(Function[Ok]):
    """
    Toggles whether the message history of a supergroup is available to new members; requires can_change_info member right

    :param supergroup_id: The identifier of the supergroup
    :param is_all_history_available: The new value of is_all_history_available
    :return: :class:`Ok`
    """
    __slots__ = ("supergroup_id", "is_all_history_available", "_extra", "_client_id", "_type")

    def __init__(self, supergroup_id: int = 0, is_all_history_available: bool = False):
        self.supergroup_id = supergroup_id
        self.is_all_history_available = is_all_history_available
        self._type = "toggleSupergroupIsAllHistoryAvailable"