from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleBotIsAddedToAttachmentMenu(Function[Ok]):
    """
    Adds or removes a bot to attachment and side menu. Bot can be added to the menu, only if userTypeBot.can_be_added_to_attachment_menu == true

    :param bot_user_id: Bot's user identifier
    :param is_added: Pass true to add the bot to attachment menu; pass false to remove the bot from attachment menu
    :param allow_write_access: Pass true if the current user allowed the bot to send them messages. Ignored if is_added is false
    :return: :class:`Ok`
    """
    __slots__ = ("bot_user_id", "is_added", "allow_write_access", "_extra", "_client_id", "_type")

    def __init__(self, bot_user_id: int = 0, is_added: bool = False, allow_write_access: bool = False):
        self.bot_user_id = bot_user_id
        self.is_added = is_added
        self.allow_write_access = allow_write_access
        self._type = "toggleBotIsAddedToAttachmentMenu"