from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleDownloadIsPaused(Function[Ok]):
    """
    Changes pause state of a file in the file download list

    :param file_id: Identifier of the downloaded file
    :param is_paused: Pass true if the download is paused
    :return: :class:`Ok`
    """
    __slots__ = ("file_id", "is_paused", "_extra", "_client_id", "_type")

    def __init__(self, file_id: int = 0, is_paused: bool = False):
        self.file_id = file_id
        self.is_paused = is_paused
        self._type = "toggleDownloadIsPaused"