from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleChatGiftNotifications(Function):
    """
    Toggles whether notifications for new gifts received by a channel chat are sent to the current user; requires can_post_messages administrator right in the chat

    :param chat_id: Identifier of the channel chat
    :param are_enabled: Pass true to enable notifications about new gifts owned by the channel chat; pass false to disable the notifications
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "are_enabled", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, are_enabled = None):
        self.chat_id = chat_id
        self.are_enabled = are_enabled
        self._type = "toggleChatGiftNotifications"