from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleSupergroupIsBroadcastGroup(Function[Ok]):
    """
    Upgrades supergroup to a broadcast group; requires owner privileges in the supergroup

    :param supergroup_id: Identifier of the supergroup
    :return: :class:`Ok`
    """
    __slots__ = ("supergroup_id", "_extra", "_client_id", "_type")

    def __init__(self, supergroup_id: int = 0):
        self.supergroup_id = supergroup_id
        self._type = "toggleSupergroupIsBroadcastGroup"