from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleGeneralForumTopicIsHidden(Function):
    """
    Toggles whether a General topic is hidden in a forum supergroup chat; requires can_manage_topics right in the supergroup

    :param chat_id: Identifier of the chat
    :param is_hidden: Pass true to hide and close the General topic; pass false to unhide it
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "is_hidden", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, is_hidden = None):
        self.chat_id = chat_id
        self.is_hidden = is_hidden
        self._type = "toggleGeneralForumTopicIsHidden"