from .function import Function

from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleForumTopicIsPinned(Function[Ok]):
    """
    Changes the pinned state of a forum topic; requires can_manage_topics right in the supergroup. There can be up to getOption("pinned_forum_topic_count_max") pinned forum topics

    :param chat_id: Chat identifier
    :param message_thread_id: Message thread identifier of the forum topic
    :param is_pinned: Pass true to pin the topic; pass false to unpin it
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_thread_id", "is_pinned", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, message_thread_id: int = 0, is_pinned: bool = False):
        self.chat_id = chat_id
        self.message_thread_id = message_thread_id
        self.is_pinned = is_pinned
        self._type = "toggleForumTopicIsPinned"