from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ToggleChatIsPinned(Function):
    """
    Changes the pinned state of a chat. There can be up to getOption("pinned_chat_count_max")/getOption("pinned_archived_chat_count_max") pinned non-secret chats and the same number of secret chats in the main/archive chat list. The limit can be increased with Telegram Premium

    :param chat_list: Chat list in which to change the pinned state of the chat
    :param chat_id: Chat identifier
    :param is_pinned: Pass true to pin the chat; pass false to unpin it
    :return: :class:`Ok`
    """
    __slots__ = ("chat_list", "chat_id", "is_pinned", "_extra", "_client_id", "_type")

    def __init__(self, chat_list = None, chat_id = None, is_pinned = None):
        self.chat_list = chat_list
        self.chat_id = chat_id
        self.is_pinned = is_pinned
        self._type = "toggleChatIsPinned"