from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TopChatCategory(ObjectBase):
    """
    Represents the categories of chats for which a list of frequently used chats can be retrieved

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "TopChatCategory"