from .function import Function

from .message_sender import MessageSender
from .ok import Ok

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class TransferGift(Function[Ok]):
    """
    Sends an upgraded gift to another user or a channel chat

    :param business_connection_id: Unique identifier of business connection on behalf of which to send the request; for bots only
    :param received_gift_id: Identifier of the gift
    :param new_owner_id: Identifier of the user or the channel chat that will receive the gift
    :param star_count: The amount of Telegram Stars required to pay for the transfer
    :return: :class:`Ok`
    """
    __slots__ = ("business_connection_id", "received_gift_id", "new_owner_id", "star_count", "_extra", "_client_id", "_type")

    def __init__(self, business_connection_id: str = "", received_gift_id: str = "", new_owner_id: MessageSender | None = None, star_count: int = 0):
        self.business_connection_id = business_connection_id
        self.received_gift_id = received_gift_id
        self.new_owner_id = new_owner_id
        self.star_count = star_count
        self._type = "transferGift"