from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UnpinAllMessageThreadMessages(Function):
    """
    Removes all pinned messages from a forum topic; requires can_pin_messages member right in the supergroup

    :param chat_id: Identifier of the chat
    :param message_thread_id: Message thread identifier in which messages will be unpinned
    :return: :class:`Ok`
    """
    __slots__ = ("chat_id", "message_thread_id", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_thread_id = None):
        self.chat_id = chat_id
        self.message_thread_id = message_thread_id
        self._type = "unpinAllMessageThreadMessages"