from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UnreadReaction(ObjectBase):
    """
    Contains information about an unread reaction to a message

    :param type: Type of the reaction
    :param sender_id: Identifier of the sender, added the reaction
    :param is_big: True, if the reaction was added with a big animation
    """
    __slots__ = ("type", "sender_id", "is_big", "_extra", "_client_id", "_type")

    def __init__(self, type = None, sender_id = None, is_big = None):
        self.type = type
        self.sender_id = sender_id
        self.is_big = is_big
        self._type = "unreadReaction"