from .business_connection import BusinessConnection
from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateBusinessConnection(Update):
    """
    A business connection has changed; for bots only

    :param connection: New data about the connection
    """
    __slots__ = ("connection", "_extra", "_client_id", "_type")

    def __init__(self, connection: BusinessConnection | None = None):
        self.connection = connection
        self._type = "updateBusinessConnection"