from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class Updates(ObjectBase):
    """
    Contains a list of updates

    :param updates: List of updates
    """
    __slots__ = ("updates", "_extra", "_client_id", "_type")

    def __init__(self, updates = None):
        self.updates = updates
        self._type = "updates"