from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateApplicationRecaptchaVerificationRequired(Update):
    """
    A request can't be completed unless reCAPTCHA verification is performed; for official mobile applications only. The method setApplicationVerificationToken must be called once the verification is completed or failed

    :param verification_id: Unique identifier for the verification process
    :param action: The action for the check
    :param recaptcha_key_id: Identifier of the reCAPTCHA key
    """
    __slots__ = ("verification_id", "action", "recaptcha_key_id", "_extra", "_client_id", "_type")

    def __init__(self, verification_id = None, action = None, recaptcha_key_id = None):
        self.verification_id = verification_id
        self.action = action
        self.recaptcha_key_id = recaptcha_key_id
        self._type = "updateApplicationRecaptchaVerificationRequired"