from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateChatPosition(Update):
    """
    The position of a chat in a chat list has changed. An updateChatLastMessage or updateChatDraftMessage update might be sent instead of the update

    :param chat_id: Chat identifier
    :param position: New chat position. If new order is 0, then the chat needs to be removed from the list
    """
    __slots__ = ("chat_id", "position", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, position = None):
        self.chat_id = chat_id
        self.position = position
        self._type = "updateChatPosition"