from .group_call import GroupCall
from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateGroupCall(Update):
    """
    Information about a group call was updated

    :param group_call: New data about the group call
    """
    __slots__ = ("group_call", "_extra", "_client_id", "_type")

    def __init__(self, group_call: GroupCall | None = None):
        self.group_call = group_call
        self._type = "updateGroupCall"