from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateMessageReactions(Update):
    """
    Reactions added to a message with anonymous reactions have changed; for bots only

    :param chat_id: Chat identifier
    :param message_id: Message identifier
    :param date: Point in time (Unix timestamp) when the reactions were changed
    :param reactions: The list of reactions added to the message
    """
    __slots__ = ("chat_id", "message_id", "date", "reactions", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, message_id = None, date = None, reactions = None):
        self.chat_id = chat_id
        self.message_id = message_id
        self.date = date
        self.reactions = reactions
        self._type = "updateMessageReactions"