from .update import Update
from .user_status import UserStatus

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateUserStatus(Update):
    """
    The user went online or offline

    :param user_id: User identifier
    :param status: New status of the user
    """
    __slots__ = ("user_id", "status", "_extra", "_client_id", "_type")

    def __init__(self, user_id: int = 0, status: UserStatus | None = None):
        self.user_id = user_id
        self.status = status
        self._type = "updateUserStatus"