from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateRecentStickers(Update):
    """
    The list of recently used stickers was updated

    :param is_attached: True, if the list of stickers attached to photo or video files was updated; otherwise, the list of sent stickers is updated
    :param sticker_ids: The new list of file identifiers of recently used stickers
    """
    __slots__ = ("is_attached", "sticker_ids", "_extra", "_client_id", "_type")

    def __init__(self, is_attached = None, sticker_ids = None):
        self.is_attached = is_attached
        self.sticker_ids = sticker_ids
        self._type = "updateRecentStickers"