from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateSavedMessagesTags(Update):
    """
    Tags used in Saved Messages or a Saved Messages topic have changed

    :param saved_messages_topic_id: Identifier of Saved Messages topic which tags were changed; 0 if tags for the whole chat has changed
    :param tags: The new tags
    """
    __slots__ = ("saved_messages_topic_id", "tags", "_extra", "_client_id", "_type")

    def __init__(self, saved_messages_topic_id = None, tags = None):
        self.saved_messages_topic_id = saved_messages_topic_id
        self.tags = tags
        self._type = "updateSavedMessagesTags"