from .message_sender import MessageSender
from .star_revenue_status import StarRevenueStatus
from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateStarRevenueStatus(Update):
    """
    The Telegram Star revenue earned by a bot or a chat has changed. If Telegram Star transaction screen of the chat is opened, then getStarTransactions may be called to fetch new transactions

    :param owner_id: Identifier of the owner of the Telegram Stars
    :param status: New Telegram Star revenue status
    """
    __slots__ = ("owner_id", "status", "_extra", "_client_id", "_type")

    def __init__(self, owner_id: MessageSender | None = None, status: StarRevenueStatus | None = None):
        self.owner_id = owner_id
        self.status = status
        self._type = "updateStarRevenueStatus"