from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateSavedMessagesTopicCount(Update):
    """
    Number of Saved Messages topics has changed

    :param topic_count: Approximate total number of Saved Messages topics
    """
    __slots__ = ("topic_count", "_extra", "_client_id", "_type")

    def __init__(self, topic_count: int = 0):
        self.topic_count = topic_count
        self._type = "updateSavedMessagesTopicCount"