from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateMessageIsPinned(Update):
    """
    The message pinned state was changed

    :param chat_id: Chat identifier
    :param message_id: The message identifier
    :param is_pinned: True, if the message is pinned
    """
    __slots__ = ("chat_id", "message_id", "is_pinned", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, message_id: int = 0, is_pinned: bool = False):
        self.chat_id = chat_id
        self.message_id = message_id
        self.is_pinned = is_pinned
        self._type = "updateMessageIsPinned"