from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateChatHasProtectedContent(Update):
    """
    A chat content was allowed or restricted for saving

    :param chat_id: Chat identifier
    :param has_protected_content: New value of has_protected_content
    """
    __slots__ = ("chat_id", "has_protected_content", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, has_protected_content = None):
        self.chat_id = chat_id
        self.has_protected_content = has_protected_content
        self._type = "updateChatHasProtectedContent"