from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateAttachmentMenuBots(Update):
    """
    The list of bots added to attachment or side menu has changed

    :param bots: The new list of bots. The bots must not be shown on scheduled messages screen
    """
    __slots__ = ("bots", "_extra", "_client_id", "_type")

    def __init__(self, bots = None):
        self.bots = bots
        self._type = "updateAttachmentMenuBots"