from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateDirectMessagesChatTopic(Update):
    """
    Basic information about a topic in a channel direct messages chat administered by the current user has changed. This update is guaranteed to come before the topic identifier is returned to the application

    :param topic: New data about the topic
    """
    __slots__ = ("topic", "_extra", "_client_id", "_type")

    def __init__(self, topic = None):
        self.topic = topic
        self._type = "updateDirectMessagesChatTopic"