from .chat_available_reactions import ChatAvailableReactions
from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateChatAvailableReactions(Update):
    """
    The chat available reactions were changed

    :param chat_id: Chat identifier
    :param available_reactions: The new reactions, available in the chat
    """
    __slots__ = ("chat_id", "available_reactions", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, available_reactions: ChatAvailableReactions | None = None):
        self.chat_id = chat_id
        self.available_reactions = available_reactions
        self._type = "updateChatAvailableReactions"