from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateActiveNotifications(Update):
    """
    Contains active notifications that were shown on previous application launches. This update is sent only if the message database is used. In that case it comes once before any updateNotification and updateNotificationGroup update

    :param groups: Lists of active notification groups
    """
    __slots__ = ("groups", "_extra", "_client_id", "_type")

    def __init__(self, groups = None):
        self.groups = groups
        self._type = "updateActiveNotifications"