from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateChatIsMarkedAsUnread(Update):
    """
    A chat was marked as unread or was read

    :param chat_id: Chat identifier
    :param is_marked_as_unread: New value of is_marked_as_unread
    """
    __slots__ = ("chat_id", "is_marked_as_unread", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, is_marked_as_unread = None):
        self.chat_id = chat_id
        self.is_marked_as_unread = is_marked_as_unread
        self._type = "updateChatIsMarkedAsUnread"