from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateChatBackground(Update):
    """
    The chat background was changed

    :param chat_id: Chat identifier
    :param background: The new chat background; may be null if background was reset to default
    """
    __slots__ = ("chat_id", "background", "_extra", "_client_id", "_type")

    def __init__(self, chat_id = None, background = None):
        self.chat_id = chat_id
        self.background = background
        self._type = "updateChatBackground"