from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateAvailableMessageEffects(Update):
    """
    The list of available message effects has changed

    :param reaction_effect_ids: The new list of available message effects from emoji reactions
    :param sticker_effect_ids: The new list of available message effects from Premium stickers
    """
    __slots__ = ("reaction_effect_ids", "sticker_effect_ids", "_extra", "_client_id", "_type")

    def __init__(self, reaction_effect_ids = None, sticker_effect_ids = None):
        self.reaction_effect_ids = reaction_effect_ids
        self.sticker_effect_ids = sticker_effect_ids
        self._type = "updateAvailableMessageEffects"