from .update import Update
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateGroupCallVerificationState(Update):
    """
    The verification state of an encrypted group call has changed; for group calls not bound to a chat only

    :param group_call_id: Identifier of the group call
    :param generation: The call state generation to which the emoji corresponds. If generation is different for two users, then their emoji may be also different
    :param emojis: Group call state fingerprint represented as 4 emoji; may be empty if the state isn't verified yet
    """
    __slots__ = ("group_call_id", "generation", "emojis", "_extra", "_client_id", "_type")

    def __init__(self, group_call_id: int = 0, generation: int = 0, emojis: List[str] | None = None):
        self.group_call_id = group_call_id
        self.generation = generation
        self.emojis = emojis
        self._type = "updateGroupCallVerificationState"