from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateChatTheme(Update):
    """
    The chat theme was changed

    :param chat_id: Chat identifier
    :param theme_name: The new name of the chat theme; may be empty if theme was reset to default
    """
    __slots__ = ("chat_id", "theme_name", "_extra", "_client_id", "_type")

    def __init__(self, chat_id: int = 0, theme_name: str = ""):
        self.chat_id = chat_id
        self.theme_name = theme_name
        self._type = "updateChatTheme"