from .suggested_action import SuggestedAction
from .update import Update
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateSuggestedActions(Update):
    """
    The list of suggested to the user actions has changed

    :param added_actions: Added suggested actions
    :param removed_actions: Removed suggested actions
    """
    __slots__ = ("added_actions", "removed_actions", "_extra", "_client_id", "_type")

    def __init__(self, added_actions: List[SuggestedAction] | None = None, removed_actions: List[SuggestedAction] | None = None):
        self.added_actions = added_actions
        self.removed_actions = removed_actions
        self._type = "updateSuggestedActions"