from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateQuickReplyShortcuts(Update):
    """
    The list of quick reply shortcuts has changed

    :param shortcut_ids: The new list of identifiers of quick reply shortcuts
    """
    __slots__ = ("shortcut_ids", "_extra", "_client_id", "_type")

    def __init__(self, shortcut_ids = None):
        self.shortcut_ids = shortcut_ids
        self._type = "updateQuickReplyShortcuts"