from .error import Error
from .message import Message
from .update import Update

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateMessageSendFailed(Update):
    """
    A message failed to send. Be aware that some messages being sent can be irrecoverably deleted, in which case updateDeleteMessages will be received instead of this update

    :param message: The failed to send message
    :param old_message_id: The previous temporary message identifier
    :param error: The cause of the message sending failure
    """
    __slots__ = ("message", "old_message_id", "error", "_extra", "_client_id", "_type")

    def __init__(self, message: Message | None = None, old_message_id: int = 0, error: Error | None = None):
        self.message = message
        self.old_message_id = old_message_id
        self.error = error
        self._type = "updateMessageSendFailed"