from .close_birthday_user import CloseBirthdayUser
from .update import Update
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpdateContactCloseBirthdays(Update):
    """
    The list of contacts that had birthdays recently or will have birthday soon has changed

    :param close_birthday_users: List of contact users with close birthday
    """
    __slots__ = ("close_birthday_users", "_extra", "_client_id", "_type")

    def __init__(self, close_birthday_users: List[CloseBirthdayUser] | None = None):
        self.close_birthday_users = close_birthday_users
        self._type = "updateContactCloseBirthdays"