from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpgradedGiftOriginalDetails(ObjectBase):
    """
    Describes the original details about the gift

    :param sender_id: Identifier of the user or the chat that sent the gift; may be null if the gift was private
    :param receiver_id: Identifier of the user or the chat that received the gift
    :param text: Message added to the gift
    :param date: Point in time (Unix timestamp) when the gift was sent
    """
    __slots__ = ("sender_id", "receiver_id", "text", "date", "_extra", "_client_id", "_type")

    def __init__(self, sender_id = None, receiver_id = None, text = None, date = None):
        self.sender_id = sender_id
        self.receiver_id = receiver_id
        self.text = text
        self.date = date
        self._type = "upgradedGiftOriginalDetails"