from .object_base import ObjectBase
from .sticker import Sticker

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UpgradedGiftSymbol(ObjectBase):
    """
    Describes a symbol shown on the pattern of an upgraded gift

    :param name: Name of the symbol
    :param sticker: The sticker representing the symbol
    :param rarity_per_mille: The number of upgraded gifts that receive this symbol for each 1000 gifts upgraded
    """
    __slots__ = ("name", "sticker", "rarity_per_mille", "_extra", "_client_id", "_type")

    def __init__(self, name: str = "", sticker: Sticker | None = None, rarity_per_mille: int = 0):
        self.name = name
        self.sticker = sticker
        self.rarity_per_mille = rarity_per_mille
        self._type = "upgradedGiftSymbol"