from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UploadStickerFile(Function):
    """
    Uploads a file with a sticker; returns the uploaded file

    :param user_id: Sticker file owner; ignored for regular users
    :param sticker_format: Sticker format
    :param sticker: File file to upload; must fit in a 512x512 square. For WEBP stickers the file must be in WEBP or PNG format, which will be converted to WEBP server-side. See https://core.telegram.org/animated_stickers#technical-requirements for technical requirements
    :return: :class:`File`
    """
    __slots__ = ("user_id", "sticker_format", "sticker", "_extra", "_client_id", "_type")

    def __init__(self, user_id = None, sticker_format = None, sticker = None):
        self.user_id = user_id
        self.sticker_format = sticker_format
        self.sticker = sticker
        self._type = "uploadStickerFile"