from .user_privacy_setting import UserPrivacySetting

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UserPrivacySettingAllowUnpaidMessages(UserPrivacySetting):
    """
    A privacy setting for managing whether the user can receive messages without additional payment

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "userPrivacySettingAllowUnpaidMessages"