from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UserLink(ObjectBase):
    """
    Contains an HTTPS URL, which can be used to get information about a user

    :param url: The URL
    :param expires_in: Left time for which the link is valid, in seconds; 0 if the link is a public username link
    """
    __slots__ = ("url", "expires_in", "_extra", "_client_id", "_type")

    def __init__(self, url: str = "", expires_in: int = 0):
        self.url = url
        self.expires_in = expires_in
        self._type = "userLink"