from .user_status import UserStatus

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UserStatusOnline(UserStatus):
    """
    The user is online

    :param expires: Point in time (Unix timestamp) when the user's online status will expire
    """
    __slots__ = ("expires", "_extra", "_client_id", "_type")

    def __init__(self, expires = None):
        self.expires = expires
        self._type = "userStatusOnline"