from .user_privacy_setting import UserPrivacySetting

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UserPrivacySettingAllowPrivateVoiceAndVideoNoteMessages(UserPrivacySetting):
    """
    A privacy setting for managing whether the user can receive voice and video messages in private chats; for Telegram Premium users only

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "userPrivacySettingAllowPrivateVoiceAndVideoNoteMessages"