from .user_privacy_setting_rule import UserPrivacySettingRule
from typing import List

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UserPrivacySettingRuleRestrictUsers(UserPrivacySettingRule):
    """
    A rule to restrict all specified users from doing something

    :param user_ids: The user identifiers, total number of users in all rules must not exceed 1000
    """
    __slots__ = ("user_ids", "_extra", "_client_id", "_type")

    def __init__(self, user_ids: List[int] | None = None):
        self.user_ids = user_ids
        self._type = "userPrivacySettingRuleRestrictUsers"