from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UserPrivacySettingRule(ObjectBase):
    """
    Represents a single rule for managing user privacy settings

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "UserPrivacySettingRule"