from .user_type import UserType

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UserTypeBot(UserType):
    """
    A bot (see https://core.telegram.org/bots)

    :param can_be_edited: True, if the bot is owned by the current user and can be edited using the methods toggleBotUsernameIsActive, reorderBotActiveUsernames, setBotProfilePhoto, setBotName, setBotInfoDescription, and setBotInfoShortDescription
    :param can_join_groups: True, if the bot can be invited to basic group and supergroup chats
    :param can_read_all_group_messages: True, if the bot can read all messages in basic group or supergroup chats and not just those addressed to the bot. In private and channel chats a bot can always read all messages
    :param has_main_web_app: True, if the bot has the main Web App
    :param is_inline: True, if the bot supports inline queries
    :param inline_query_placeholder: Placeholder for inline queries (displayed on the application input field)
    :param need_location: True, if the location of the user is expected to be sent with every inline query to this bot
    :param can_connect_to_business: True, if the bot supports connection to Telegram Business accounts
    :param can_be_added_to_attachment_menu: True, if the bot can be added to attachment or side menu
    :param active_user_count: The number of recently active users of the bot
    """
    __slots__ = ("can_be_edited", "can_join_groups", "can_read_all_group_messages", "has_main_web_app", "is_inline", "inline_query_placeholder", "need_location", "can_connect_to_business", "can_be_added_to_attachment_menu", "active_user_count", "_extra", "_client_id", "_type")

    def __init__(self, can_be_edited = None, can_join_groups = None, can_read_all_group_messages = None, has_main_web_app = None, is_inline = None, inline_query_placeholder = None, need_location = None, can_connect_to_business = None, can_be_added_to_attachment_menu = None, active_user_count = None):
        self.can_be_edited = can_be_edited
        self.can_join_groups = can_join_groups
        self.can_read_all_group_messages = can_read_all_group_messages
        self.has_main_web_app = has_main_web_app
        self.is_inline = is_inline
        self.inline_query_placeholder = inline_query_placeholder
        self.need_location = need_location
        self.can_connect_to_business = can_connect_to_business
        self.can_be_added_to_attachment_menu = can_be_added_to_attachment_menu
        self.active_user_count = active_user_count
        self._type = "userTypeBot"