from .user_privacy_setting import UserPrivacySetting

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class UserPrivacySettingAutosaveGifts(UserPrivacySetting):
    """
    A privacy setting for managing whether received gifts are automatically shown on the user's profile page

    """
    __slots__ = ("_extra", "_client_id", "_type")

    def __init__(self):

        self._type = "userPrivacySettingAutosaveGifts"