from .function import Function



### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class ValidateOrderInfo(Function):
    """
    Validates the order information provided by a user and returns the available shipping options for a flexible invoice

    :param input_invoice: The invoice
    :param order_info: The order information, provided by the user; pass null if empty
    :param allow_save: Pass true to save the order information
    :return: :class:`ValidatedOrderInfo`
    """
    __slots__ = ("input_invoice", "order_info", "allow_save", "_extra", "_client_id", "_type")

    def __init__(self, input_invoice = None, order_info = None, allow_save = None):
        self.input_invoice = input_invoice
        self.order_info = order_info
        self.allow_save = allow_save
        self._type = "validateOrderInfo"