from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class Venue(ObjectBase):
    """
    Describes a venue

    :param location: Venue location; as defined by the sender
    :param title: Venue name; as defined by the sender
    :param address: Venue address; as defined by the sender
    :param provider: Provider of the venue database; as defined by the sender. Currently, only "foursquare" and "gplaces" (Google Places) need to be supported
    :param id: Identifier of the venue in the provider database; as defined by the sender
    :param type: Type of the venue in the provider database; as defined by the sender
    """
    __slots__ = ("location", "title", "address", "provider", "id", "type", "_extra", "_client_id", "_type")

    def __init__(self, location = None, title = None, address = None, provider = None, id = None, type = None):
        self.location = location
        self.title = title
        self.address = address
        self.provider = provider
        self.id = id
        self.type = type
        self._type = "venue"