from .object_base import ObjectBase

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class Video(ObjectBase):
    """
    Describes a video file

    :param duration: Duration of the video, in seconds; as defined by the sender
    :param width: Video width; as defined by the sender
    :param height: Video height; as defined by the sender
    :param file_name: Original name of the file; as defined by the sender
    :param mime_type: MIME type of the file; as defined by the sender
    :param has_stickers: True, if stickers were added to the video. The list of corresponding sticker sets can be received using getAttachedStickerSets
    :param supports_streaming: True, if the video is expected to be streamed
    :param minithumbnail: Video minithumbnail; may be null
    :param thumbnail: Video thumbnail in JPEG or MPEG4 format; as defined by the sender; may be null
    :param video: File containing the video
    """
    __slots__ = ("duration", "width", "height", "file_name", "mime_type", "has_stickers", "supports_streaming", "minithumbnail", "thumbnail", "video", "_extra", "_client_id", "_type")

    def __init__(self, duration = None, width = None, height = None, file_name = None, mime_type = None, has_stickers = None, supports_streaming = None, minithumbnail = None, thumbnail = None, video = None):
        self.duration = duration
        self.width = width
        self.height = height
        self.file_name = file_name
        self.mime_type = mime_type
        self.has_stickers = has_stickers
        self.supports_streaming = supports_streaming
        self.minithumbnail = minithumbnail
        self.thumbnail = thumbnail
        self.video = video
        self._type = "video"