from .object_base import ObjectBase
from .theme_parameters import ThemeParameters
from .web_app_open_mode import WebAppOpenMode

### FILE IS AUTOGENERATED. DO NO EDIT IT BY HAND ###

class WebAppOpenParameters(ObjectBase):
    """
    Options to be used when a Web App is opened

    :param theme: Preferred Web App theme; pass null to use the default theme
    :param application_name: Short name of the current application; 0-64 English letters, digits, and underscores
    :param mode: The mode in which the Web App is opened; pass null to open in webAppOpenModeFullSize
    """
    __slots__ = ("theme", "application_name", "mode", "_extra", "_client_id", "_type")

    def __init__(self, theme: ThemeParameters | None = None, application_name: str = "", mode: WebAppOpenMode | None = None):
        self.theme = theme
        self.application_name = application_name
        self.mode = mode
        self._type = "webAppOpenParameters"